// @ts-nocheck
import { createClient } from "@supabase/supabase-js";
import postgres from "postgres";

const SUPA_URL=Deno.env.get("SUPABASE_URL"),DB=Deno.env.get("SUPABASE_DB_URL");
if(!SUPA_URL||!DB)throw new Error("runtime vars missing");
const sql=postgres(DB,{prepare:false,max:1,idle_timeout:1,max_lifetime:30,connect_timeout:5});
const REPO="rokotove26-png/ronatrade.com";
const REF="refs/heads/release/public-go-live-v1.1";
const AUD="rona-issue635-production-browser-v1";
const SOURCE="QA_GITHUB_OIDC_ISSUE635";
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function runtimeKey(kind){const legacy=kind==="pub"?Deno.env.get("SUPABASE_ANON_KEY"):Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(legacy)return legacy;const raw=Deno.env.get(kind==="pub"?"SUPABASE_PUBLISHABLE_KEYS":"SUPABASE_SECRET_KEYS");if(raw){const p=JSON.parse(raw);if(p.default)return p.default}throw new Error("key missing")}
const service=createClient(SUPA_URL,runtimeKey("secret"),{auth:{persistSession:false,autoRefreshToken:false}});
const publicClient=()=>createClient(SUPA_URL,runtimeKey("pub"),{auth:{persistSession:false,autoRefreshToken:false}});
const json=(status,body)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","x-content-type-options":"nosniff","referrer-policy":"no-referrer"}});
const b64=s=>{s=s.replace(/-/g,"+").replace(/_/g,"/");return Uint8Array.from(atob(s+"=".repeat((4-s.length%4)%4)),c=>c.charCodeAt(0))};
async function verifyGithubOidc(token){
  const parts=String(token||"").split(".");if(parts.length!==3)throw Object.assign(new Error("OIDC_FORMAT_INVALID"),{status:401});
  const header=JSON.parse(new TextDecoder().decode(b64(parts[0]))),claims=JSON.parse(new TextDecoder().decode(b64(parts[1])));
  if(header.alg!=="RS256"||!header.kid)throw Object.assign(new Error("OIDC_HEADER_INVALID"),{status:401});
  const jwks=await fetch("https://token.actions.githubusercontent.com/.well-known/jwks",{headers:{accept:"application/json"}}).then(r=>r.ok?r.json():Promise.reject(new Error("OIDC_JWKS_HTTP_"+r.status)));
  const jwk=(jwks.keys||[]).find(k=>k.kid===header.kid);if(!jwk)throw Object.assign(new Error("OIDC_KID_UNKNOWN"),{status:401});
  const key=await crypto.subtle.importKey("jwk",jwk,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["verify"]);
  const ok=await crypto.subtle.verify("RSASSA-PKCS1-v1_5",key,b64(parts[2]),new TextEncoder().encode(parts[0]+"."+parts[1]));if(!ok)throw Object.assign(new Error("OIDC_SIGNATURE_INVALID"),{status:401});
  const now=Math.floor(Date.now()/1000);if(claims.iss!=="https://token.actions.githubusercontent.com"||claims.aud!==AUD||claims.repository!==REPO||claims.ref!==REF||!claims.sha||!/^[0-9a-f]{40}$/i.test(claims.sha)||Number(claims.exp||0)<now-30||Number(claims.nbf||0)>now+30)throw Object.assign(new Error("OIDC_CLAIMS_DENIED"),{status:403});
  if(String(claims.event_name||"")!=="push")throw Object.assign(new Error("OIDC_EVENT_DENIED"),{status:403});
  return claims;
}
function bearer(req){const h=req.headers.get("authorization")||"";return h.startsWith("Bearer ")?h.slice(7):""}
async function retire(rows,reason){for(const row of rows){const portalId=String(row.id),authId=String(row.auth_user_id||"");try{await sql.begin(async tx=>{await tx`update portal_private.portal_user_roles set status='REVOKED'::portal_private.binding_status_enum,revoked_at=coalesce(revoked_at,now()),reason=${reason},updated_at=now() where user_id=${portalId}::uuid and role='ADMIN'::portal_private.portal_role_enum and status='ACTIVE'::portal_private.binding_status_enum`;await tx`update portal_private.portal_users set status='SUSPENDED'::portal_private.portal_user_status_enum,lifecycle_state='SUSPENDED'::portal_private.lifecycle_state_enum,suspended_at=coalesce(suspended_at,now()),auth_user_id=null,updated_at=now(),source_version=coalesce(source_version,'')||'|RETIRED' where id=${portalId}::uuid`});}catch(e){console.error("retire db",e)}if(authId&&UUID_RE.test(authId))try{await service.auth.admin.deleteUser(authId,false)}catch(e){console.error("retire auth",e)}}}
async function cleanupRun(runId){const rows=await sql`select id,auth_user_id from portal_private.portal_users where source_system=${SOURCE} and source_version=${`RUN_${runId}`} and status='ACTIVE'::portal_private.portal_user_status_enum`;await retire(rows,"ISSUE635 GitHub OIDC live-preview QA cleanup");return rows.length}
async function issue(claims){const runId=String(claims.run_id||"");if(!/^\d{5,20}$/.test(runId))throw Object.assign(new Error("OIDC_RUN_ID_INVALID"),{status:403});await cleanupRun(runId);const nonce=crypto.randomUUID().replaceAll("-","").slice(0,12),login=`qa_issue635_${runId}_${nonce}`,email=`qa-issue635-${runId}-${nonce}@example.invalid`;const entropy=new Uint8Array(32);crypto.getRandomValues(entropy);const password="Aa1!"+Array.from(entropy).map(x=>x.toString(16).padStart(2,"0")).join("");const created=await service.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{rona_portal_login:login,rona_portal_display_name:"RONA ISSUE635 OIDC QA Administrator",rona_issue635_head:claims.sha}});if(created.error||!created.data?.user?.id)throw new Error("OIDC_QA_AUTH_USER_CREATE_FAILED");const authId=String(created.data.user.id),portalId=crypto.randomUUID();try{await sql.begin(async tx=>{await tx`insert into portal_private.portal_users(id,auth_user_id,login_name,display_name,status,source_system,source_version,source_timestamp,authority_state,lifecycle_state,auth_linked_at,activated_at,last_auth_verified_at,must_change_password,password_changed_at) values(${portalId}::uuid,${authId}::uuid,${login},'RONA ISSUE635 OIDC QA Administrator','ACTIVE'::portal_private.portal_user_status_enum,${SOURCE},${`RUN_${runId}`},now(),'CONFIRMED'::portal_private.authority_state_enum,'ACTIVE'::portal_private.lifecycle_state_enum,now(),now(),now(),false,now())`;await tx`insert into portal_private.portal_user_roles(user_id,role,status,granted_by,reason) values(${portalId}::uuid,'ADMIN'::portal_private.portal_role_enum,'ACTIVE'::portal_private.binding_status_enum,null,'ISSUE635 exact-head GitHub OIDC deployed-preview QA')`});const signed=await publicClient().auth.signInWithPassword({email,password});if(signed.error||!signed.data?.session?.access_token||!signed.data?.session?.refresh_token)throw new Error("OIDC_QA_SESSION_CREATE_FAILED");return{portalId,runId,session:signed.data.session}}catch(e){await retire([{id:portalId,auth_user_id:authId}],"ISSUE635 OIDC failed issuance cleanup").catch(()=>{});throw e}}
Deno.serve(async req=>{if(req.method!=="POST")return json(405,{ok:false,code:"METHOD_NOT_ALLOWED"});try{const claims=await verifyGithubOidc(bearer(req));const path=new URL(req.url).pathname;if(path.endsWith("/cleanup")){const retired=await cleanupRun(String(claims.run_id||""));return json(200,{ok:true,mode:"GITHUB_OIDC_ISSUE635",retired})}const body=await req.json().catch(()=>({}));if(body?.expectedHead&&String(body.expectedHead)!==String(claims.sha))return json(409,{ok:false,code:"EXACT_HEAD_MISMATCH"});const issued=await issue(claims);return json(200,{ok:true,mode:"GITHUB_OIDC_ISSUE635",broker_admin_id:issued.portalId,session:issued.session,head:claims.sha,run_id:issued.runId})}catch(e){console.error("issue635 oidc qa",e);const status=Number(e?.status||500);return json(status>=400&&status<600?status:500,{ok:false,code:String(e?.message||"OIDC_QA_ERROR")})}});
