import fs from 'node:fs';
import assert from 'node:assert/strict';

const source=fs.readFileSync('functions/portal/clients-agents-current-ui.js','utf8');
const polish=fs.readFileSync('functions/portal/admin-approved-polish-ui.js','utf8');
const analyticsCompat=fs.readFileSync('functions/portal/admin-approved-analytics-v455-ui.js','utf8');
const shell=fs.readFileSync('portal-src/current/admin.html','utf8');
const fastShell=fs.readFileSync('assets/portal-admin-shell-fast-v1.js','utf8');
const watchdog=fs.readFileSync('assets/portal-admin-runtime-watchdog-v1.js','utf8');

assert(source.includes("window.__RONA_CLIENTS_AGENTS_CURRENT__='20260828-single-owner-v5'"),'Current Clients/Agents v5 marker missing');
assert(source.includes("window.__RONA_ACCESS_CURRENT_OWNER__='clients-agents-current-v5'"),'Single access owner marker missing');
assert(source.includes("'Создать пользователя'"),'Primary create-user action missing');
assert(source.includes("new Option('Клиент','Клиент'),new Option('Агент','Агент')"),'Client/Agent role selector missing');
assert(source.includes("role:isAgent?'Агент':'Клиент'"),'Role-aware access payload missing');
assert(!source.includes('agentScope'),'Legacy Agent profile/scope payload must be absent');
assert(!source.includes('Профиль агента'),'Legacy Agent profile field must be absent');
assert(source.includes("Компании назначаются агентам отдельно"),'Agent creation must state that company assignment is separate');
assert(source.includes("contractIds:isAgent?[]:ids"),'Client/Agent contract policy missing');
assert(source.includes("openWithoutContract:!isAgent&&openWithout.checked"),'Fail-closed pre-contract onboarding option missing');
assert(source.includes("bindingRole:bindingRole.value"),'Client representation role payload missing');
assert(source.includes("makeField('Единый логин',login)"),'Separate unified-login field missing');
assert(source.includes("makeField('Электронная почта',email)"),'Separate email field missing');
assert(source.includes("makeField('Пароль',password)"),'Initial password field missing');
assert(source.includes("makeField('Повторите пароль',repeat)"),'Repeated initial password field missing');
assert(source.includes("initialPassword:pw1"),'Initial password payload missing');
assert(source.includes("await mutate('/access/users',payload)"),'Account creation must call current authority directly');
assert(source.includes("'/signed-document/attach'"),'Signed contract PDF attachment route missing');
assert(source.includes("'Сменить пароль'"),'Administrator password reset control missing');
assert(source.includes("['history','История и права']"),'History and rights view missing');
assert(source.includes("const clientContract=kind===''||kind==='CLIENT_CONTRACT'"),'Agent bindings must not use Client contract mutation routes');
assert(source.includes("dataset.ronaCreateAccess='primary'"),'Primary create access marker missing');
assert(source.includes("'x-rona-access-create':'single-owner-create-agent-v7'"),'Access-create response marker missing');
assert(source.includes("'x-rona-access-create-owner':'clients-agents-current-v5'"),'Access-create owner response marker missing');
assert(source.includes("'x-rona-admin-nav-owner':'external-current-router-v2'"),'External navigation-owner contract missing');
assert(source.includes("'x-rona-shell-mutation':'none'"),'No-global-shell-mutation contract missing');
for(const stale of ['openCanonicalAccessModal','installCanonicalAccessCreate','approved-canonical-v3.4.13','admin-canonical-create-access-v441-ui','rona-approved-access-mask','rona-canonical-access-mask'])assert(!source.includes(stale),'Competing access runtime marker remains: '+stale);
assert(!polish.includes('installCanonicalAccessCreate')&&!polish.includes('openCanonicalAccessModal'),'Polish runtime must not own access creation');
assert(polish.includes("'x-rona-access-create-owner':'none'"),'Polish runtime must explicitly declare no access owner');
assert(!analyticsCompat.includes('loadCanonicalAccess')&&!analyticsCompat.includes('admin-canonical-create-access-v441-ui'),'Analytics compatibility runtime must not load access UI');
assert(analyticsCompat.includes("'x-rona-access-loader':'none'"),'Analytics compatibility runtime must explicitly declare no access loader');
assert(!source.includes('installNavigationStability'),'Access page must not install a second navigation owner');
assert(!source.includes('installShellParity'),'Access page must not restyle the global shell');
assert(shell.includes("window.__RONA_ADMIN_CURRENT_ROUTER__='current-only-router-v2'"),'Navigation must be owned by current shell');
assert(shell.includes('grid-template-columns:272px minmax(0,1fr)'),'Canonical Home-scale sidebar must live in shell');
assert(shell.includes('/assets/portal-admin-shell-fast-v1.js?v=20260919-admin-access-stability-v3'),'Admin shell must cache-bust the stability shell runtime');
assert(shell.includes('/portal/clients-agents-current-ui?v=20260919-admin-access-stability-v3'),'Admin shell must cache-bust the Access current runtime');
assert(shell.includes('/assets/portal-admin-runtime-watchdog-v1.js?v=20260919-admin-access-stability-v3'),'Admin shell must cache-bust the stability watchdog runtime');
assert(source.includes("window.__RONA_CLIENTS_AGENTS_CURRENT_STATE__='BOOTING'"),'Access runtime boot lifecycle marker missing');
assert(source.includes('window.__RONA_CLIENTS_AGENTS_CURRENT_REPAIR__=repair'),'Access runtime in-place repair hook missing');
assert(source.includes("window.__RONA_CLIENTS_AGENTS_CURRENT_STATE__='READY_STALE'"),'Access runtime must preserve last-good workspace on transient refresh failure');
assert(source.includes('window.__RONA_CLIENTS_AGENTS_CURRENT_ROOT_GUARD__=rootGuard'),'Access runtime root survival guard missing');
assert(source.includes("let s=q('#ronaCaCurrentStyleV5');if(!s)"),'Access style owner must refresh an existing style node instead of freezing stale CSS');
assert(source.includes(".ca-modal .ca-btn.ca-danger"),'Modal destructive style missing');
assert(source.includes("remove.dataset.ronaDangerAction='entity-delete'"),'Delete company inline destructive fallback missing');
assert(source.includes('if(window.__RONA_CLIENTS_AGENTS_CURRENT_READY__&&r&&accessRootHealthy())'),'Access refresh must preserve last-good DOM');
assert(fastShell.includes('const accessReady=()=>window.__RONA_CLIENTS_AGENTS_CURRENT_READY__===true&&!!accessHost()'),'Fast shell must use stable access readiness');
assert(fastShell.includes('waitAccessReady(14000)'),'Fast shell must allow bounded async access bootstrap without teardown');
assert(fastShell.includes('CURRENT_RUNTIME_NOT_READY_WITHOUT_TEARDOWN'),'Fast shell must fail non-destructively while access runtime is booting');
assert(!fastShell.includes('window.__RONA_CLIENTS_AGENTS_CURRENT__=null'),'Fast shell must not clear a live Access runtime marker during recovery');
assert(watchdog.includes("if(p==='access')return window.__RONA_CLIENTS_AGENTS_CURRENT_READY__===true&&!!n.querySelector(':scope > #rona-ca4')"),'Watchdog must use stable Access workspace readiness');

const fnStart=source.indexOf('function currentUiRuntime(){');
const fnEnd=source.indexOf("\nconst SCRIPT='('+currentUiRuntime.toString()+')();';");
assert(fnStart>=0&&fnEnd>fnStart,'Runtime function boundary missing');
const fnText=source.slice(fnStart,fnEnd);
const runtimeFunction=(0,eval)('('+fnText.replace(/^function currentUiRuntime/,'function')+')');
assert.equal(typeof runtimeFunction,'function','Browser runtime must parse as JavaScript');
console.log('Admin current access single-owner v5 QA: PASS');
