import fs from 'node:fs';
import assert from 'node:assert/strict';

const source=fs.readFileSync('functions/portal/clients-agents-current-ui.js','utf8');
const polish=fs.readFileSync('functions/portal/admin-approved-polish-ui.js','utf8');
const analyticsCompat=fs.readFileSync('functions/portal/admin-approved-analytics-v455-ui.js','utf8');
const shell=fs.readFileSync('portal-src/current/admin.html','utf8');

assert(source.includes("window.__RONA_CLIENTS_AGENTS_CURRENT__='20260828-single-owner-v5'"),'Current Clients/Agents v5 marker missing');
assert(source.includes("window.__RONA_ACCESS_CURRENT_OWNER__='clients-agents-current-v5'"),'Single access owner marker missing');
assert(source.includes("'Создать пользователя'"),'Primary create-user action missing');
assert(source.includes("new Option('Клиент','Клиент'),new Option('Агент','Агент')"),'Client/Agent role selector missing');
assert(source.includes("role:isAgent?'Агент':'Клиент'"),'Role-aware access payload missing');
assert(source.includes('payload.agentScope=scope'),'Agent profile binding missing');
assert(source.includes("contractIds:isAgent?[]:ids"),'Client/Agent contract policy missing');
assert(source.includes("openWithoutContract:!isAgent&&openWithout.checked"),'Fail-closed pre-contract onboarding option missing');
assert(source.includes("bindingRole:bindingRole.value"),'Client representation role payload missing');
assert(source.includes("makeField('Единый логин',login)"),'Separate unified-login field missing');
assert(source.includes("makeField('Электронная почта',email)"),'Separate email field missing');
assert(source.includes("makeField('Пароль',password)"),'Initial password field missing');
assert(source.includes("makeField('Повторите пароль',repeat)"),'Repeated initial password field missing');
assert(source.includes("initialPassword:pw1"),'Initial password payload missing');
assert(source.includes("await mutate('/access/users',payload)"),'Account creation must call current authority directly');
assert(source.includes("'/signed-document/attach'"),'Signed contract PDF attachment route missing');
assert(source.includes("'Сменить пароль'"),'Administrator password reset control missing');
assert(source.includes("['history','История и права']"),'History and rights view missing');
assert(source.includes("const clientContract=kind===''||kind==='CLIENT_CONTRACT'"),'Agent bindings must not use Client contract mutation routes');
assert(source.includes("dataset.ronaCreateAccess='primary'"),'Primary create access marker missing');
assert(source.includes("'x-rona-access-create':'single-owner-create-user-v6'"),'Access-create response marker missing');
assert(source.includes("'x-rona-access-create-owner':'clients-agents-current-v5'"),'Access-create owner response marker missing');
assert(source.includes("'x-rona-admin-nav-owner':'external-current-router-v2'"),'External navigation-owner contract missing');
assert(source.includes("'x-rona-shell-mutation':'none'"),'No-global-shell-mutation contract missing');
for(const stale of ['openCanonicalAccessModal','installCanonicalAccessCreate','approved-canonical-v3.4.13','admin-canonical-create-access-v441-ui','rona-approved-access-mask','rona-canonical-access-mask'])assert(!source.includes(stale),'Competing access runtime marker remains: '+stale);
assert(!polish.includes('installCanonicalAccessCreate')&&!polish.includes('openCanonicalAccessModal'),'Polish runtime must not own access creation');
assert(polish.includes("'x-rona-access-create-owner':'none'"),'Polish runtime must explicitly declare no access owner');
assert(!analyticsCompat.includes('loadCanonicalAccess')&&!analyticsCompat.includes('admin-canonical-create-access-v441-ui'),'Analytics compatibility runtime must not load access UI');
assert(analyticsCompat.includes("'x-rona-access-loader':'none'"),'Analytics compatibility runtime must explicitly declare no access loader');
assert(!source.includes('installNavigationStability'),'Access page must not install a second navigation owner');
assert(!source.includes('installShellParity'),'Access page must not restyle the global shell');
assert(shell.includes("window.__RONA_ADMIN_CURRENT_ROUTER__='current-only-router-v2'"),'Navigation must be owned by current shell');
assert(shell.includes('grid-template-columns:272px minmax(0,1fr)'),'Canonical Home-scale sidebar must live in shell');

const fnStart=source.indexOf('function currentUiRuntime(){');
const fnEnd=source.indexOf("\nconst SCRIPT='('+currentUiRuntime.toString()+')();';");
assert(fnStart>=0&&fnEnd>fnStart,'Runtime function boundary missing');
const fnText=source.slice(fnStart,fnEnd);
const runtimeFunction=(0,eval)('('+fnText.replace(/^function currentUiRuntime/,'function')+')');
assert.equal(typeof runtimeFunction,'function','Browser runtime must parse as JavaScript');
console.log('Admin current access single-owner v5 QA: PASS');
