const SUPABASE_URL='https://sxawrwzeobaqwwmlkzws.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_W2MxTx00ILiugSyZKp8uyQ_zBzcyorL';
const PORTAL_API=`${SUPABASE_URL}/functions/v1/rona-portal-api`;
const LEGACY_STATE_API=`${SUPABASE_URL}/functions/v1/rona-temp-upload-order-20260816`;
const ACCESS_COOKIE='rona_portal_at';
const REFRESH_COOKIE='rona_portal_rt';
const REALIZATION_SOURCE='SERVER_AUTHORITATIVE_REALIZATION_V1';
const RESOURCE_AUTHORITY='PORTAL_CONTEXT_CANONICAL_RESOURCE_V1';
const SECURITY_HEADERS=Object.freeze({'cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache','referrer-policy':'no-referrer','x-content-type-options':'nosniff','x-frame-options':'DENY','permissions-policy':'camera=(), microphone=(), geolocation=(), payment=()','cross-origin-opener-policy':'same-origin','cross-origin-resource-policy':'same-origin'});

function norm(v){return String(v??'').trim()}
function upper(v){return norm(v).toUpperCase()}
function parseCookies(header){const out={};for(const item of String(header||'').split(';')){const i=item.indexOf('=');if(i<1)continue;const k=item.slice(0,i).trim(),v=item.slice(i+1).trim();if(k)out[k]=v}return out}
function accessCookie(token,maxAge=3600){return `${ACCESS_COOKIE}=${token}; Max-Age=${Math.max(0,Number(maxAge)||0)}; Path=/portal; Secure; HttpOnly; SameSite=Lax`}
function refreshCookie(token,maxAge=604800){return `${REFRESH_COOKIE}=${token}; Max-Age=${Math.max(0,Number(maxAge)||0)}; Path=/portal; Secure; HttpOnly; SameSite=Lax`}
function clearCookies(){return[`${ACCESS_COOKIE}=; Max-Age=0; Path=/portal; Secure; HttpOnly; SameSite=Lax`,`${REFRESH_COOKIE}=; Max-Age=0; Path=/portal; Secure; HttpOnly; SameSite=Lax`]}
function tokenCookies(t){const e=Math.min(Math.max(Number(t?.expires_in||3600),60),7200);return[accessCookie(t.access_token,e),refreshCookie(t.refresh_token,604800)]}
function headers(base=new Headers()){const h=new Headers(base);for(const[k,v]of Object.entries(SECURITY_HEADERS))h.set(k,v);h.delete('access-control-allow-origin');h.delete('access-control-allow-credentials');h.delete('content-length');h.delete('etag');return h}
function json(body,status=200,cookies=[],extra={}){const h=headers(new Headers({'content-type':'application/json; charset=utf-8',...extra}));for(const c of cookies)h.append('set-cookie',c);return new Response(JSON.stringify(body),{status,headers:h})}
function sameOrigin(request){const u=new URL(request.url),origin=request.headers.get('origin');if(origin)return origin===u.origin;const ref=request.headers.get('referer');if(!ref)return request.method==='GET';try{return new URL(ref).origin===u.origin}catch{return false}}
async function authRefresh(refreshToken){const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,'content-type':'application/json'},body:JSON.stringify({refresh_token:refreshToken})});const data=await r.json().catch(()=>({}));return{ok:r.ok,status:r.status,data}}
async function edgeGet(base,path,access){return fetch(`${base}${path}`,{method:'GET',headers:{authorization:`Bearer ${access}`,accept:'application/json'},cache:'no-store',redirect:'manual'})}
function resourceProjection(deal){const status=upper(deal?.resource_status);if(!['RESOURCE_CONFIRMED','RESOURCE_PENDING','RESOURCE_DENIED'].includes(status))return null;return{status,source:norm(deal?.resource_source)||'NO_AUTHORITATIVE_RESOURCE_FACT',confirmed_at:deal?.resource_confirmed_at||null}}
function finite(v){const n=Number(v);return Number.isFinite(n)?n:null}
function paymentProjection(deal){const status=upper(deal?.payment_status),label=norm(deal?.payment_label),due=finite(deal?.payment_due_now);if(status==='PAID')return{key:'payment',state:'DONE',detail:label||'Оплачено 100%'};if(status==='OVERDUE')return{key:'payment',state:'CURRENT',detail:label||'Оплата просрочена'};if(['AWAITING_PAYMENT','DUE','PAYMENT_DUE'].includes(status))return{key:'payment',state:'CURRENT',detail:label||'Ожидается оплата'};if(status==='PARTIALLY_PAID')return{key:'payment',state:due!==null&&due>0?'CURRENT':'PENDING',detail:label||'Частичная оплата подтверждена'};if(status==='NOT_DUE')return{key:'payment',state:'PENDING',detail:label||'Срок оплаты ещё не наступил'};return{key:'payment',state:'PENDING',detail:label||'Статус оплаты уточняется'}}
function documentProjection(row){const signed=Boolean(row?.signed_supplement_document_key&&row?.signed_addendum_document_id&&upper(row?.signed_lifecycle_state)==='ACTIVE'&&['CONFIRMED','VERIFIED'].includes(upper(row?.signed_authority_state)));return{key:'documents',state:signed?'DONE':'PENDING',detail:signed?'Документы подписаны':'Ожидается подписание документов'}}
function logisticsProjection(row){const status=upper(row?.shipment_status);if(!status)return{key:'logistics',state:'PENDING',detail:'Отгрузка ещё не начата'};if(status==='PLANNED')return{key:'logistics',state:'PENDING',detail:'Отгрузка запланирована'};if(status==='OPEN')return{key:'logistics',state:'CURRENT',detail:'Отгрузка открыта'};if(status==='IN_TRANSIT')return{key:'logistics',state:'CURRENT',detail:'Груз в пути'};if(status==='ARRIVED')return{key:'logistics',state:'CURRENT',detail:'Груз прибыл, ожидается завершение поставки'};if(['UNLOADED','CLOSED'].includes(status))return{key:'logistics',state:'DONE',detail:status==='UNLOADED'?'Груз выгружен':'Поставка завершена'};if(status==='CANCELLED')return{key:'logistics',state:'BLOCKED',detail:'Отгрузка отменена'};return{key:'logistics',state:'CURRENT',detail:'Отгрузка выполняется'}}
function closureProjection(row){const status=upper(row?.accounting_closure_status);if(status==='CLOSED'||row?.closed_at)return{key:'close',state:'DONE',detail:'Сделка закрыта'};if(status==='PENDING_RECONCILIATION')return{key:'close',state:'CURRENT',detail:'Идёт сверка и закрытие сделки'};return{key:'close',state:'PENDING',detail:'Закрытие сделки ещё предстоит'}}
function patchRealization(raw,resource,deal,row){const original=raw&&typeof raw==='object'?raw:null;if(!original||original.source!==REALIZATION_SOURCE||!Array.isArray(original.stages))return null;const resourceStage=resource.status==='RESOURCE_CONFIRMED'?{key:'resource',state:'DONE',detail:'Ресурс подтверждён'}:resource.status==='RESOURCE_DENIED'?{key:'resource',state:'BLOCKED',detail:'Ресурс не подтверждён'}:{key:'resource',state:'PENDING',detail:'Ресурс пока не подтверждён'};const stages=[{key:'contract',state:'DONE',detail:'Сделка зарегистрирована и доступна в кабинете'},documentProjection(row),resourceStage,paymentProjection(deal),logisticsProjection(row),closureProjection(row)];for(const s of stages)if(!['DONE','CURRENT','PENDING','BLOCKED'].includes(s.state))return null;return{...original,source:REALIZATION_SOURCE,completed_count:stages.filter(s=>s.state==='DONE').length,total_count:stages.length,current_stage_key:stages.find(s=>s.state==='CURRENT')?.key||null,has_blocker:stages.some(s=>s.state==='BLOCKED'),stages}
}
async function fetchAuthoritative(access,clientId,contractId){const query=`?clientId=${encodeURIComponent(clientId)}&contractId=${encodeURIComponent(contractId)}`;const [legacy,canonical]=await Promise.all([edgeGet(LEGACY_STATE_API,`/v1/client/deal-documents/state${query}`,access),edgeGet(PORTAL_API,`/v1/client/context${query}`,access)]);return{legacy,canonical}}
async function buildResponse(pair,clientId,contractId,cookies){const legacyBody=await pair.legacy.json().catch(()=>null),canonicalBody=await pair.canonical.json().catch(()=>null);if(!pair.legacy.ok||!legacyBody||legacyBody.ok===false)return json(legacyBody||{ok:false,code:`WORKFLOW_STATE_${pair.legacy.status}`},pair.legacy.status,cookies);if(!pair.canonical.ok||!canonicalBody||canonicalBody.ok===false)return json(canonicalBody||{ok:false,code:`CANONICAL_CONTEXT_${pair.canonical.status}`},pair.canonical.status,cookies);
  const data=canonicalBody.data,contract=data?.contract;if(norm(contract?.client_id)!==clientId||norm(contract?.contract_id)!==contractId)return json({ok:false,code:'CANONICAL_CONTEXT_SCOPE_MISMATCH'},409,cookies);
  const canonicalDeals=Array.isArray(data?.deals)?data.deals:[],canonicalMap=new Map();for(const deal of canonicalDeals){const id=norm(deal?.deal_id);if(!id||canonicalMap.has(id))return json({ok:false,code:'CANONICAL_DEAL_SCOPE_INVALID'},502,cookies);canonicalMap.set(id,deal)}
  const workflowDeals=Array.isArray(legacyBody?.deals)?legacyBody.deals:null;if(!workflowDeals)return json({ok:false,code:'WORKFLOW_STATE_INVALID'},502,cookies);const seen=new Set(),out=[];for(const row of workflowDeals){const id=norm(row?.deal_id);if(!id||seen.has(id))return json({ok:false,code:'WORKFLOW_DEAL_SCOPE_INVALID'},502,cookies);seen.add(id);const authoritative=canonicalMap.get(id),resource=resourceProjection(authoritative);if(!authoritative||!resource)return json({ok:false,code:'CANONICAL_RESOURCE_FACT_REQUIRED',deal_id:id},502,cookies);const realization=patchRealization(row?.realization_status,resource,authoritative,row);if(!realization)return json({ok:false,code:'WORKFLOW_REALIZATION_INVALID',deal_id:id},502,cookies);out.push({...row,resource_status:resource.status,resource_source:resource.source,resource_confirmed_at:resource.confirmed_at,realization_status:realization})}
  return json({ok:true,deals:out,resource_authority:RESOURCE_AUTHORITY},200,cookies,{'x-rona-resource-authority':RESOURCE_AUTHORITY,'x-rona-workflow-composition':'canonical-resource-v1'})
}
export async function onRequest(context){const request=context.request;if(request.method!=='GET')return json({ok:false,code:'METHOD_NOT_ALLOWED'},405);if(!sameOrigin(request))return json({ok:false,code:'ORIGIN_DENIED'},403);const url=new URL(request.url),clientId=norm(url.searchParams.get('clientId')),contractId=norm(url.searchParams.get('contractId'));if(!clientId||!contractId)return json({ok:false,code:'CLIENT_CONTRACT_CONTEXT_REQUIRED'},400);const parsed=parseCookies(request.headers.get('cookie')),refresh=parsed[REFRESH_COOKIE]||'';let access=parsed[ACCESS_COOKIE]||'',setCookies=[];if(!access&&!refresh)return json({ok:false,code:'PORTAL_ACCESS_DENIED'},401,clearCookies());let pair=access?await fetchAuthoritative(access,clientId,contractId):null;if(!pair||pair.legacy.status===401||pair.canonical.status===401){if(!refresh)return json({ok:false,code:'PORTAL_ACCESS_DENIED'},401,clearCookies());const next=await authRefresh(refresh).catch(()=>null);if(!next?.ok||!next.data?.access_token||!next.data?.refresh_token){if(next&&[429,500,502,503,504].includes(next.status))return json({ok:false,code:'PORTAL_AUTH_BACKEND_UNAVAILABLE',retryable:true},503);return json({ok:false,code:'PORTAL_ACCESS_DENIED'},401,clearCookies())}access=next.data.access_token;setCookies=tokenCookies(next.data);pair=await fetchAuthoritative(access,clientId,contractId)}return buildResponse(pair,clientId,contractId,setCookies)}
