import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const source=readFileSync(new URL('../../supabase/functions/rona-mcp-gateway/index.ts',import.meta.url),'utf8');
const start=source.indexOf('function executionRecovery(data, ctx) {');
const end=source.indexOf('async function compactCurrentStateResponse',start);
const run=vm.runInNewContext("const scopeHas=(s,v)=>String(s||'').split(/\\s+/).includes(v);"+source.slice(start,end)+";executionRecovery");
const ctx={server_slug:'rona-mcp-system-admin',role:'SYSTEM_ADMIN',identity_id:'AI-SYSTEM-ADMIN',scope:'mcp:read mcp:coordinate'};
const data={active_tasks:[],coordination:{records:[{record_id:'latest',record_type:'FUNCTIONAL_CONCLUSION'},{record_id:'incoming',record_type:'HANDOFF_REQUEST',target_role:'SYSTEM_ADMIN',status:'REQUESTED'}]}};
const result=run(data,ctx);
assert.equal(result.transport.server_slug,ctx.server_slug);
assert.equal(result.transport.identity_id,ctx.identity_id);
assert.equal(result.write_scope_granted,true);
assert.equal(result.write_tools.length,6);
assert.equal(result.latest_coordination_record_id,'latest');
assert.equal(result.incoming_handoff_record_ids[0],'incoming');
assert.equal(result.active_task_ids.length,0);
assert.equal(run(data,{...ctx,scope:'mcp:read'}).write_tools.length,0);
assert.ok(source.includes('if (ctx && primaryTechnicalCtx(ctx)) data.execution_recovery'));
console.log('PASS: recovery actual identity/scope, latest record, incoming work, empty tasks and read-only scope');
