const SUPABASE_URL='https://sxawrwzeobaqwwmlkzws.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_W2MxTx00ILiugSyZKp8uyQ_zBzcyorL';
const MAIN_API=`${SUPABASE_URL}/functions/v1/rona-portal-api`;
const PR429_PREVIEW_API=`${SUPABASE_URL}/functions/v1/rona-portal-api-candidate-20260817`;
const MAIN_BOOTSTRAP_API=`${MAIN_API}/v1/client/bootstrap`;
const PR429_PREVIEW_BOOTSTRAP_API=`${PR429_PREVIEW_API}/v1/client/bootstrap`;
const MAIN_CONTEXT_API=`${MAIN_API}/v1/client/context`;
const PR429_PREVIEW_CONTEXT_API=`${PR429_PREVIEW_API}/v1/client/context`;
const DIRECTORY_SOURCE='AUTHORITATIVE_AUTHORIZED_CONTEXT_DIRECTORY_DB';
const DOCUMENTS_PREDICATE='CURRENT_EFFECTIVE_CONTRACTUAL_ONLY';
const ACCESS_COOKIE='rona_portal_at';
const REFRESH_COOKIE='rona_portal_rt';
const SECURITY_HEADERS=Object.freeze({'cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache','referrer-policy':'no-referrer','x-content-type-options':'nosniff','x-frame-options':'DENY','permissions-policy':'camera=(), microphone=(), geolocation=(), payment=()','cross-origin-opener-policy':'same-origin','cross-origin-resource-policy':'same-origin'});
function parseCookies(header){const out={};for(const item of String(header||'').split(';')){const i=item.indexOf('=');if(i<1)continue;const k=item.slice(0,i).trim(),v=item.slice(i+1).trim();if(k)out[k]=v}return out}
function accessCookie(token,maxAge=3600){return `${ACCESS_COOKIE}=${token}; Max-Age=${Math.max(0,Number(maxAge)||0)}; Path=/portal; Secure; HttpOnly; SameSite=Lax`}
function refreshCookie(token,maxAge=604800){return `${REFRESH_COOKIE}=${token}; Max-Age=${Math.max(0,Number(maxAge)||0)}; Path=/portal; Secure; HttpOnly; SameSite=Lax`}
function clearCookies(){return[`${ACCESS_COOKIE}=; Max-Age=0; Path=/portal; Secure; HttpOnly; SameSite=Lax`,`${REFRESH_COOKIE}=; Max-Age=0; Path=/portal; Secure; HttpOnly; SameSite=Lax`]}
function tokenCookies(t){const e=Math.min(Math.max(Number(t?.expires_in||3600),60),7200);return[accessCookie(t.access_token,e),refreshCookie(t.refresh_token,604800)]}
function secureHeaders(){const h=new Headers({'content-type':'application/json; charset=utf-8'});for(const[k,v]of Object.entries(SECURITY_HEADERS))h.set(k,v);return h}
function json(body,status=200,cookies=[]){const h=secureHeaders();for(const c of cookies)h.append('set-cookie',c);return new Response(JSON.stringify(body),{status,headers:h})}
function sameOrigin(request){const u=new URL(request.url),origin=request.headers.get('origin');if(origin)return origin===u.origin;const ref=request.headers.get('referer');if(!ref)return request.method==='GET';try{return new URL(ref).origin===u.origin}catch{return false}}
async function authRefresh(refreshToken){const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,'content-type':'application/json'},body:JSON.stringify({refresh_token:refreshToken})});const data=await r.json().catch(()=>({}));return{ok:r.ok,status:r.status,data}}
async function upstream(target,access){return fetch(target,{headers:{authorization:`Bearer ${access}`,accept:'application/json'},cache:'no-store'})}
async function notifications(access){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/portal_client_recent_event_results_v1`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,authorization:`Bearer ${access}`,'content-type':'application/json',accept:'application/json'},body:'{}'});if(!r.ok)return[];const body=await r.json().catch(()=>[]);return Array.isArray(body)?body:[]}
function norm(v){return String(v??'').trim()}
function safePriceAuthority(a){const publicationStatus=String(a?.publication_status??'').toUpperCase(),publicationAuthority=String(a?.publication_authority_state??'').toUpperCase(),publicationLifecycle=String(a?.publication_lifecycle_state??'').toUpperCase(),itemAuthority=String(a?.item_authority_state??'').toUpperCase(),itemLifecycle=String(a?.item_lifecycle_state??'').toUpperCase(),businessStatus=String(a?.business_status??'').toUpperCase();if(publicationStatus!=='PUBLISHED'||!['CONFIRMED','VERIFIED'].includes(publicationAuthority)||publicationLifecycle!=='ACTIVE'||!['CONFIRMED','VERIFIED'].includes(itemAuthority)||itemLifecycle!=='ACTIVE'||businessStatus!=='PUBLISHED'||a?.publish_client!==true)return null;return{publication_item_id:a?.publication_item_id??null,publication_id:a?.publication_id??null,publication_status:publicationStatus,publication_authority_state:publicationAuthority,publication_lifecycle_state:publicationLifecycle,item_authority_state:itemAuthority,item_lifecycle_state:itemLifecycle,product:a?.product??null,producer:a?.producer??null,supplier:a?.supplier??null,snapshot_basis:a?.snapshot_basis??null,final_station:a?.final_station??null,snapshot_price:a?.snapshot_price??null,snapshot_currency:a?.snapshot_currency??null,payment_terms:a?.payment_terms??null,commercial_terms:a?.commercial_terms??null,business_status:businessStatus,publish_client:true,client_published_at:a?.client_published_at??null,updated_at:a?.updated_at??null}}
function safeCompanyDirectory(rows){return(Array.isArray(rows)?rows:[]).map(c=>{const signed=c?.current_signed_contract&&typeof c.current_signed_contract==='object'?{document_id:c.current_signed_contract?.document_id??null,storage_object_id:c.current_signed_contract?.storage_object_id??null,authoritative_filename:c.current_signed_contract?.authoritative_filename??null}:null;return{client_id:c?.client_id??null,legal_name:c?.legal_name??null,registration_country:c?.registration_country??null,contract_id:c?.contract_id??null,current_external_contract_number:c?.current_external_contract_number??null,contract_status:c?.contract_status??null,effective_from:c?.effective_from??null,effective_to:c?.effective_to??null,applications_total:c?.applications_total??null,deals_total:c?.deals_total??null,documents_total:c?.documents_total??null,documents_predicate:c?.documents_predicate??null,source:c?.source??null,current_signed_contract:signed}})}
function safeBootstrap(data,notes,preview=false){const contexts=(Array.isArray(data?.contexts)?data.contexts:[]).map(c=>({client_id:c?.client_id??null,legal_name:c?.legal_name??null,registration_country:c?.registration_country??null,registered_address:c?.registered_address??null,contact_phone:c?.contact_phone??null,contract_id:c?.contract_id??null,current_external_contract_number:c?.current_external_contract_number??null,contract_status:c?.contract_status??null,effective_from:c?.effective_from??null,effective_to:c?.effective_to??null,verification_status:'CONFIRMED_CURRENT',verification_source:'AUTHORITATIVE_CONTRACT_ACCESS_GATE'}));const price_authority=(Array.isArray(data?.price_authority)?data.price_authority:[]).map(safePriceAuthority).filter(Boolean);const directorySource=String(data?.company_directory_source??'');const directoryAuthorized=directorySource===DIRECTORY_SOURCE;return{generated_at:data?.generated_at??null,data_contract:data?.data_contract??null,requires_context_selection:Boolean(data?.requires_context_selection??contexts.length>1),contexts,...(directoryAuthorized?{company_directory_source:directorySource,company_directory:safeCompanyDirectory(data?.company_directory)}:{}),price_authority,notifications:Array.isArray(notes)?notes:[]}}
function exactContexts(data){return(Array.isArray(data?.contexts)?data.contexts:[]).map(c=>({client_id:norm(c?.client_id),contract_id:norm(c?.contract_id),legal_name:norm(c?.legal_name),registration_country:norm(c?.registration_country),current_external_contract_number:norm(c?.current_external_contract_number),contract_status:norm(c?.contract_status),effective_from:c?.effective_from??null,effective_to:c?.effective_to??null})).filter(c=>c.client_id&&c.contract_id)}
function integerMetric(v){const n=Number(v);return Number.isInteger(n)&&n>=0?n:null}
function completeDirectory(data,contexts){if(norm(data?.company_directory_source)!==DIRECTORY_SOURCE)return false;const rows=Array.isArray(data?.company_directory)?data.company_directory:[];if(rows.length!==contexts.length)return false;const expected=new Set(contexts.map(c=>`${c.client_id}|${c.contract_id}`)),seen=new Set();for(const row of rows){const k=`${norm(row?.client_id)}|${norm(row?.contract_id)}`;if(!expected.has(k)||seen.has(k)||norm(row?.source)!==DIRECTORY_SOURCE||norm(row?.documents_predicate)!==DOCUMENTS_PREDICATE||integerMetric(row?.applications_total)===null||integerMetric(row?.deals_total)===null||integerMetric(row?.documents_total)===null)return false;seen.add(k)}return seen.size===expected.size}
function currentSignedContract(documents,ctx){const rows=Array.isArray(documents)?documents:[];const exact=rows.find(d=>norm(d?.document_id)===ctx.contract_id&&norm(d?.storage_object_id)&&norm(d?.authoritative_filename));return exact?{document_id:norm(exact.document_id),storage_object_id:norm(exact.storage_object_id),authoritative_filename:norm(exact.authoritative_filename)}:null}
async function contextDirectoryRow(target,access,ctx){const url=new URL(target);url.searchParams.set('clientId',ctx.client_id);url.searchParams.set('contractId',ctx.contract_id);const r=await upstream(url.toString(),access);const payload=await r.json().catch(()=>null);if(!r.ok||!payload?.ok||!payload?.data)throw new Error('CLIENT_COMPANY_DIRECTORY_CONTEXT_UNAVAILABLE');const data=payload.data,contract=data?.contract||{};if(norm(contract.client_id)!==ctx.client_id||norm(contract.contract_id)!==ctx.contract_id)throw new Error('CLIENT_COMPANY_DIRECTORY_SCOPE_MISMATCH');const applications=Array.isArray(data.applications)?data.applications:[],deals=Array.isArray(data.deals)?data.deals:[],documents=Array.isArray(data.documents)?data.documents:[];return{client_id:ctx.client_id,legal_name:ctx.legal_name||norm(contract.legal_name)||null,registration_country:ctx.registration_country||null,contract_id:ctx.contract_id,current_external_contract_number:ctx.current_external_contract_number||norm(contract.current_external_contract_number)||ctx.contract_id,contract_status:ctx.contract_status||norm(contract.contract_status)||null,effective_from:ctx.effective_from??contract.effective_from??null,effective_to:ctx.effective_to??contract.effective_to??null,applications_total:applications.length,deals_total:deals.length,documents_total:documents.length,documents_predicate:DOCUMENTS_PREDICATE,source:DIRECTORY_SOURCE,current_signed_contract:currentSignedContract(documents,ctx)}}
async function ensureCompanyDirectory(data,access,preview){const contexts=exactContexts(data);if(!contexts.length)return data;if(completeDirectory(data,contexts))return data;const target=preview?PR429_PREVIEW_CONTEXT_API:MAIN_CONTEXT_API;const rows=[];for(const ctx of contexts)rows.push(await contextDirectoryRow(target,access,ctx));return{...data,company_directory_source:DIRECTORY_SOURCE,company_directory:rows}}
function isPr429Preview(request){const host=new URL(request.url).hostname.toLowerCase();return host.endsWith('.rona-trade-public.pages.dev')}
export async function onRequest(context){
  const request=context.request;
  if(request.method!=='GET')return json({ok:false,code:'METHOD_NOT_ALLOWED'},405);
  if(!sameOrigin(request))return json({ok:false,code:'ORIGIN_DENIED'},403);
  const preview=isPr429Preview(request),target=preview?PR429_PREVIEW_BOOTSTRAP_API:MAIN_BOOTSTRAP_API;
  const cookies=parseCookies(request.headers.get('cookie'));let access=cookies[ACCESS_COOKIE]||'',refresh=cookies[REFRESH_COOKIE]||'',setCookies=[];
  if(!access&&refresh){const next=await authRefresh(refresh);if(next.ok&&next.data?.access_token&&next.data?.refresh_token){access=next.data.access_token;setCookies=tokenCookies(next.data)}}
  if(!access)return json({ok:false,code:'PORTAL_ACCESS_DENIED'},401,clearCookies());
  let r=await upstream(target,access);
  if(r.status===401&&refresh){const next=await authRefresh(refresh);if(next.ok&&next.data?.access_token&&next.data?.refresh_token){access=next.data.access_token;setCookies=tokenCookies(next.data);r=await upstream(target,access)}}
  if(r.status===401)return json({ok:false,code:'PORTAL_ACCESS_DENIED'},401,clearCookies());
  const body=await r.json().catch(()=>null);
  if(!r.ok||!body?.ok||!body?.data)return json({ok:false,code:'CLIENT_BOOTSTRAP_BACKEND_ERROR'},r.status>=500?503:r.status,setCookies);
  let enriched;try{enriched=await ensureCompanyDirectory(body.data,access,preview)}catch(error){console.error('RONA client company directory composition',error);return json({ok:false,code:'CLIENT_COMPANY_DIRECTORY_INCOMPLETE'},503,setCookies)}
  const notes=await notifications(access);
  return json({ok:true,data:safeBootstrap(enriched,notes,preview)},200,setCookies);
}
