const SUPABASE_URL='https://sxawrwzeobaqwwmlkzws.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_W2MxTx00ILiugSyZKp8uyQ_zBzcyorL';
const PORTAL_API=`${SUPABASE_URL}/functions/v1/rona-portal-api`;
const ACCESS_COOKIE='rona_portal_at';
const REFRESH_COOKIE='rona_portal_rt';
const SECURITY_HEADERS=Object.freeze({'cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache','referrer-policy':'no-referrer','x-content-type-options':'nosniff','x-frame-options':'DENY','permissions-policy':'camera=(), microphone=(), geolocation=(), payment=()','cross-origin-opener-policy':'same-origin','cross-origin-resource-policy':'same-origin'});
function parseCookies(header){const out={};for(const item of String(header||'').split(';')){const i=item.indexOf('=');if(i<1)continue;const k=item.slice(0,i).trim(),v=item.slice(i+1).trim();if(k)out[k]=v}return out}
function accessCookie(token,maxAge=3600){return `${ACCESS_COOKIE}=${token}; Max-Age=${Math.max(0,Number(maxAge)||0)}; Path=/portal; Secure; HttpOnly; SameSite=Lax`}
function refreshCookie(token,maxAge=604800){return `${REFRESH_COOKIE}=${token}; Max-Age=${Math.max(0,Number(maxAge)||0)}; Path=/portal; Secure; HttpOnly; SameSite=Lax`}
function clearCookies(){return[`${ACCESS_COOKIE}=; Max-Age=0; Path=/portal; Secure; HttpOnly; SameSite=Lax`,`${REFRESH_COOKIE}=; Max-Age=0; Path=/portal; Secure; HttpOnly; SameSite=Lax`]}
function tokenCookies(t){const e=Math.min(Math.max(Number(t?.expires_in||3600),60),7200);return[accessCookie(t.access_token,e),refreshCookie(t.refresh_token,604800)]}
function secureHeaders(){const h=new Headers({'content-type':'application/json; charset=utf-8'});for(const[k,v]of Object.entries(SECURITY_HEADERS))h.set(k,v);return h}
function json(body,status=200,cookies=[]){const h=secureHeaders();for(const c of cookies)h.append('set-cookie',c);return new Response(JSON.stringify(body),{status,headers:h})}
function sameOrigin(request){const u=new URL(request.url),origin=request.headers.get('origin');if(origin)return origin===u.origin;const ref=request.headers.get('referer');if(!ref)return request.method==='GET';try{return new URL(ref).origin===u.origin}catch{return false}}
async function authRefresh(refreshToken){const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,'content-type':'application/json'},body:JSON.stringify({refresh_token:refreshToken})});const data=await r.json().catch(()=>({}));return{ok:r.ok,status:r.status,data}}
async function upstream(access){return fetch(`${PORTAL_API}/v1/client/bootstrap`,{headers:{authorization:`Bearer ${access}`,accept:'application/json'},cache:'no-store'})}
async function notifications(access){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/portal_client_recent_event_results_v1`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,authorization:`Bearer ${access}`,'content-type':'application/json',accept:'application/json'},body:'{}'});if(!r.ok)return[];const body=await r.json().catch(()=>[]);return Array.isArray(body)?body:[]}
function safePriceAuthority(a){const publicationStatus=String(a?.publication_status??'').toUpperCase(),publicationAuthority=String(a?.publication_authority_state??'').toUpperCase(),publicationLifecycle=String(a?.publication_lifecycle_state??'').toUpperCase(),itemAuthority=String(a?.item_authority_state??'').toUpperCase(),itemLifecycle=String(a?.item_lifecycle_state??'').toUpperCase(),businessStatus=String(a?.business_status??'').toUpperCase();if(publicationStatus!=='PUBLISHED'||!['CONFIRMED','VERIFIED'].includes(publicationAuthority)||publicationLifecycle!=='ACTIVE'||!['CONFIRMED','VERIFIED'].includes(itemAuthority)||itemLifecycle!=='ACTIVE'||businessStatus!=='PUBLISHED'||a?.publish_client!==true)return null;return{publication_item_id:a?.publication_item_id??null,publication_id:a?.publication_id??null,publication_status:publicationStatus,publication_authority_state:publicationAuthority,publication_lifecycle_state:publicationLifecycle,item_authority_state:itemAuthority,item_lifecycle_state:itemLifecycle,product:a?.product??null,producer:a?.producer??null,supplier:a?.supplier??null,snapshot_basis:a?.snapshot_basis??null,final_station:a?.final_station??null,snapshot_price:a?.snapshot_price??null,snapshot_currency:a?.snapshot_currency??null,payment_terms:a?.payment_terms??null,commercial_terms:a?.commercial_terms??null,business_status:businessStatus,publish_client:true,client_published_at:a?.client_published_at??null,updated_at:a?.updated_at??null}}
function safeBootstrap(data,notes){const contexts=(Array.isArray(data?.contexts)?data.contexts:[]).map(c=>({client_id:c?.client_id??null,legal_name:c?.legal_name??null,registration_country:c?.registration_country??null,registered_address:c?.registered_address??null,contact_phone:c?.contact_phone??null,contract_id:c?.contract_id??null,current_external_contract_number:c?.current_external_contract_number??null,contract_status:c?.contract_status??null,effective_from:c?.effective_from??null,effective_to:c?.effective_to??null,verification_status:'CONFIRMED_CURRENT',verification_source:'AUTHORITATIVE_CONTRACT_ACCESS_GATE'}));const price_authority=(Array.isArray(data?.price_authority)?data.price_authority:[]).map(safePriceAuthority).filter(Boolean);return{generated_at:data?.generated_at??null,data_contract:data?.data_contract??null,requires_context_selection:Boolean(data?.requires_context_selection??contexts.length>1),contexts,price_authority,notifications:Array.isArray(notes)?notes:[]}}
export async function onRequest(context){
  const request=context.request;
  if(request.method!=='GET')return json({ok:false,code:'METHOD_NOT_ALLOWED'},405);
  if(!sameOrigin(request))return json({ok:false,code:'ORIGIN_DENIED'},403);
  const cookies=parseCookies(request.headers.get('cookie'));let access=cookies[ACCESS_COOKIE]||'',refresh=cookies[REFRESH_COOKIE]||'',setCookies=[];
  if(!access&&refresh){const next=await authRefresh(refresh);if(next.ok&&next.data?.access_token&&next.data?.refresh_token){access=next.data.access_token;setCookies=tokenCookies(next.data)}}
  if(!access)return json({ok:false,code:'PORTAL_ACCESS_DENIED'},401,clearCookies());
  let r=await upstream(access);
  if(r.status===401&&refresh){const next=await authRefresh(refresh);if(next.ok&&next.data?.access_token&&next.data?.refresh_token){access=next.data.access_token;setCookies=tokenCookies(next.data);r=await upstream(access)}}
  if(r.status===401)return json({ok:false,code:'PORTAL_ACCESS_DENIED'},401,clearCookies());
  const body=await r.json().catch(()=>null);
  if(!r.ok||!body?.ok||!body?.data)return json({ok:false,code:'CLIENT_BOOTSTRAP_BACKEND_ERROR'},r.status>=500?503:r.status,setCookies);
  const notes=await notifications(access);
  return json({ok:true,data:safeBootstrap(body.data,notes)},200,setCookies);
}
