const AGENT_RUNTIME = `<script id="rona-agent-production-actions">(()=>{'use strict';if(window.__RONA_AGENT_PRODUCTION_ACTIONS__)return;window.__RONA_AGENT_PRODUCTION_ACTIONS__=true;let sending=false;const toast=t=>{try{window.toast?.(t)}catch(_e){}};const prepare=()=>{let logout=document.getElementById('ronaLogout');if(!logout){logout=document.querySelector('.rona-go-home');if(logout){logout.id='ronaLogout';logout.textContent='Выйти';logout.dataset.ronaControlStatus='FUNCTIONAL';document.body.appendChild(logout)}}if(logout){logout.textContent='Выйти';logout.dataset.ronaControlStatus='FUNCTIONAL';Object.assign(logout.style,{position:'fixed',top:'18px',right:'20px',zIndex:'2147483000',display:'block',visibility:'visible',opacity:'1',width:'auto',height:'auto',pointerEvents:'auto',margin:'0'})}for(const b of document.querySelectorAll('#page-messages button')){if(String(b.textContent||'').trim()!=='Отправить')continue;b.removeAttribute('onclick');try{b.onclick=null}catch(_e){}b.dataset.ronaControlStatus='FUNCTIONAL'}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',prepare,{once:true});else queueMicrotask(prepare);new MutationObserver(prepare).observe(document.documentElement,{subtree:true,childList:true});document.addEventListener('click',async e=>{const logout=e.target?.closest?.('#ronaLogout');if(logout){e.preventDefault();e.stopImmediatePropagation();try{await fetch('/portal/auth/logout',{method:'POST',credentials:'same-origin',headers:{accept:'text/html'}})}catch(_e){}location.replace('/');return}const b=e.target?.closest?.('#page-messages button');if(!b||String(b.textContent||'').trim()!=='Отправить')return;e.preventDefault();e.stopImmediatePropagation();if(sending)return;const box=b.closest('#page-messages');const deal=String(box?.querySelector('select')?.value||'').trim();const subject=String(box?.querySelector('input')?.value||'').trim();const message=String(box?.querySelector('textarea')?.value||'').trim();if(!/^DEAL-\d{4}-\d{3,}$/.test(deal)||!subject||!message){toast('Заполните сделку, тему и сообщение.');return}sending=true;b.disabled=true;try{const r=await fetch('/portal/api/v1/events',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','accept':'application/json','x-idempotency-key':'agent-message-'+deal+'-'+crypto.randomUUID()},body:JSON.stringify({role:'AGENT',event_type:'AGENT_MESSAGE_SUBMIT',authority_domain:'COMMUNICATION',authority_target_type:'DEAL',authority_target_id:deal,deal_id:deal,payload:{subject,message}})});let j={};try{j=await r.json()}catch(_e){}if(!r.ok||!j.ok)throw new Error(j.code||('HTTP_'+r.status));const input=box?.querySelector('input'),area=box?.querySelector('textarea');if(input)input.value='';if(area)area.value='';toast('Сообщение зарегистрировано сервером.')}catch(err){toast('Ошибка сервера: '+String(err?.message||err))}finally{sending=false;b.disabled=false}},true)})();<\/script>`;

export async function onRequest(context){
  const response=await context.next();
  const type=String(response.headers.get('content-type')||'').toLowerCase();
  if(!type.includes('text/html'))return response;
  let html=await response.text();
  if(!html.includes('rona-agent-production-actions'))html=html.includes('</body>')?html.replace('</body>',AGENT_RUNTIME+'</body>'):html+AGENT_RUNTIME;
  const headers=new Headers(response.headers);headers.delete('content-length');headers.set('cache-control','no-store, no-cache, must-revalidate');
  return new Response(html,{status:response.status,statusText:response.statusText,headers});
}
