import test from 'node:test';
import assert from 'node:assert/strict';
import {
  buildAdminPaymentsV7Projection,
  createAdminPaymentsV7SourceBundle,
  buildOwnerPaymentDecision,
  canExecuteOwnerPaymentDecision,
  normalizeFinanceSourceRecordV1,
  normalizeFinanceSourceRecordV2,
} from '../../supabase/functions/rona-portal-api/admin-payments-v7/index.mjs';

const ref = (id) => ({ source_type: 'TEST', source_id: id, source_version: '1', source_timestamp: '2026-09-13T00:00:00Z', authority_state: 'AUTHORITATIVE', lifecycle_state: 'CURRENT' });
const mv = (amount, currency = 'USD') => ({ amount: String(amount), currency, status: 'AUTHORITATIVE', reason: null, authority_refs: [ref(`money-${amount}`)] });
function deal(key = 'deal-a', id = 'D-A') { return { deal_key: key, deal_id: id, client_display: `Client ${id}`, payment_handoff_state: 'READY', current: true, authority_state: 'AUTHORITATIVE', lifecycle_state: 'CURRENT', authority_refs: [ref(key)] }; }
function financeClaim({ id = 'fin-a', dealKey = 'deal-a', total = '100', due = '0', expected = '60', future = '0', currency = 'USD', supersedes = null, status = 'OPEN', documentary = 'CONFIRMED' } = {}) {
  return { id, deal_key: dealKey, total_to_receive: mv(total, currency), due_now: mv(due, currency), expected_not_due: mv(expected, currency), future_conditional: mv(future, currency), finance_status: status, documentary_status: documentary, contractual_payment_currency: currency, current: true, source_locked: true, authority_state: 'AUTHORITATIVE', lifecycle_state: 'CURRENT', effective_at: '2026-09-13T00:00:00Z', supersedes_id: supersedes, source_version: '1', authority_refs: [ref(id)] };
}
function payment({ key, id, direction = 'INCOMING', kind = 'CLIENT_PAYMENT', amount = '40', currency = 'USD', candidates = [], applicability } = {}) {
  return { payment_key: key, payment_id: id || key, payment_at: '2026-09-13T00:00:00Z', direction, kind, amount, currency, bank_fact_status: 'BANK_CONFIRMED', finance_verification_status: 'VERIFIED', allocation_applicability: applicability || (kind === 'FX_CONVERSION' ? 'NOT_APPLICABLE' : 'APPLICABLE'), candidate_deal_ids: candidates, current: true, source_locked: true, authority_state: 'AUTHORITATIVE', lifecycle_state: 'CURRENT', authority_refs: [ref(key)] };
}
function attribution({ id, paymentKey, lines = [], scope = [], classification = null, disposition = 'BIND_TO_DEAL', supersedes = null, supersedesRefs = [], principal = null } = {}) {
  return { id, payment_key: paymentKey, classification, disposition, lines, scope_deal_keys: scope, principal_payment_key: principal, current: true, source_locked: true, authority_state: 'AUTHORITATIVE', lifecycle_state: 'CURRENT', supersedes_id: supersedes, supersedes_authority_refs: supersedesRefs, authority_kind: 'OWNER', authority_refs: [ref(id)] };
}
function physical({ id, paymentKey, dealKey, amount, currency = 'USD', current = true } = {}) {
  return { id, payment_key: paymentKey, deal_key: dealKey, amount, currency, allocation_status: 'VERIFIED', current, source_locked: true, authority_state: current ? 'AUTHORITATIVE' : 'SUPERSEDED', lifecycle_state: current ? 'CURRENT' : 'SUPERSEDED', authority_refs: [ref(id)] };
}
function baseSource() {
  return { generatedAt: '2026-09-13T00:00:00Z', sourceAsOf: '2026-09-13T00:00:00Z', capabilities: { paymentBusinessAuthority: true, financeAuthority: true, resourceChain: true }, contour: [deal()], payments: [payment({ key: 'pay-in-1', amount: '40' })], attributionClaims: [attribution({ id: 'attr-in-1', paymentKey: 'pay-in-1', lines: [{ deal_key: 'deal-a', amount: '40', currency: 'USD', amount_status: 'EXACT' }] })], physicalAllocations: [physical({ id: 'mat-in-1', paymentKey: 'pay-in-1', dealKey: 'deal-a', amount: '40' })], financeAuthorities: [financeClaim()], resourceChains: [] };
}
function project(source) { return buildAdminPaymentsV7Projection(structuredClone(source)); }
function genuineRec() { return { payment_key: 'p', payment_id: 'p', reconciliation_class: 'GENUINELY_UNALLOCATED', status: 'AUTHORITATIVE', owner_action_required: true, allowed_owner_actions: ['BIND_TO_DEAL', 'ASSIGN_ADVANCE_PAYMENT'], current_authority_id: null }; }

test('A — Finance projection mutation is data-driven', () => {
  const a = project(baseSource()); const b = baseSource(); b.financeAuthorities[0] = financeClaim({ total: '120', expected: '80' }); const pb = project(b);
  assert.equal(a.deals[0].total_to_receive.amount, '100'); assert.equal(pb.deals[0].total_to_receive.amount, '120'); assert.equal(pb.deals[0].expected_not_due.amount, '80'); assert.equal(pb.deals[0].verified_received.amount, '40');
});
test('B — new Deal enters contour without code branch', () => { const s = baseSource(); s.contour.push(deal('deal-b', 'D-B')); s.financeAuthorities.push(financeClaim({ id: 'fin-b', dealKey: 'deal-b', total: '25', expected: '25' })); const o = project(s); assert.equal(o.deals.length, 2); assert.equal(o.deals[1].deal_id, 'D-B'); });
test('C — new verified client payment recomputes receipt and progress only', () => { const s = baseSource(); s.payments.push(payment({ key: 'pay-in-2', amount: '10' })); s.attributionClaims.push(attribution({ id: 'attr-in-2', paymentKey: 'pay-in-2', lines: [{ deal_key: 'deal-a', amount: '10', currency: 'USD' }] })); s.physicalAllocations.push(physical({ id: 'mat-in-2', paymentKey: 'pay-in-2', dealKey: 'deal-a', amount: '10' })); const o = project(s); assert.equal(o.deals[0].verified_received.amount, '50'); assert.equal(o.deals[0].remaining_to_receive.amount, '50'); assert.equal(o.deals[0].payment_progress.percent, '50'); assert.equal(o.deals[0].actual_spend.amount, '0'); });
test('D — Deal spend same currency and exact cross-currency chain; missing chain fails closed', () => {
  const s = baseSource();
  s.payments.push(payment({ key: 'pay-out-usd', direction: 'OUTGOING', kind: 'COUNTERPARTY_PAYMENT', amount: '10' })); s.attributionClaims.push(attribution({ id: 'attr-out-usd', paymentKey: 'pay-out-usd', lines: [{ deal_key: 'deal-a', amount: '10', currency: 'USD' }] }));
  s.payments.push(payment({ key: 'pay-out-rub', direction: 'OUTGOING', kind: 'COUNTERPARTY_PAYMENT', amount: '1000', currency: 'RUB' })); s.attributionClaims.push(attribution({ id: 'attr-out-rub', paymentKey: 'pay-out-rub', lines: [{ deal_key: 'deal-a', amount: '1000', currency: 'RUB' }] }));
  s.resourceChains.push({ id: 'chain-1', payment_key: 'pay-out-rub', deal_key: 'deal-a', native_amount: '1000', native_currency: 'RUB', accounting_amount: '12.5', accounting_currency: 'USD', current: true, source_locked: true, authority_state: 'AUTHORITATIVE', lifecycle_state: 'CURRENT', authority_refs: [ref('chain-1')] });
  const good = project(s); assert.equal(good.deals[0].actual_spend.amount, '22.5'); assert.equal(good.deals[0].actual_spend_status, 'AUTHORITATIVE'); s.resourceChains = []; const bad = project(s); assert.equal(bad.deals[0].actual_spend_status, 'PARTIAL_TO_VERIFY'); assert.equal(bad.deals[0].remaining_execution.status, 'TO_VERIFY');
});
test('E — genuine unresolved appears then disappears when scope authority arrives', () => { const s = baseSource(); const unresolved = payment({ key: 'pay-u', direction: 'OUTGOING', kind: 'COUNTERPARTY_PAYMENT', amount: '7' }); unresolved.allocation_review_status = 'UNALLOCATED'; s.payments.push(unresolved); let o = project(s); assert.equal(o.owner_exception_queue.length, 1); s.attributionClaims.push(attribution({ id: 'scope-u', paymentKey: 'pay-u', scope: ['deal-a'], classification: 'SHARED_DEAL_SCOPE_SPLIT_TO_VERIFY', disposition: null })); o = project(s); assert.equal(o.owner_exception_queue.length, 0); assert.equal(o.payment_exceptions.find((e) => e.payment_ids.includes('pay-u')).reconciliation_class, 'SHARED_DEAL_SCOPE_SPLIT_TO_VERIFY'); });
test('F — exact split without physical materialization is a technical gap, not Owner action', () => { const s = baseSource(); s.contour.push(deal('deal-b', 'D-B')); s.financeAuthorities.push(financeClaim({ id: 'fin-b', dealKey: 'deal-b', total: '10', expected: '10' })); s.payments.push(payment({ key: 'pay-split', direction: 'OUTGOING', kind: 'COUNTERPARTY_PAYMENT', amount: '20' })); s.attributionClaims.push(attribution({ id: 'attr-split', paymentKey: 'pay-split', lines: [{ deal_key: 'deal-a', amount: '12', currency: 'USD' }, { deal_key: 'deal-b', amount: '8', currency: 'USD' }] })); const o = project(s); const ex = o.payment_exceptions.find((e) => e.payment_ids.includes('pay-split')); assert.equal(ex.reconciliation_class, 'KNOWN_MULTI_DEAL_EXACT_SPLIT'); assert.equal(ex.owner_action_required, false); assert.equal(ex.technical_gap, 'NOT_MATERIALIZED'); });
test('G — Owner asserted allocated and shared associated fee remain non-queue gaps', () => { const s = baseSource(); s.payments.push(payment({ key: 'principal', direction: 'OUTGOING', kind: 'COUNTERPARTY_PAYMENT', amount: '50' })); s.attributionClaims.push(attribution({ id: 'asserted', paymentKey: 'principal', scope: ['deal-a'], classification: 'OWNER_ASSERTED_ALLOCATED_SYSTEM_AUTHORITY_NOT_MATERIALIZED', disposition: null })); s.payments.push(payment({ key: 'fee', direction: 'OUTGOING', kind: 'BANK_FEE', amount: '1' })); s.attributionClaims.push(attribution({ id: 'fee-attr', paymentKey: 'fee', scope: ['deal-a'], classification: 'ASSOCIATED_BANK_FEE', disposition: null, principal: 'principal' })); const o = project(s); assert.equal(o.owner_exception_queue.length, 0); assert.equal(o.payment_exceptions.find((e) => e.payment_ids.includes('principal')).reconciliation_class, 'OWNER_ASSERTED_ALLOCATED_SYSTEM_AUTHORITY_NOT_MATERIALIZED'); assert.equal(o.payment_exceptions.find((e) => e.payment_ids.includes('fee')).fee_attribution_state, 'SHARED_SCOPE'); });
test('H — FX conversion is normal non-applicable state, never receipt/spend/exception/Owner queue', () => { const s = baseSource(); s.payments.push(payment({ key: 'fx-1', direction: 'OUTGOING', kind: 'FX_CONVERSION', amount: '500', currency: 'RUB' })); const o = project(s); assert.equal(o.payment_exceptions.some((e) => e.payment_ids.includes('fx-1')), false); assert.equal(o.owner_exception_queue.length, 0); assert.equal(o.deals[0].verified_received.amount, '40'); assert.equal(o.deals[0].actual_spend.amount, '0'); });
test('I — mixed inbound currencies fail closed without explicit rule', () => { const s = baseSource(); s.payments.push(payment({ key: 'pay-eur', amount: '5', currency: 'EUR' })); s.attributionClaims.push(attribution({ id: 'attr-eur', paymentKey: 'pay-eur', lines: [{ deal_key: 'deal-a', amount: '5', currency: 'EUR' }] })); const o = project(s); assert.equal(o.deals[0].accounting_currency.status, 'TO_VERIFY'); assert.equal(o.deals[0].accounting_currency.reason, 'MIXED_INBOUND_CURRENCIES'); assert.equal(o.deals[0].financial_status, 'TO_VERIFY'); });
test('J — semantic baseline has zero generic unallocated for known/resolved/FX classes', () => { const s = baseSource(); s.payments.push(payment({ key: 'known', direction: 'OUTGOING', kind: 'COUNTERPARTY_PAYMENT', amount: '2' })); s.attributionClaims.push(attribution({ id: 'known-scope', paymentKey: 'known', scope: ['deal-a'], classification: 'SHARED_DEAL_SCOPE_SPLIT_TO_VERIFY', disposition: null })); s.payments.push(payment({ key: 'asserted-j', direction: 'OUTGOING', kind: 'COUNTERPARTY_PAYMENT', amount: '3' })); s.attributionClaims.push(attribution({ id: 'asserted-j-a', paymentKey: 'asserted-j', scope: ['deal-a'], classification: 'OWNER_ASSERTED_ALLOCATED_SYSTEM_AUTHORITY_NOT_MATERIALIZED', disposition: null })); s.payments.push(payment({ key: 'fx-j', direction: 'OUTGOING', kind: 'FX_CONVERSION', amount: '4', currency: 'RUB' })); const o = project(s); assert.equal(o.reconciliation_summary.genuinely_unallocated_count, 0); assert.equal(o.owner_exception_queue.length, 0); });
test('K — Owner BIND_TO_DEAL is human Owner/Admin only, server-guarded and append-only', () => {
  let n = 0; const p = payment({ key: 'p-k', direction: 'OUTGOING', kind: 'COUNTERPARTY_PAYMENT', amount: '10' }); const rec = { ...genuineRec(), payment_key: 'p-k', payment_id: 'p-k' };
  const result = buildOwnerPaymentDecision({ actor: { id: 'owner-1', role: 'OWNER', actor_type: 'HUMAN' }, payment: p, currentAuthority: null, currentReconciliation: rec, contourDeals: [deal()], action: 'BIND_TO_DEAL', payload: { expected_current_authority_id: null, lines: [{ deal_key: 'deal-a', amount: '10', currency: 'USD' }], idempotency_key: 'idem-k' }, idFactory: () => `id-${++n}`, now: '2026-09-13T01:00:00Z' });
  assert.equal(result.authority.supersedes_id, null); assert.equal(result.lines[0].amount, '10'); assert.equal(result.auditRecord.request_fingerprint, 'idem-k'); assert.equal(canExecuteOwnerPaymentDecision({ id: 'finance-ai', role: 'FINANCE', actor_type: 'AI', is_ai: true }), false);
});
test('L — ASSIGN_ADVANCE_PAYMENT remains outside client receipt and obligation arithmetic', () => {
  let n = 0; const p = payment({ key: 'advance-p', amount: '25', direction: 'OUTGOING', kind: 'COUNTERPARTY_PAYMENT' }); const rec = { ...genuineRec(), payment_key: 'advance-p', payment_id: 'advance-p' };
  const decision = buildOwnerPaymentDecision({ actor: { id: 'admin-1', role: 'ADMIN', actor_type: 'HUMAN' }, payment: p, currentReconciliation: rec, contourDeals: [deal()], action: 'ASSIGN_ADVANCE_PAYMENT', payload: { expected_current_authority_id: null, idempotency_key: 'idem-l' }, idFactory: () => `l-${++n}`, now: '2026-09-13T01:00:00Z' });
  const s = baseSource(); s.payments.push(p); s.attributionClaims.push({ ...decision.authority, disposition: decision.authority.decision_type, lines: [], scope_deal_keys: [], authority_refs: [ref('advance')] }); const o = project(s); assert.equal(o.owner_exception_queue.length, 0); assert.equal(o.payment_exceptions.some((e) => e.payment_ids.includes('advance-p')), false); assert.equal(o.deals[0].verified_received.amount, '40'); assert.equal(o.deals[0].total_to_receive.amount, '100'); assert.equal(o.deals[0].remaining_to_receive.amount, '60');
});
test('M — superseding Owner authority beats stale VERIFIED materialization', () => { const s = baseSource(); s.contour.push(deal('deal-b', 'D-B')); s.financeAuthorities.push(financeClaim({ id: 'fin-b', dealKey: 'deal-b', total: '40', expected: '0' })); s.attributionClaims = [attribution({ id: 'new-owner-auth', paymentKey: 'pay-in-1', lines: [{ deal_key: 'deal-b', amount: '40', currency: 'USD' }], supersedesRefs: [{ source_type: 'PAYMENT_ALLOCATION', source_id: 'stale-row' }] })]; s.physicalAllocations = [physical({ id: 'stale-row', paymentKey: 'pay-in-1', dealKey: 'deal-a', amount: '40', current: true })]; const o = project(s); assert.equal(o.deals.find((d) => d.deal_id === 'D-A').verified_received.amount, '0'); assert.equal(o.deals.find((d) => d.deal_id === 'D-B').verified_received.amount, '40'); assert.equal(o.payment_exceptions.find((e) => e.payment_ids.includes('pay-in-1')).technical_gap, 'STALE_SUPERSEDED_MATERIALIZATION'); });
test('N — Finance source schema versions normalize to one runtime contract without Deal branch', () => { const common = { record_id: 'f-n', deal_key: 'deal-a', current: true, source_locked: true, qa_only: false, authority_state: 'AUTHORITATIVE', lifecycle_state: 'CURRENT', version: 1, created_at: '2026-09-13T00:00:00Z' }; const v1 = normalizeFinanceSourceRecordV1({ ...common, payload: { total_to_receive: '100', due_now: '10', expected_not_due: '90', future_conditional: '0', contractual_payment_currency: 'USD', finance_status: 'OPEN', documentary_status: 'CONFIRMED' } }); const v2 = normalizeFinanceSourceRecordV2({ ...common, record_id: 'f-n2', payload: { obligation: { total: '100' }, buckets: { due_now: '10', expected_not_due: '90', future_conditional: '0' }, currency: { contractual: 'USD' }, finance_status: 'OPEN', documentary_status: 'CONFIRMED' } }); assert.deepEqual([v1.total_to_receive.amount, v1.due_now.amount, v1.expected_not_due.amount, v1.contractual_payment_currency], [v2.total_to_receive.amount, v2.due_now.amount, v2.expected_not_due.amount, v2.contractual_payment_currency]); });
test('O — over-receipt is explicit, negative remainder and >100% are preserved', () => { const s = baseSource(); s.payments[0].amount = '120'; s.attributionClaims[0].lines[0].amount = '120'; s.physicalAllocations[0].amount = '120'; const o = project(s); const d = o.deals[0]; assert.equal(d.remaining_to_receive.amount, '-20'); assert.equal(d.payment_progress.percent, '120'); assert.equal(d.financial_status, 'OVERRECEIVED'); assert.equal(d.financial_exceptions[0].amount.amount, '20'); assert.equal(o.owner_exception_queue.length, 0); });
test('P — incompatible current authorities fail closed as AUTHORITY_CONFLICT, never arbitrary Owner action', () => { const s = baseSource(); s.payments.push(payment({ key: 'p-conflict', direction: 'OUTGOING', kind: 'COUNTERPARTY_PAYMENT', amount: '9' })); s.attributionClaims.push(attribution({ id: 'conf-a', paymentKey: 'p-conflict', lines: [{ deal_key: 'deal-a', amount: '9', currency: 'USD' }] }), attribution({ id: 'conf-b', paymentKey: 'p-conflict', scope: ['deal-a'], classification: 'SHARED_DEAL_SCOPE_SPLIT_TO_VERIFY', disposition: null })); const o = project(s); const ex = o.payment_exceptions.find((e) => e.payment_ids.includes('p-conflict')); assert.equal(ex.reconciliation_class, 'AUTHORITY_CONFLICT'); assert.equal(ex.status, 'TO_VERIFY'); assert.equal(ex.owner_action_required, false); assert.equal(o.owner_exception_queue.length, 0); });
test('Q — stale materialized incoming allocation is not double-counted after supersession', () => { const s = baseSource(); s.attributionClaims = [attribution({ id: 'old-q', paymentKey: 'pay-in-1', lines: [{ deal_key: 'deal-a', amount: '40', currency: 'USD' }] }), attribution({ id: 'new-q', paymentKey: 'pay-in-1', lines: [{ deal_key: 'deal-a', amount: '40.0000', currency: 'USD' }], supersedes: 'old-q' })]; s.physicalAllocations = [physical({ id: 'raw-old', paymentKey: 'pay-in-1', dealKey: 'deal-a', amount: '40', current: false }), physical({ id: 'raw-new', paymentKey: 'pay-in-1', dealKey: 'deal-a', amount: '40.0', current: true })]; const o = project(s); assert.equal(o.deals[0].verified_received.amount, '40'); });

test('R — RAW ADAPTER SUPERSESSION: physical materialization cannot conflict with later Owner authority', () => {
  const raw = {
    generatedAt: '2026-09-13T00:00:00Z', sourceAsOf: '2026-09-13T00:00:00Z',
    deals: [
      { id: 'deal-a', deal_id: 'D-A', client_key: 'client-a', contract_key: 'ctr-a', business_status: 'EXECUTING', authority_state: 'CONFIRMED', lifecycle_state: 'ACTIVE' },
      { id: 'deal-b', deal_id: 'D-B', client_key: 'client-b', contract_key: 'ctr-b', business_status: 'EXECUTING', authority_state: 'CONFIRMED', lifecycle_state: 'ACTIVE' },
    ],
    workflows: [{ deal_key: 'deal-a', payment_handoff_state: 'READY', cancellation_state: 'ACTIVE' }, { deal_key: 'deal-b', payment_handoff_state: 'READY', cancellation_state: 'ACTIVE' }],
    clients: [{ id: 'client-a', legal_name: 'A' }, { id: 'client-b', legal_name: 'B' }], contracts: [{ id: 'ctr-a', contract_id: 'C-A' }, { id: 'ctr-b', contract_id: 'C-B' }],
    payments: [{ id: 'pay-raw', payment_id: 'P-RAW', payment_at: '2026-09-13T00:00:00Z', payment_direction: 'INCOMING', payment_kind: 'CLIENT_PAYMENT', amount: '40.0000', currency: 'USD', bank_fact_status: 'BANK_CONFIRMED', finance_verification_status: 'VERIFIED', deal_allocation_applicability: 'DEAL_ALLOCATABLE', allocation_review_status: 'VERIFIED', candidate_deal_ids: [], authority_state: 'CONFIRMED', lifecycle_state: 'ACTIVE' }],
    paymentAllocations: [{ id: 'alloc-old', payment_key: 'pay-raw', deal_key: 'deal-a', allocated_amount: '40.0', allocation_status: 'VERIFIED', finance_status: 'PAID', authority_state: 'CONFIRMED', lifecycle_state: 'ACTIVE' }], paymentAllocationHistory: [],
    paymentBusinessAttributions: [{ id: 'owner-new', payment_key: 'pay-raw', classification: 'RESOLVED', decision_type: 'BIND_TO_DEAL', authority_kind: 'OWNER', scope_deal_keys: ['deal-b'], authority_state: 'AUTHORITATIVE', lifecycle_state: 'CURRENT', effective_at: '2026-09-13T01:00:00Z', source_locked: true, supersedes_authority_refs: [{ source_type: 'PAYMENT_ALLOCATION', source_id: 'alloc-old' }] }],
    paymentBusinessAttributionLines: [{ attribution_id: 'owner-new', deal_key: 'deal-b', amount: '40', currency: 'USD', amount_status: 'EXACT' }],
    dealFinanceAuthorities: [
      { id: 'f-a', deal_key: 'deal-a', total_to_receive: '100', due_now: '0', expected_not_due: '100', future_conditional: '0', obligation_currency: 'USD', contractual_payment_currency: 'USD', finance_status: 'OPEN', documentary_status: 'CONFIRMED', authority_state: 'AUTHORITATIVE', lifecycle_state: 'CURRENT', effective_at: '2026-09-13T00:00:00Z', source_locked: true },
      { id: 'f-b', deal_key: 'deal-b', total_to_receive: '40', due_now: '0', expected_not_due: '0', future_conditional: '0', obligation_currency: 'USD', contractual_payment_currency: 'USD', finance_status: 'OPEN', documentary_status: 'CONFIRMED', authority_state: 'AUTHORITATIVE', lifecycle_state: 'CURRENT', effective_at: '2026-09-13T00:00:00Z', source_locked: true },
    ], resourceChains: [], ownerOutgoingPaymentFacts: [],
  };
  const bundle = createAdminPaymentsV7SourceBundle(raw); assert.equal(bundle.attributionClaims.some((c) => String(c.id).startsWith('MATERIALIZED:')), false);
  const o = buildAdminPaymentsV7Projection(bundle); assert.equal(o.deals.find((d) => d.deal_id === 'D-A').verified_received.amount, '0'); assert.equal(o.deals.find((d) => d.deal_id === 'D-B').verified_received.amount, '40'); const ex = o.payment_exceptions.find((e) => e.payment_ids.includes('P-RAW')); assert.equal(ex.reconciliation_class, 'RESOLVED'); assert.equal(ex.technical_gap, 'STALE_SUPERSEDED_MATERIALIZATION'); assert.equal(o.reconciliation_summary.authority_conflict_count, 0);
});
test('S — INVALID OUTGOING EXACT COVERAGE fails closed before spend', () => { const s = baseSource(); s.payments.push(payment({ key: 'out-100', direction: 'OUTGOING', kind: 'COUNTERPARTY_PAYMENT', amount: '100' })); s.attributionClaims.push(attribution({ id: 'bad-60', paymentKey: 'out-100', lines: [{ deal_key: 'deal-a', amount: '60', currency: 'USD' }] })); const o = project(s); const ex = o.payment_exceptions.find((e) => e.payment_ids.includes('out-100')); assert.equal(ex.reconciliation_class, 'ATTRIBUTION_INTEGRITY_ERROR'); assert.equal(ex.integrity_reason, 'ATTRIBUTION_AMOUNT_COVERAGE_MISMATCH'); assert.notEqual(o.deals[0].actual_spend_status, 'AUTHORITATIVE'); });
test('T — OWNER ACTION GUARDS reject bypass of reconciliation, contour, idempotency and optimistic lock', () => {
  const actor = { id: 'owner', role: 'OWNER', actor_type: 'HUMAN' }; const contour = [deal()]; const rec = { ...genuineRec(), payment_key: 'p', payment_id: 'p' }; const basePayment = payment({ key: 'p', direction: 'OUTGOING', kind: 'COUNTERPARTY_PAYMENT', amount: '10' });
  const bind = (overrides = {}) => buildOwnerPaymentDecision({ actor, payment: overrides.payment || basePayment, currentAuthority: overrides.currentAuthority || null, currentReconciliation: overrides.rec || rec, contourDeals: overrides.contour || contour, action: overrides.action || 'BIND_TO_DEAL', payload: overrides.payload || { expected_current_authority_id: null, idempotency_key: 'idem', lines: [{ deal_key: 'deal-a', amount: '10', currency: 'USD' }] }, idFactory: () => 'id', now: '2026-09-13T00:00:00Z' });
  assert.throws(() => bind({ payment: payment({ key: 'p', direction: 'OUTGOING', kind: 'FX_CONVERSION', amount: '10' }) }), /NOT_ACTIONABLE/);
  assert.throws(() => bind({ rec: { ...rec, reconciliation_class: 'RESOLVED', owner_action_required: false, allowed_owner_actions: [] } }), /RECONCILIATION_NOT_ACTIONABLE/);
  assert.throws(() => bind({ rec: { ...rec, reconciliation_class: 'SHARED_DEAL_SCOPE_SPLIT_TO_VERIFY', status: 'TO_VERIFY', owner_action_required: false, allowed_owner_actions: [] } }), /RECONCILIATION_NOT_ACTIONABLE/);
  assert.throws(() => bind({ contour: [], payload: { expected_current_authority_id: null, idempotency_key: 'idem', lines: [{ deal_key: 'deal-a', amount: '10', currency: 'USD' }] } }), /BIND_TARGET_DEAL_NOT_IN_PAYMENTS_CONTOUR|ATTRIBUTION_DEAL_KEY_INVALID/);
  assert.throws(() => bind({ payload: { expected_current_authority_id: null, lines: [{ deal_key: 'deal-a', amount: '10', currency: 'USD' }] } }), /IDEMPOTENCY_KEY_REQUIRED/);
  assert.throws(() => bind({ payload: { idempotency_key: 'idem', lines: [{ deal_key: 'deal-a', amount: '10', currency: 'USD' }] } }), /EXPECTED_CURRENT_AUTHORITY_ID_REQUIRED/);
  assert.throws(() => bind({ currentAuthority: { id: 'old' }, payload: { expected_current_authority_id: null, idempotency_key: 'idem', lines: [{ deal_key: 'deal-a', amount: '10', currency: 'USD' }] } }), /STALE_OWNER_DECISION/);
});
test('V — EXCEPTION SEMANTICS: FX, aligned exact split and assigned advance are normal states', () => {
  const s = baseSource(); s.contour.push(deal('deal-b', 'D-B')); s.financeAuthorities.push(financeClaim({ id: 'fin-b', dealKey: 'deal-b', total: '10', expected: '10' }));
  s.payments.push(payment({ key: 'fx-v', direction: 'OUTGOING', kind: 'FX_CONVERSION', amount: '5', currency: 'RUB' }));
  s.payments.push(payment({ key: 'split-v', direction: 'OUTGOING', kind: 'COUNTERPARTY_PAYMENT', amount: '20' })); s.attributionClaims.push(attribution({ id: 'split-v-a', paymentKey: 'split-v', lines: [{ deal_key: 'deal-a', amount: '12.0', currency: 'USD' }, { deal_key: 'deal-b', amount: '8.000', currency: 'USD' }] })); s.physicalAllocations.push(physical({ id: 'split-v-m1', paymentKey: 'split-v', dealKey: 'deal-a', amount: '12' }), physical({ id: 'split-v-m2', paymentKey: 'split-v', dealKey: 'deal-b', amount: '8.0' }));
  s.payments.push(payment({ key: 'adv-v', direction: 'OUTGOING', kind: 'COUNTERPARTY_PAYMENT', amount: '7' })); s.attributionClaims.push(attribution({ id: 'adv-v-a', paymentKey: 'adv-v', classification: 'RESOLVED', disposition: 'ASSIGN_ADVANCE_PAYMENT', lines: [] }));
  const o = project(s); for (const id of ['fx-v', 'split-v', 'adv-v']) assert.equal(o.payment_exceptions.some((e) => e.payment_ids.includes(id)), false); assert.equal(o.owner_exception_queue.length, 0);
});
test('W — DECIMAL CANONICALIZATION prevents scale-only conflict/stale mismatch', () => { const s = baseSource(); s.attributionClaims = [attribution({ id: 'w1', paymentKey: 'pay-in-1', lines: [{ deal_key: 'deal-a', amount: '40.0', currency: 'USD' }] }), attribution({ id: 'w2', paymentKey: 'pay-in-1', lines: [{ deal_key: 'deal-a', amount: '40.0000', currency: 'USD' }] })]; s.physicalAllocations = [physical({ id: 'wm', paymentKey: 'pay-in-1', dealKey: 'deal-a', amount: '40.000' })]; const o = project(s); assert.equal(o.deals[0].verified_received.amount, '40'); assert.equal(o.reconciliation_summary.authority_conflict_count, 0); assert.equal(o.payment_exceptions.some((e) => e.payment_ids.includes('pay-in-1')), false); });
test('X — ASSOCIATED FEE exact is spend-eligible; shared scope is TO_VERIFY with no inferred split', () => {
  const exact = baseSource(); exact.payments.push(payment({ key: 'fee-x', direction: 'OUTGOING', kind: 'BANK_FEE', amount: '2' })); exact.attributionClaims.push(attribution({ id: 'fee-x-a', paymentKey: 'fee-x', classification: 'ASSOCIATED_BANK_FEE', principal: 'principal-x', lines: [{ deal_key: 'deal-a', amount: '2', currency: 'USD' }] })); exact.physicalAllocations.push(physical({ id: 'fee-x-m', paymentKey: 'fee-x', dealKey: 'deal-a', amount: '2' })); let o = project(exact); assert.equal(o.deals[0].actual_spend_status, 'AUTHORITATIVE'); assert.equal(o.deals[0].actual_spend.amount, '2'); assert.equal(o.payment_exceptions.some((e) => e.payment_ids.includes('fee-x')), false);
  const shared = structuredClone(exact); shared.payments.push(payment({ key: 'fee-shared', direction: 'OUTGOING', kind: 'BANK_FEE', amount: '3' })); shared.attributionClaims.push(attribution({ id: 'fee-shared-a', paymentKey: 'fee-shared', classification: 'ASSOCIATED_BANK_FEE', principal: 'principal-x', scope: ['deal-a'], lines: [], disposition: null })); o = project(shared); const ex = o.payment_exceptions.find((e) => e.payment_ids.includes('fee-shared')); assert.equal(ex.fee_attribution_state, 'SHARED_SCOPE'); assert.equal(ex.status, 'TO_VERIFY'); assert.equal(o.deals[0].actual_spend_status, 'PARTIAL_TO_VERIFY'); assert.equal(o.deals[0].actual_spend.amount, '2');
});
