\set ON_ERROR_STOP on
DROP SCHEMA IF EXISTS portal_private CASCADE;
DROP SCHEMA IF EXISTS supabase_migrations CASCADE;
CREATE SCHEMA portal_private;
CREATE SCHEMA supabase_migrations;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN CREATE ROLE anon NOLOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN CREATE ROLE authenticated NOLOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='service_role') THEN CREATE ROLE service_role NOLOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='rona_payments_v7_reader') THEN CREATE ROLE rona_payments_v7_reader NOLOGIN NOINHERIT; END IF;
END $$;
CREATE TABLE supabase_migrations.schema_migrations(version text PRIMARY KEY,statements text[] NOT NULL DEFAULT '{}',name text);
INSERT INTO supabase_migrations.schema_migrations(version,name) VALUES
('20260913160703','admin_payments_v7_stage3a_authority_core'),('20260913160742','admin_payments_v7_stage3a_validation_function'),('20260913160902','admin_payments_v7_stage3a_immutability'),('20260913160927','admin_payments_v7_stage3a_owner_audit'),('20260913161026','admin_payments_v7_stage3a_finance_authority'),('20260913161057','admin_payments_v7_stage3d_shape'),('20260913161140','admin_payments_v7_stage3d_reader_role'),('20260913161204','admin_payments_v7_stage3d_revoke_attribution'),('20260913161257','admin_payments_v7_stage3d1_provider_readiness'),('20260913161623','admin_payments_v7_stage4a_seed_fee_000009'),('20260913161909','admin_payments_v7_stage4a_function_search_path_hardening');
CREATE TABLE portal_private.deals(id uuid PRIMARY KEY);
CREATE TABLE portal_private.payments(id uuid PRIMARY KEY,amount numeric(24,8) NOT NULL,currency char(3) NOT NULL);
CREATE TABLE portal_private.payment_allocations(id uuid PRIMARY KEY,payment_key uuid);
CREATE FUNCTION portal_private.admin_payments_v7_valid_currency(value text) RETURNS boolean LANGUAGE sql IMMUTABLE AS $$SELECT value IS NOT NULL AND btrim(value)~'^[A-Z]{3}$'$$;
ALTER FUNCTION portal_private.admin_payments_v7_valid_currency(text) SET search_path=pg_catalog,portal_private;
CREATE TABLE portal_private.payment_business_attributions_v7(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),payment_key uuid NOT NULL REFERENCES portal_private.payments(id),classification text NOT NULL,
 attribution_mode text NOT NULL CHECK(attribution_mode IN('EXACT','SCOPE_ONLY','NO_DEAL_BINDING')),decision_type text NULL CHECK(decision_type IS NULL OR decision_type IN('BIND_TO_DEAL','ASSIGN_ADVANCE_PAYMENT')),
 authority_kind text NOT NULL,authority_source_ref text NULL,business_scope_refs text[] NOT NULL DEFAULT '{}',scope_deal_keys uuid[] NOT NULL DEFAULT '{}',
 lines_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(lines_snapshot)='array'),principal_payment_key uuid NULL REFERENCES portal_private.payments(id),
 materialization_status text NOT NULL DEFAULT 'NOT_MATERIALIZED',authority_state text NOT NULL DEFAULT 'AUTHORITATIVE',lifecycle_state text NOT NULL DEFAULT 'CURRENT',effective_at timestamptz NOT NULL,
 supersedes_id uuid NULL REFERENCES portal_private.payment_business_attributions_v7(id),supersedes_authority_refs jsonb NOT NULL DEFAULT '[]'::jsonb,source_version text NULL,source_timestamp timestamptz NULL,
 source_refs jsonb NOT NULL DEFAULT '[]'::jsonb,source_locked boolean NOT NULL DEFAULT true CHECK(source_locked),actor_id text NULL,actor_role text NULL,idempotency_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(payment_key,idempotency_key),CHECK((attribution_mode='EXACT' AND jsonb_array_length(lines_snapshot)>0 AND cardinality(scope_deal_keys)>0) OR (attribution_mode='SCOPE_ONLY' AND jsonb_array_length(lines_snapshot)=0 AND (cardinality(scope_deal_keys)>0 OR cardinality(business_scope_refs)>0 OR principal_payment_key IS NOT NULL)) OR (attribution_mode='NO_DEAL_BINDING' AND jsonb_array_length(lines_snapshot)=0 AND cardinality(scope_deal_keys)=0)),
 CHECK(principal_payment_key IS NULL OR principal_payment_key<>payment_key),CHECK(CASE WHEN decision_type='BIND_TO_DEAL' THEN attribution_mode='EXACT' AND classification IN('RESOLVED','KNOWN_MULTI_DEAL_EXACT_SPLIT') WHEN decision_type='ASSIGN_ADVANCE_PAYMENT' THEN attribution_mode='NO_DEAL_BINDING' AND classification='RONA_ADVANCE_DEAL_SPEND' WHEN decision_type IS NULL THEN attribution_mode='EXACT' OR(attribution_mode='SCOPE_ONLY' AND classification IN('SHARED_DEAL_SCOPE_SPLIT_TO_VERIFY','ASSOCIATED_BANK_FEE','OWNER_ASSERTED_ALLOCATED_SYSTEM_AUTHORITY_NOT_MATERIALIZED')) ELSE false END));
CREATE FUNCTION portal_private.validate_payment_business_attribution_v7() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE pa numeric; pc text; lc int; ls numeric;
BEGIN SELECT amount,upper(btrim(currency::text)) INTO pa,pc FROM portal_private.payments WHERE id=new.payment_key; IF NOT FOUND OR pa IS NULL OR pa<=0 THEN RAISE EXCEPTION 'PAYMENT_AUTHORITY_PAYMENT_INVALID'; END IF;
 IF new.attribution_mode='EXACT' THEN SELECT count(*),coalesce(sum((x->>'amount')::numeric),0) INTO lc,ls FROM jsonb_array_elements(new.lines_snapshot)x; IF lc=0 OR ls<>pa OR EXISTS(SELECT 1 FROM jsonb_array_elements(new.lines_snapshot)x WHERE upper(btrim(x->>'currency'))<>pc OR(x->>'amount')::numeric<=0 OR NOT EXISTS(SELECT 1 FROM portal_private.deals d WHERE d.id=(x->>'deal_key')::uuid)) THEN RAISE EXCEPTION 'PAYMENT_AUTHORITY_EXACT_INVALID'; END IF; END IF; RETURN new; END $$;
ALTER FUNCTION portal_private.validate_payment_business_attribution_v7() SET search_path=pg_catalog,portal_private;
CREATE FUNCTION portal_private.reject_v7_authority_mutation() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'V7 authority records are immutable; append a superseding authority instead'; END$$;
ALTER FUNCTION portal_private.reject_v7_authority_mutation() SET search_path=pg_catalog,portal_private;
CREATE TRIGGER payment_business_attributions_v7_validate BEFORE INSERT ON portal_private.payment_business_attributions_v7 FOR EACH ROW EXECUTE FUNCTION portal_private.validate_payment_business_attribution_v7();
CREATE TRIGGER payment_business_attributions_v7_immutable BEFORE UPDATE OR DELETE ON portal_private.payment_business_attributions_v7 FOR EACH ROW EXECUTE FUNCTION portal_private.reject_v7_authority_mutation();
CREATE VIEW portal_private.payment_business_attribution_lines_v7 AS SELECT(a.id::text||':'||line.ordinality::text)id,a.id attribution_id,(line.item->>'deal_key')::uuid deal_key,(line.item->>'amount')::numeric amount,upper(btrim(line.item->>'currency'))::char(3) currency,'EXACT'::text amount_status,coalesce(line.item->'source_refs',a.source_refs,'[]'::jsonb)source_refs,a.created_at FROM portal_private.payment_business_attributions_v7 a CROSS JOIN LATERAL jsonb_array_elements(a.lines_snapshot) WITH ORDINALITY line(item,ordinality) WHERE a.attribution_mode='EXACT';
CREATE TABLE portal_private.owner_payment_decision_audit_v7(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),payment_key uuid NOT NULL REFERENCES portal_private.payments(id),resulting_authority_id uuid NOT NULL REFERENCES portal_private.payment_business_attributions_v7(id),event_type text NOT NULL CHECK(event_type='OWNER_PAYMENT_DECISION'),action text NOT NULL CHECK(action IN('BIND_TO_DEAL','ASSIGN_ADVANCE_PAYMENT')),actor_id text NOT NULL,actor_role text NOT NULL CHECK(actor_role IN('OWNER','ADMIN')),expected_current_authority_id uuid NULL,expected_current_authority_ref jsonb NULL,effective_at timestamptz NOT NULL,idempotency_key text NOT NULL,request_fingerprint text NOT NULL,request_snapshot jsonb NOT NULL CHECK(jsonb_typeof(request_snapshot)='object'),previous_authority_snapshot jsonb NULL,current_reconciliation_snapshot jsonb NULL,resulting_authority_snapshot jsonb NOT NULL CHECK(jsonb_typeof(resulting_authority_snapshot)='object'),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(payment_key,idempotency_key),UNIQUE(resulting_authority_id));
CREATE TRIGGER owner_payment_decision_audit_v7_immutable BEFORE UPDATE OR DELETE ON portal_private.owner_payment_decision_audit_v7 FOR EACH ROW EXECUTE FUNCTION portal_private.reject_v7_authority_mutation();
CREATE TABLE portal_private.deal_finance_authority_v7(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),deal_key uuid NOT NULL REFERENCES portal_private.deals(id),total_to_receive numeric(24,8) NOT NULL,due_now numeric(24,8) NOT NULL,expected_not_due numeric(24,8) NOT NULL,future_conditional numeric(24,8) NOT NULL,obligation_currency char(3) NOT NULL,contractual_payment_currency char(3),mixed_inbound_accounting_currency char(3),finance_status text NOT NULL,documentary_status text NOT NULL,authority_state text NOT NULL DEFAULT'AUTHORITATIVE',lifecycle_state text NOT NULL DEFAULT'CURRENT',effective_at timestamptz NOT NULL,supersedes_id uuid NULL REFERENCES portal_private.deal_finance_authority_v7(id),supersedes_authority_refs jsonb NOT NULL DEFAULT'[]',source_version text,source_timestamp timestamptz,source_refs jsonb NOT NULL DEFAULT'[]',source_locked boolean NOT NULL DEFAULT true CHECK(source_locked),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE portal_private.admin_payments_v7_provider_readiness(provider_key text PRIMARY KEY,is_ready boolean NOT NULL DEFAULT false,ready_at timestamptz,validation_ref text,updated_at timestamptz NOT NULL DEFAULT now());
GRANT USAGE ON SCHEMA portal_private TO rona_payments_v7_reader; GRANT SELECT ON portal_private.payment_business_attributions_v7,portal_private.payment_business_attribution_lines_v7,portal_private.deal_finance_authority_v7,portal_private.admin_payments_v7_provider_readiness TO rona_payments_v7_reader;
REVOKE ALL ON portal_private.payment_business_attributions_v7 FROM public,anon,authenticated,service_role; REVOKE ALL ON portal_private.admin_payments_v7_provider_readiness FROM public,anon,authenticated,service_role;
INSERT INTO portal_private.deals(id) VALUES('10000000-0000-4000-8000-000000000001'),('10000000-0000-4000-8000-000000000002'),('10000000-0000-4000-8000-000000000003'),('10000000-0000-4000-8000-000000000004');
INSERT INTO portal_private.payments(id,amount,currency) VALUES('20000000-0000-4000-8000-000000000001',25,'USD'),('20000000-0000-4000-8000-000000000002',3,'USD'),('20000000-0000-4000-8000-000000000003',50,'USD');
INSERT INTO portal_private.payment_allocations(id,payment_key) VALUES('30000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001');
INSERT INTO portal_private.payment_business_attributions_v7(id,payment_key,classification,attribution_mode,authority_kind,business_scope_refs,scope_deal_keys,lines_snapshot,effective_at,source_locked,idempotency_key) VALUES
('40000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001','OWNER_ASSERTED_ALLOCATED_SYSTEM_AUTHORITY_NOT_MATERIALIZED','SCOPE_ONLY','OWNER_SOURCE_RECORD',ARRAY['SYNTHETIC:BASE:1'],ARRAY['10000000-0000-4000-8000-000000000001'::uuid],'[]',now(),true,'fixture-attribution-1'),
('40000000-0000-4000-8000-000000000002','20000000-0000-4000-8000-000000000002','ASSOCIATED_BANK_FEE','SCOPE_ONLY','OWNER_SOURCE_RECORD',ARRAY['SYNTHETIC:BASE:2'],ARRAY['10000000-0000-4000-8000-000000000001'::uuid],'[]',now(),true,'fixture-attribution-2');
INSERT INTO portal_private.deal_finance_authority_v7(deal_key,total_to_receive,due_now,expected_not_due,future_conditional,obligation_currency,contractual_payment_currency,finance_status,documentary_status,effective_at,source_locked) SELECT id,100,0,100,0,'USD','USD','NOT_DUE','VERIFIED',now(),true FROM portal_private.deals;
INSERT INTO portal_private.admin_payments_v7_provider_readiness(provider_key,is_ready,ready_at,validation_ref) VALUES('PAYMENT_BUSINESS_AUTHORITY',true,now(),'STAGE4B_FIXTURE');
