import { onRequest as serveCurrentAdminUi } from '../admin-main-ui-current.js';
import applicationPassportRuntime from './application-passport-runtime.js';
import adminVisualRedesign from './admin-visual-redesign-v1.js';
import adminVisualStatusChips from './admin-visual-status-chips-v1.js';
import adminVisualPolish from './admin-visual-polish-v1.js';
import adminVisualRevisionV2 from './admin-visual-revision-v2.js';

// Issue #442: keep finalized source applications visible through the existing Completed projection.
const BUCKET_FROM="function application2BBucket(a){const owner=String(a?.owner_status||'').toUpperCase(),app=String(a?.status||'').toUpperCase(),deal=String(a?.deal_status||'').toUpperCase();if(owner==='REJECTED'||owner==='CANCELLED'||owner==='SUPPLIER_APPROVED'||owner==='DEAL'||app==='CANCELLED'||(app==='DEAL_REGISTERED'&&deal!=='SUPPLIER_PENDING'))return'COMPLETED';if(owner==='COUNTER_OFFERED'||owner==='SUPPLIER_PENDING'||deal==='SUPPLIER_PENDING')return'DECISION';if(owner==='NEW'||!owner)return'NEW';return'WORK'}";
const BUCKET_TO="function application2BBucket(a){const owner=String(a?.owner_status||'').toUpperCase(),app=String(a?.status||'').toUpperCase(),deal=String(a?.deal_status||'').toUpperCase();if(owner==='REJECTED'||owner==='CANCELLED'||owner==='DEAL'||app==='CANCELLED'||(app==='DEAL_REGISTERED'&&deal!=='SUPPLIER_PENDING'))return'COMPLETED';if(owner==='COUNTER_OFFERED'||owner==='SUPPLIER_PENDING'||deal==='SUPPLIER_PENDING')return'DECISION';if(owner==='NEW'||!owner)return'NEW';return'WORK'}";
const ACTIONS_FROM="function application2BActions(a){const bucket=application2BBucket(a),owner=String(a?.owner_status||'').toUpperCase(),deal=String(a?.deal_status||'').toUpperCase();if(bucket==='DECISION'&&(owner==='SUPPLIER_PENDING'||deal==='SUPPLIER_PENDING')){const box=e('div',{class:'rona-owner-actions rona-app-actions'});const run=async(action,body={})=>{try{await post('/admin/applications/'+encodeURIComponent(a.application_id)+'/'+action,body);await refreshAdmin()}catch(err){await notify(err.code||err.message,'Ошибка')}};box.append(e('button',{text:'Ресурс одобрен',onclick:()=>run('supplier-approved')}),e('button',{text:'В ресурсе отказано',onclick:()=>run('cancel',{reason:'SUPPLIER_RESOURCE_DENIED'})}));return box}if(bucket==='COMPLETED')return e('span',{class:'rona-owner-muted',text:'—'});return applicationActions(a)}";
const ACTIONS_TO="function application2BActions(a){const bucket=application2BBucket(a),owner=String(a?.owner_status||'').toUpperCase(),deal=String(a?.deal_status||'').toUpperCase();const run=async(action,body={})=>{try{await post('/admin/applications/'+encodeURIComponent(a.application_id)+'/'+action,body);await refreshAdmin()}catch(err){await notify(err.code||err.message,'Ошибка')}};if(owner==='SUPPLIER_APPROVED'&&!a?.deal_id){const box=e('div',{class:'rona-owner-actions rona-app-actions'});box.append(e('button',{text:'Отправить в сделки',onclick:()=>run('accept')}));return box}if(bucket==='DECISION'&&(owner==='SUPPLIER_PENDING'||deal==='SUPPLIER_PENDING')){const box=e('div',{class:'rona-owner-actions rona-app-actions'});box.append(e('button',{text:'Ресурс одобрен',onclick:()=>run('supplier-approved')}),e('button',{text:'В ресурсе отказано',onclick:()=>run('cancel',{reason:'SUPPLIER_RESOURCE_DENIED'})}));return box}if(bucket==='COMPLETED')return e('button',{type:'button','data-rona-app-passport-open':String(a?.application_id||''),text:'Открыть'});return applicationActions(a)}";
const ADMIN_BOOTSTRAP_FROM="async function call(path,options={}){const init={credentials:'same-origin',cache:'no-store',headers:{accept:'application/json'},...options};const r=await fetch(`${API}?path=${encodeURIComponent(path)}`,init);const ct=String(r.headers.get('content-type')||'');if(ct.includes('application/pdf'))return r;const j=await r.json().catch(()=>({}));if(!r.ok||j?.ok===false){const err=new Error(String(j?.code||`HTTP_${r.status}`));err.code=String(j?.code||'REQUEST_FAILED');err.status=r.status;throw err}const data=j.data;if(path==='/admin/bootstrap'&&Array.isArray(data?.rail)){data.rail=data.rail.map(x=>({...x,gu12_number:x.gu12_number??x.gu12Number??x.document_number??x.documentNumber??x.rail_document_id??x.railDocumentId,document_number:x.document_number??x.documentNumber,rail_document_id:x.rail_document_id??x.railDocumentId,deal_id:x.deal_id??x.dealId,route_text:x.route_text??x.routeText}))}return data}";
const ADMIN_BOOTSTRAP_TO="async function call(path,options={}){const init={credentials:'same-origin',cache:'no-store',headers:{accept:'application/json'},...options},target=path==='/admin/bootstrap'?'/portal/admin-completed-bootstrap':`${API}?path=${encodeURIComponent(path)}`,r=await fetch(target,init),ct=String(r.headers.get('content-type')||'');if(ct.includes('application/pdf'))return r;const j=await r.json().catch(()=>({}));if(!r.ok||j?.ok===false){const err=new Error(String(j?.code||`HTTP_${r.status}`));err.code=String(j?.code||'REQUEST_FAILED');err.status=r.status;throw err}const data=j.data;if(path==='/admin/bootstrap'&&Array.isArray(data?.rail)){data.rail=data.rail.map(x=>({...x,gu12_number:x.gu12_number??x.gu12Number??x.document_number??x.documentNumber??x.rail_document_id??x.railDocumentId,document_number:x.document_number??x.documentNumber,rail_document_id:x.rail_document_id??x.railDocumentId,deal_id:x.deal_id??x.dealId,route_text:x.route_text??x.routeText}));window.__RONA_ADMIN_COMPLETED_APPLICATIONS_PROJECTION__=String(r.headers.get('x-rona-admin-completed-applications')||'SERVER_MATERIALIZED')}return data}";

export async function onRequest(context){
  const response=await serveCurrentAdminUi(context);
  const source=await response.text();
  if(!source.includes(BUCKET_FROM)||!source.includes(ACTIONS_FROM)||!source.includes(ADMIN_BOOTSTRAP_FROM)){
    return new Response('APPLICATION_DEAL_HANDOFF_PATCH_SOURCE_MISMATCH',{status:500,headers:{'content-type':'text/plain; charset=utf-8','cache-control':'no-store'}});
  }
  const patched=source.replace(BUCKET_FROM,BUCKET_TO).replace(ACTIONS_FROM,ACTIONS_TO).replace(ADMIN_BOOTSTRAP_FROM,ADMIN_BOOTSTRAP_TO)+applicationPassportRuntime+adminVisualRedesign+adminVisualStatusChips+adminVisualPolish+adminVisualRevisionV2;
  const headers=new Headers(response.headers);
  headers.set('content-length',String(new TextEncoder().encode(patched).length));
  headers.set('x-rona-application-deal-handoff','approved-to-deal-v1');
  headers.set('x-rona-application-passport','first-render-v2');
  headers.set('x-rona-admin-completed-applications','owner-r1-server-v2');
  headers.set('x-rona-admin-visual-redesign','home-applications-deals-v1');
  headers.set('x-rona-admin-visual-revision','silver-steel-v2');
  return new Response(patched,{status:response.status,statusText:response.statusText,headers});
}
