const SUPABASE_URL='https://sxawrwzeobaqwwmlkzws.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_W2MxTx00ILiugSyZKp8uyQ_zBzcyorL';
const PRODUCTION_API=`${SUPABASE_URL}/functions/v1/rona-portal-api`;
const CANDIDATE_API=`${SUPABASE_URL}/functions/v1/rona-portal-api-candidate-20260817`;
const ACCESS_COOKIE='rona_portal_at';
const REFRESH_COOKIE='rona_portal_rt';
const SELECTOR='PR431_PREVIEW_HOST_SELECTOR_V1';
const SECURITY_HEADERS=Object.freeze({'cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache','referrer-policy':'no-referrer','x-content-type-options':'nosniff','x-frame-options':'DENY','permissions-policy':'camera=(), microphone=(), geolocation=(), payment=()','cross-origin-opener-policy':'same-origin','cross-origin-resource-policy':'same-origin'});
function parseCookies(header){const out={};for(const item of String(header||'').split(';')){const i=item.indexOf('=');if(i<1)continue;const key=item.slice(0,i).trim(),value=item.slice(i+1).trim();if(key)out[key]=value}return out}
function accessCookie(token,maxAge=3600){return `${ACCESS_COOKIE}=${token}; Max-Age=${Math.max(0,Number(maxAge)||0)}; Path=/portal; Secure; HttpOnly; SameSite=Lax`}
function refreshCookie(token,maxAge=604800){return `${REFRESH_COOKIE}=${token}; Max-Age=${Math.max(0,Number(maxAge)||0)}; Path=/portal; Secure; HttpOnly; SameSite=Lax`}
function clearCookies(){return [`${ACCESS_COOKIE}=; Max-Age=0; Path=/portal; Secure; HttpOnly; SameSite=Lax`,`${REFRESH_COOKIE}=; Max-Age=0; Path=/portal; Secure; HttpOnly; SameSite=Lax`]}
function tokenCookies(tokens){const expires=Math.min(Math.max(Number(tokens?.expires_in||3600),60),7200);return [accessCookie(tokens.access_token,expires),refreshCookie(tokens.refresh_token,604800)]}
function secure(headers=new Headers()){const out=new Headers(headers);for(const [k,v] of Object.entries(SECURITY_HEADERS))out.set(k,v);out.delete('access-control-allow-origin');out.delete('access-control-allow-credentials');out.delete('content-length');out.delete('etag');return out}
function json(body,status=200,cookies=[]){const headers=secure(new Headers({'content-type':'application/json; charset=utf-8'}));for(const cookie of cookies)headers.append('set-cookie',cookie);return new Response(JSON.stringify(body),{status,headers})}
function sameOriginPost(request){const url=new URL(request.url),origin=request.headers.get('origin');if(origin)return origin===url.origin;const ref=request.headers.get('referer');if(!ref)return false;try{return new URL(ref).origin===url.origin}catch{return false}}
async function authRefresh(refreshToken){const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,'content-type':'application/json'},body:JSON.stringify({refresh_token:refreshToken})});const data=await r.json().catch(()=>({}));return{ok:r.ok,status:r.status,data}}
function isPreviewHost(host){const h=String(host||'').toLowerCase();return h.endsWith('.rona-trade-public.pages.dev')&&h!=='rona-trade-public.pages.dev'}
function backendSelection(context,url,path){const configured=String(context?.env?.RONA_PORTAL_API_TARGET||'').trim().toLowerCase(),clientRoute=String(path||'').startsWith('/v1/client/');if(configured==='candidate'&&clientRoute)return{slot:'candidate',fn:'rona-portal-api-candidate-20260817',base:CANDIDATE_API,selector:'ENV_CANDIDATE'};if(configured==='production'||!clientRoute)return{slot:'production',fn:'rona-portal-api',base:PRODUCTION_API,selector:configured==='production'?'ENV_PRODUCTION':'NON_CLIENT_PRODUCTION'};if(isPreviewHost(url.hostname))return{slot:'candidate',fn:'rona-portal-api-candidate-20260817',base:CANDIDATE_API,selector:SELECTOR};return{slot:'production',fn:'rona-portal-api',base:PRODUCTION_API,selector:'PRODUCTION_DEFAULT'}}
async function upstream(access,request,selection){const url=new URL(request.url),path=url.pathname.slice('/portal/api'.length)||'/';const headers=new Headers({authorization:`Bearer ${access}`,accept:'application/json'});for(const name of ['content-type','x-request-id','x-correlation-id','x-idempotency-key','x-current-document-id','x-rona-client-source']){const value=request.headers.get(name);if(value)headers.set(name,value)}const init={method:request.method,headers};if(!['GET','HEAD'].includes(request.method))init.body=await request.clone().arrayBuffer();return fetch(`${selection.base}${path}${url.search}`,init)}
function finalize(response,cookies,selection){const headers=secure(response.headers);headers.set('x-rona-portal-backend-slot',selection.slot);headers.set('x-rona-portal-backend-function',selection.fn);headers.set('x-rona-portal-backend-selector',selection.selector);for(const cookie of cookies)headers.append('set-cookie',cookie);return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
export async function onRequest(context){const {request}=context;if(!['GET','POST'].includes(request.method))return json({ok:false,code:'METHOD_NOT_ALLOWED'},405);if(request.method==='POST'&&!sameOriginPost(request))return json({ok:false,code:'ORIGIN_DENIED'},403);const url=new URL(request.url),path=url.pathname.slice('/portal/api'.length)||'/',selection=backendSelection(context,url,path),cookies=parseCookies(request.headers.get('cookie'));let access=cookies[ACCESS_COOKIE]||'',refresh=cookies[REFRESH_COOKIE]||'';if(!access&&!refresh)return json({ok:false,code:'PORTAL_ACCESS_DENIED'},401,clearCookies());let response=access?await upstream(access,request,selection):null,setCookies=[];if(!response||response.status===401){if(!refresh)return json({ok:false,code:'PORTAL_ACCESS_DENIED'},401,clearCookies());let next;try{next=await authRefresh(refresh)}catch{return json({ok:false,code:'PORTAL_AUTH_BACKEND_UNAVAILABLE',retryable:true},503)}if(!next.ok||!next.data?.access_token||!next.data?.refresh_token){if(next.status===429||Number(next.status||0)>=500)return json({ok:false,code:'PORTAL_AUTH_BACKEND_UNAVAILABLE',retryable:true},503);return json({ok:false,code:'PORTAL_ACCESS_DENIED'},401,clearCookies())}access=next.data.access_token;setCookies=tokenCookies(next.data);response=await upstream(access,request,selection)}return finalize(response,setCookies,selection)}
