const SUPABASE_URL='https://sxawrwzeobaqwwmlkzws.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_W2MxTx00ILiugSyZKp8uyQ_zBzcyorL';
const PORTAL_API=`${SUPABASE_URL}/functions/v1/rona-portal-api`;
// Existing production slot hosts the canonical Client deal-document service while the project Edge Function quota is full.
const CLIENT_DEAL_DOCUMENTS_API=`${SUPABASE_URL}/functions/v1/rona-temp-upload-order-20260816`;
const ACCESS_COOKIE='rona_portal_at';
const REFRESH_COOKIE='rona_portal_rt';
const SECURITY_HEADERS=Object.freeze({'cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache','referrer-policy':'no-referrer','x-content-type-options':'nosniff','x-frame-options':'DENY','permissions-policy':'camera=(), microphone=(), geolocation=(), payment=()','cross-origin-opener-policy':'same-origin','cross-origin-resource-policy':'same-origin'});
const EXTERNAL_DOCUMENT_TYPES=new Set(['CONTRACT','КОНТРАКТ','ADDENDUM','SIGNED_ADDENDUM','INVOICE','CLOSING_DOCUMENT']);
const AGENT_AMOUNT_VISIBLE_STAGES=new Set(['APPROVED','PAYABLE_CONFIRMED','PAID']);
function parseCookies(header){const out={};for(const item of String(header||'').split(';')){const i=item.indexOf('=');if(i<1)continue;const k=item.slice(0,i).trim(),v=item.slice(i+1).trim();if(k)out[k]=v}return out}
function accessCookie(token,maxAge=3600){return `${ACCESS_COOKIE}=${token}; Max-Age=${Math.max(0,Number(maxAge)||0)}; Path=/portal; Secure; HttpOnly; SameSite=Lax`}
function refreshCookie(token,maxAge=604800){return `${REFRESH_COOKIE}=${token}; Max-Age=${Math.max(0,Number(maxAge)||0)}; Path=/portal; Secure; HttpOnly; SameSite=Lax`}
function clearCookies(){return[`${ACCESS_COOKIE}=; Max-Age=0; Path=/portal; Secure; HttpOnly; SameSite=Lax`,`${REFRESH_COOKIE}=; Max-Age=0; Path=/portal; Secure; HttpOnly; SameSite=Lax`]}
function tokenCookies(t){const e=Math.min(Math.max(Number(t?.expires_in||3600),60),7200);return[accessCookie(t.access_token,e),refreshCookie(t.refresh_token,604800)]}
function secureHeaders(base=new Headers()){const h=new Headers(base);for(const[k,v]of Object.entries(SECURITY_HEADERS))h.set(k,v);h.delete('access-control-allow-origin');h.delete('access-control-allow-credentials');h.delete('content-length');h.delete('etag');return h}
function json(body,status=200,cookies=[]){const h=secureHeaders(new Headers({'content-type':'application/json; charset=utf-8'}));for(const c of cookies)h.append('set-cookie',c);return new Response(JSON.stringify(body),{status,headers:h})}
function sameOrigin(request){const u=new URL(request.url),origin=request.headers.get('origin');if(origin)return origin===u.origin;const ref=request.headers.get('referer');if(!ref)return ['GET','HEAD'].includes(request.method);try{return new URL(ref).origin===u.origin}catch{return false}}
async function authRefresh(refreshToken){const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,'content-type':'application/json'},body:JSON.stringify({refresh_token:refreshToken})});const data=await r.json().catch(()=>({}));return{ok:r.ok,data}}
function safePrice(p){return{id:p?.id??p?.publication_item_id??null,publication_item_id:p?.publication_item_id??p?.id??null,publication_id:p?.publication_id??null,product:p?.product??null,producer:p?.producer??null,basis:p?.basis??null,final_station:p?.final_station??null,sale_price:p?.sale_price??p?.price??null,price:p?.price??p?.sale_price??null,currency:p?.currency??null,payment_terms:p?.payment_terms??null,commercial_terms:p?.commercial_terms??null,published_at:p?.published_at??null,valid_from:p?.valid_from??null,valid_to:p?.valid_to??null,delivery_period_from:p?.delivery_period_from??null,delivery_period_to:p?.delivery_period_to??null}}
function safePriceAuthority(a){const publicationStatus=String(a?.publication_status??'').toUpperCase(),publicationAuthority=String(a?.publication_authority_state??'').toUpperCase(),publicationLifecycle=String(a?.publication_lifecycle_state??'').toUpperCase(),itemAuthority=String(a?.item_authority_state??'').toUpperCase(),itemLifecycle=String(a?.item_lifecycle_state??'').toUpperCase(),businessStatus=String(a?.business_status??'').toUpperCase();if(publicationStatus!=='PUBLISHED'||!['CONFIRMED','VERIFIED'].includes(publicationAuthority)||publicationLifecycle!=='ACTIVE'||!['CONFIRMED','VERIFIED'].includes(itemAuthority)||itemLifecycle!=='ACTIVE'||businessStatus!=='PUBLISHED'||a?.publish_client!==true)return null;return{publication_item_id:a?.publication_item_id??null,publication_id:a?.publication_id??null,publication_status:publicationStatus,publication_authority_state:publicationAuthority,publication_lifecycle_state:publicationLifecycle,item_authority_state:itemAuthority,item_lifecycle_state:itemLifecycle,product:a?.product??null,producer:a?.producer??null,supplier:a?.supplier??null,snapshot_basis:a?.snapshot_basis??null,final_station:a?.final_station??null,snapshot_price:a?.snapshot_price??null,snapshot_currency:a?.snapshot_currency??null,payment_terms:a?.payment_terms??null,commercial_terms:a?.commercial_terms??null,business_status:businessStatus,publish_client:true,client_published_at:a?.client_published_at??null,updated_at:a?.updated_at??null}}
function safeDocument(d,{includeStorage=false}={}){const type=String(d?.document_type??d?.documentType??d?.type??'').toUpperCase();if(type&&!EXTERNAL_DOCUMENT_TYPES.has(type))return null;const authority=String(d?.authority_state??d?.authorityState??'');if(authority&&!['VERIFIED','CONFIRMED'].includes(authority))return null;const lifecycle=String(d?.lifecycle_state??d?.lifecycleState??'');if(lifecycle&&lifecycle!=='ACTIVE')return null;const out={document_id:d?.document_id??d?.documentId??null,document_type:type||null,authoritative_filename:d?.authoritative_filename??d?.filename??null,deal_id:d?.deal_id??d?.dealId??null,lifecycle_state:lifecycle||'ACTIVE',authority_state:authority||null,updated_at:d?.updated_at??null};if(includeStorage)out.storage_object_id=d?.storage_object_id??d?.storageObjectId??null;return out}
function safeClientApplication(a){return{application_id:a?.application_id??null,product:a?.product??null,quantity_tonnes:a?.quantity_tonnes??null,delivery_period_from:a?.delivery_period_from??null,delivery_period_to:a?.delivery_period_to??null,delivery_basis:a?.delivery_basis??null,destination:a?.destination??null,payment_terms:a?.payment_terms??null,price_mode:a?.price_mode??null,proposed_price:a?.proposed_price??null,proposed_currency:a?.proposed_currency??null,status:a?.status??null,deal_id:a?.deal_id??null,submitted_at:a?.submitted_at??null,updated_at:a?.updated_at??null}}
function safeClientContext(data){const out={};if(data?.projection_contract)out.projection_contract=data.projection_contract;if(data?.contract)out.contract={client_id:data.contract.client_id??null,legal_name:data.contract.legal_name??null,contract_id:data.contract.contract_id??data.contract.contractId??null,current_external_contract_number:data.contract.current_external_contract_number??data.contract.currentExternalContractNumber??null,contract_status:data.contract.contract_status??data.contract.status??null,effective_from:data.contract.effective_from??null,effective_to:data.contract.effective_to??null,verification_status:'CONFIRMED_CURRENT',verification_source:'AUTHORITATIVE_CONTRACT_ACCESS_GATE'};out.applications=(Array.isArray(data?.applications)?data.applications:[]).map(safeClientApplication);if(data?.application)out.application=safeClientApplication(data.application);out.deals=(Array.isArray(data?.deals)?data.deals:[]).map(d=>({deal_id:d?.deal_id??d?.dealId??null,business_status:d?.business_status??d?.status??null,status:d?.business_status??d?.status??null,stage:d?.stage??null,current_status:d?.current_status??null,current_status_label:d?.current_status_label??null,status_source:d?.status_source??null,payment_status:d?.payment_status??null,payment_label:d?.payment_label??null,payment_received_amount:d?.payment_received_amount??null,payment_obligation_amount:d?.payment_obligation_amount??null,payment_currency:d?.payment_currency??null,payment_percent:d?.payment_percent??null,payment_source:d?.payment_source??null,resource_status:d?.resource_status??null,resource_label:d?.resource_label??null,resource_source:d?.resource_source??null,opened_at:d?.opened_at??null,closed_at:d?.closed_at??null,updated_at:d?.updated_at??null}));out.documents=(Array.isArray(data?.documents)?data.documents:[]).map(d=>safeDocument(d,{includeStorage:true})).filter(Boolean);out.payments=(Array.isArray(data?.payments)?data.payments:[]).map(p=>({payment_id:p?.payment_id??p?.paymentId??null,deal_id:p?.deal_id??p?.dealId??null,amount:p?.amount??null,currency:p?.currency??null,bank_fact_status:p?.bank_state??p?.payment_bank_state??p?.bankFactStatus??null,bank_confirmed_at:p?.bank_confirmed_at??p?.confirmed_at??null,payment_at:p?.payment_at??null,received_at:p?.received_at??p?.payment_at??null,updated_at:p?.updated_at??null}));out.prices=(Array.isArray(data?.prices)?data.prices:[]).map(safePrice);out.shipments=[];out.railPublicationGate={status:'FAIL_CLOSED',reason:'AUTHORITATIVE_SHIPMENT_REQUIRED'};return out}
function safeClientBootstrap(data){const contexts=(Array.isArray(data?.contexts)?data.contexts:[]).map(c=>({client_id:c?.client_id??null,legal_name:c?.legal_name??null,registration_country:c?.registration_country??null,registered_address:c?.registered_address??null,contact_phone:c?.contact_phone??null,contract_id:c?.contract_id??null,current_external_contract_number:c?.current_external_contract_number??null,contract_status:c?.contract_status??null,effective_from:c?.effective_from??null,effective_to:c?.effective_to??null,verification_status:'CONFIRMED_CURRENT',verification_source:'AUTHORITATIVE_CONTRACT_ACCESS_GATE'}));const price_authority=(Array.isArray(data?.price_authority)?data.price_authority:[]).map(safePriceAuthority).filter(Boolean);return{generated_at:data?.generated_at??null,data_contract:data?.data_contract??null,requires_context_selection:Boolean(data?.requires_context_selection??contexts.length>1),contexts,price_authority}}
function safeAgentSettlement(s){const stage=String(s?.stage??s?.settlement_state??s?.status??'');const visible=AGENT_AMOUNT_VISIBLE_STAGES.has(stage);return{settlementId:s?.settlementId??s?.settlement_id??null,dealId:s?.dealId??s?.deal_id??null,clientId:s?.clientId??s?.client_id??null,stage,amount:visible?(s?.amount??null):null,currency:visible?(s?.currency??null):null,paymentObligationConfirmed:!!(s?.paymentObligationConfirmed??s?.payable_confirmed_at),paymentFactConfirmed:!!(s?.paymentFactConfirmed??s?.paid_at),updatedAt:s?.updatedAt??s?.updated_at??null}}
function safeAgentBootstrap(data){const out={assignedClients:(Array.isArray(data?.assignedClients)?data.assignedClients:Array.isArray(data?.companies)?data.companies:[]).map(c=>({clientId:c?.clientId??c?.client_id??null,legalName:c?.legalName??c?.legal_name??null,contractId:c?.contractId??c?.contract_id??null})),deals:(Array.isArray(data?.deals)?data.deals:[]).map(d=>({dealId:d?.dealId??d?.deal_id??null,clientId:d?.clientId??d?.client_id??null,status:d?.status??d?.business_status??null,updatedAt:d?.updatedAt??d?.updated_at??null})),documents:(Array.isArray(data?.documents)?data.documents:[]).map(safeDocument).filter(Boolean),settlements:(Array.isArray(data?.settlements)?data.settlements:[]).map(safeAgentSettlement),economics:[],messages:[]};if(data?.pricePublication)out.pricePublication=data.pricePublication;return out}
function safeAgentPayment(data){return{paymentId:data?.paymentId??data?.payment_id??null,dealId:data?.dealId??data?.deal_id??null,amount:data?.amount??null,currency:data?.currency??null,bankFactStatus:data?.bankFactStatus??data?.bank_state??data?.payment_bank_state??null,bankConfirmedAt:data?.bankConfirmedAt??data?.bank_confirmed_at??null,receivedAt:data?.receivedAt??data?.received_at??data?.payment_at??null}}
function isClientDealDocumentsPath(path){return path==='/v1/client/deal-documents/state'||/^\/v1\/client\/deals\/DEAL-\d{4}-\d{3,}\/documents\/[^/]+\/downloaded$/.test(path)||/^\/v1\/client\/deals\/DEAL-\d{4}-\d{3,}\/signed-addendum$/.test(path)}
function isSignedAddendumUpload(path,method){return method==='POST'&&/^\/v1\/client\/deals\/DEAL-\d{4}-\d{3,}\/signed-addendum$/.test(path)}
async function sanitize(path,response){if(!response.ok)return response;const ct=String(response.headers.get('content-type')||'');if(!ct.includes('application/json'))return response;const target=path==='/v1/client/bootstrap'||path==='/v1/client/context'||path==='/v1/agent/bootstrap'||/^\/v1\/agent\/payments\//.test(path);if(!target)return response;const payload=await response.json().catch(()=>null);if(!payload||typeof payload!=='object')return json({ok:false,code:'EXTERNAL_PROJECTION_INVALID'},502);if(payload.data&&typeof payload.data==='object'){if(path==='/v1/client/bootstrap')payload.data=safeClientBootstrap(payload.data);else if(path==='/v1/client/context')payload.data=safeClientContext(payload.data);else if(path==='/v1/agent/bootstrap')payload.data=safeAgentBootstrap(payload.data);else payload.data=safeAgentPayment(payload.data)}const h=new Headers(response.headers);h.set('content-type','application/json; charset=utf-8');return new Response(JSON.stringify(payload),{status:response.status,statusText:response.statusText,headers:h})}
export async function onRequest(context){const request=context.request;if(!sameOrigin(request))return json({ok:false,code:'ORIGIN_DENIED'},403);const url=new URL(request.url);const prefix='/portal/api';let path=url.pathname.startsWith(prefix)?url.pathname.slice(prefix.length):'';if(!path.startsWith('/')||path.includes('..'))return json({ok:false,code:'ROUTE_NOT_ALLOWED'},404);const query=url.search||'';const cookies=parseCookies(request.headers.get('cookie'));let access=cookies[ACCESS_COOKIE]||'',refresh=cookies[REFRESH_COOKIE]||'',setCookies=[];if(!access&&refresh){const next=await authRefresh(refresh);if(next.ok&&next.data?.access_token&&next.data?.refresh_token){access=next.data.access_token;refresh=next.data.refresh_token;setCookies=tokenCookies(next.data)}}if(!access)return json({ok:false,code:'PORTAL_ACCESS_DENIED'},401,clearCookies());const multipartUpload=isSignedAddendumUpload(path,request.method);let body=null,uploadParts=null;if(multipartUpload){let form;try{form=await request.clone().formData()}catch{return json({ok:false,code:'INVALID_MULTIPART'},400)}const file=form.get('file'),source=form.get('sourceUnsignedDocumentId');if(!(file instanceof File))return json({ok:false,code:'PDF_REQUIRED'},400);if(typeof source!=='string'||!source.trim())return json({ok:false,code:'SOURCE_ADDENDUM_REQUIRED'},400);uploadParts={file,source:source.trim()}}else if(!['GET','HEAD'].includes(request.method))body=await request.clone().arrayBuffer();const forward=async token=>{const h=new Headers({authorization:`Bearer ${token}`,accept:request.headers.get('accept')||'application/json'});for(const name of['content-type','x-request-id','x-correlation-id','x-idempotency-key']){const v=request.headers.get(name);if(v)h.set(name,v)}const init={method:request.method,headers:h};if(uploadParts){h.delete('content-type');const fd=new FormData();fd.append('file',uploadParts.file,uploadParts.file.name);fd.append('sourceUnsignedDocumentId',uploadParts.source);init.body=fd}else if(body!==null)init.body=body;const target=isClientDealDocumentsPath(path)?`${CLIENT_DEAL_DOCUMENTS_API}${path}${query}`:`${PORTAL_API}${path}${query}`;return fetch(target,init)};let response=await forward(access);if(response.status===401&&refresh){const next=await authRefresh(refresh);if(next.ok&&next.data?.access_token&&next.data?.refresh_token){access=next.data.access_token;setCookies=tokenCookies(next.data);response=await forward(access)}}response=await sanitize(path,response);const h=secureHeaders(response.headers);for(const c of setCookies)h.append('set-cookie',c);if(response.status===401&&!setCookies.length)for(const c of clearCookies())h.append('set-cookie',c);return new Response(response.body,{status:response.status,statusText:response.statusText,headers:h})}
