-- Admin Prices current-only workspace + Operations Director CP workflow.
create table if not exists portal_private.owner_price_list_controls (
  id uuid primary key default gen_random_uuid(), publication_key uuid not null unique references portal_private.publications(id) on delete restrict,
  internal_state text not null default 'RECEIVED_IN_ADMIN' check (internal_state in ('RECEIVED_IN_ADMIN','READY_FOR_REVIEW','RETIRED')),
  received_from_role text not null default 'OPERATIONS_DIRECTOR', received_from_identity text not null default 'AI-OPERATIONS-DIRECTOR', received_at timestamptz not null default now(),
  client_enabled boolean not null default false, agent_enabled boolean not null default false, client_published_at timestamptz, agent_published_at timestamptz,
  published_by uuid references portal_private.portal_users(id) on delete restrict, source_refs jsonb not null default '[]'::jsonb,
  authority_state portal_private.authority_state_enum not null default 'CONFIRMED'::portal_private.authority_state_enum,
  lifecycle_state portal_private.lifecycle_state_enum not null default 'ACTIVE'::portal_private.lifecycle_state_enum,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists portal_private.owner_agent_commercial_proposals (
  id uuid primary key default gen_random_uuid(), cp_id text not null unique, publication_key uuid not null references portal_private.publications(id) on delete restrict,
  agent_legal_entity_key uuid not null references portal_private.agent_legal_entities(id) on delete restrict, version integer not null default 1 check(version>0),
  document_key uuid references portal_private.documents(id) on delete restrict, request_event_key uuid references portal_private.portal_reverse_events(id) on delete restrict,
  status text not null default 'REQUESTED' check(status in ('REQUESTED','GENERATED','OWNER_REVIEWED','SENT','BLOCKED','RETIRED')),
  generated_by_identity text, generated_at timestamptz, owner_reviewed_at timestamptz, owner_reviewed_by uuid references portal_private.portal_users(id) on delete restrict,
  sent_at timestamptz, sent_by uuid references portal_private.portal_users(id) on delete restrict, source_refs jsonb not null default '[]'::jsonb,
  authority_state portal_private.authority_state_enum not null default 'SOURCE_RECEIVED'::portal_private.authority_state_enum,
  lifecycle_state portal_private.lifecycle_state_enum not null default 'ACTIVE'::portal_private.lifecycle_state_enum,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(publication_key,agent_legal_entity_key,version)
);
create index if not exists idx_owner_agent_cp_publication on portal_private.owner_agent_commercial_proposals(publication_key,status,created_at desc);
create index if not exists idx_owner_agent_cp_agent on portal_private.owner_agent_commercial_proposals(agent_legal_entity_key,created_at desc);
drop trigger if exists trg_owner_price_list_controls_touch on portal_private.owner_price_list_controls;
create trigger trg_owner_price_list_controls_touch before update on portal_private.owner_price_list_controls for each row execute function portal_private.touch_updated_at();
drop trigger if exists trg_owner_agent_cp_touch on portal_private.owner_agent_commercial_proposals;
create trigger trg_owner_agent_cp_touch before update on portal_private.owner_agent_commercial_proposals for each row execute function portal_private.touch_updated_at();

create or replace function portal_private.materialize_owner_price_list_control_v1() returns trigger language plpgsql security definer set search_path to 'pg_catalog','portal_private' as $$
declare v_publication_key uuid;
begin
  if new.source_publication_item_key is null or new.business_status='SUPERSEDED' then return new; end if;
  select publication_key into v_publication_key from portal_private.publication_items where id=new.source_publication_item_key limit 1;
  if v_publication_key is null then return new; end if;
  insert into portal_private.owner_price_list_controls(publication_key,internal_state,received_from_role,received_from_identity,received_at,source_refs,authority_state,lifecycle_state)
  values(v_publication_key,'RECEIVED_IN_ADMIN','OPERATIONS_DIRECTOR','AI-OPERATIONS-DIRECTOR',coalesce(new.agreed_at,now()),jsonb_build_array(coalesce(new.source_reference,'')),'CONFIRMED','ACTIVE')
  on conflict(publication_key) do update set internal_state=case when portal_private.owner_price_list_controls.internal_state='RETIRED' then 'RETIRED' else 'RECEIVED_IN_ADMIN' end,received_at=least(portal_private.owner_price_list_controls.received_at,excluded.received_at),updated_at=now();
  return new;
end $$;
drop trigger if exists trg_owner_price_snapshot_list_control on portal_private.owner_price_snapshots;
create trigger trg_owner_price_snapshot_list_control after insert or update of source_publication_item_key,business_status on portal_private.owner_price_snapshots for each row execute function portal_private.materialize_owner_price_list_control_v1();
insert into portal_private.owner_price_list_controls(publication_key,internal_state,received_from_role,received_from_identity,received_at,client_enabled,agent_enabled,client_published_at,agent_published_at,source_refs,authority_state,lifecycle_state)
select pi.publication_key,'RECEIVED_IN_ADMIN','OPERATIONS_DIRECTOR','AI-OPERATIONS-DIRECTOR',min(coalesce(ops.agreed_at,ops.created_at)),bool_or(coalesce(ops.publish_client,false)),bool_or(coalesce(ops.publish_agent,false)),max(ops.client_published_at),max(ops.agent_published_at),jsonb_agg(distinct coalesce(ops.source_reference,'')),'CONFIRMED','ACTIVE'
from portal_private.owner_price_snapshots ops join portal_private.publication_items pi on pi.id=ops.source_publication_item_key where ops.business_status<>'SUPERSEDED' group by pi.publication_key on conflict(publication_key) do nothing;

create or replace function public.owner_prices_admin_workspace() returns jsonb language plpgsql security definer set search_path to 'pg_catalog','public','portal_private','auth' as $$
declare v_actor uuid; v_out jsonb;
begin
  v_actor:=portal_private.owner_r1_actor('ADMIN');
  select jsonb_build_object('generatedAt',now(),'operationsIdentity',jsonb_build_object('role','OPERATIONS_DIRECTOR','identityId','AI-OPERATIONS-DIRECTOR','displayName','Операционный директор'),
  'priceLists',coalesce((select jsonb_agg(to_jsonb(x) order by x.received_at desc) from (select p.publication_id,p.title,p.status::text publication_status,p.audience source_audience,p.prepared_at,p.approved_at,p.published_at source_published_at,c.internal_state,c.received_from_role,c.received_from_identity,c.received_at,c.client_enabled,c.agent_enabled,c.client_published_at,c.agent_published_at,count(distinct pi.id)::int item_count,min(pi.valid_from) valid_from,max(pi.valid_to) valid_to,bool_and(pi.authority_state::text in ('VERIFIED','CONFIRMED')) item_authority_ok,bool_and(coalesce(pi.distribution_allowed,false)) distribution_allowed from portal_private.owner_price_list_controls c join portal_private.publications p on p.id=c.publication_key left join portal_private.publication_items pi on pi.publication_key=p.id and pi.lifecycle_state::text='ACTIVE' and pi.item_type::text='PRICE' where c.lifecycle_state::text='ACTIVE' and p.lifecycle_state::text='ACTIVE' group by p.id,c.id) x),'[]'::jsonb),
  'items',coalesce((select jsonb_agg(to_jsonb(x) order by x.agreed_at desc,x.product,x.final_station) from (select p.publication_id,ops.id,ops.product,ops.producer,ops.supplier,ops.purchase_price,ops.rail_tariff,ops.rail_segments,ops.basis,ops.border_crossing,ops.final_station,ops.landed_cost,ops.rona_margin,ops.sale_price,ops.currency,ops.payment_terms,ops.commercial_terms,ops.business_status,ops.agreed_at from portal_private.owner_price_snapshots ops join portal_private.publication_items pi on pi.id=ops.source_publication_item_key join portal_private.publications p on p.id=pi.publication_key where ops.business_status<>'SUPERSEDED' and p.lifecycle_state::text='ACTIVE') x),'[]'::jsonb),
  'agentCommercialProposals',coalesce((select jsonb_agg(to_jsonb(x) order by x.created_at desc) from (select cp.cp_id,p.publication_id,ale.agent_legal_entity_id,ale.legal_name agent_legal_name,cp.version,cp.status,cp.generated_by_identity,cp.generated_at,cp.owner_reviewed_at,cp.sent_at,cp.created_at,d.document_id,d.authoritative_filename,dv.sha256,dv.version_number document_version from portal_private.owner_agent_commercial_proposals cp join portal_private.publications p on p.id=cp.publication_key join portal_private.agent_legal_entities ale on ale.id=cp.agent_legal_entity_key left join portal_private.documents d on d.id=cp.document_key left join portal_private.document_versions dv on dv.id=d.current_version_id and dv.is_current and dv.is_effective where cp.lifecycle_state::text='ACTIVE') x),'[]'::jsonb),
  'activeAgents',coalesce((select jsonb_agg(to_jsonb(x) order by x.legal_name) from (select distinct ale.agent_legal_entity_id,ale.legal_name from portal_private.agent_client_assignments aca join portal_private.agent_legal_entities ale on ale.id=aca.agent_legal_entity_key where aca.status::text='ACTIVE' and aca.lifecycle_state::text='ACTIVE' and aca.authority_state::text in ('VERIFIED','CONFIRMED') and aca.valid_from<=now() and (aca.valid_to is null or aca.valid_to>now()) and ale.lifecycle_state::text='ACTIVE') x),'[]'::jsonb)) into v_out;
  return v_out;
end $$;

create or replace function public.owner_prices_agent_cp_request(p_publication_id text) returns jsonb language plpgsql security definer set search_path to 'pg_catalog','public','portal_private','auth' as $$
declare v_actor uuid;v_auth uuid;v_publication_key uuid;v_title text;v_event_key uuid;v_event_id text;v_req uuid:=gen_random_uuid();v_count int:=0;r record;v_version int;v_cp_id text;
begin
  v_actor:=portal_private.owner_r1_actor('ADMIN');v_auth:=auth.uid();
  select id,title into v_publication_key,v_title from portal_private.publications where publication_id=p_publication_id and publication_type::text='PRICE' and lifecycle_state::text='ACTIVE' and authority_state::text in ('VERIFIED','CONFIRMED') limit 1;
  if v_publication_key is null then raise exception 'PRICE_LIST_NOT_FOUND'; end if;
  if not exists(select 1 from portal_private.owner_price_list_controls where publication_key=v_publication_key and lifecycle_state::text='ACTIVE') then raise exception 'PRICE_LIST_NOT_IN_ADMIN'; end if;
  v_event_id:='PORTAL-EVT-PRICE-CP-'||replace(v_req::text,'-','');
  insert into portal_private.portal_reverse_events(event_id,idempotency_key,actor_user_id,actor_auth_user_id,actor_role,event_type,authority_domain,authority_target_type,authority_target_id,payload,request_id,source_system,source_version,authority_state,lifecycle_state)
  values(v_event_id,'ADMIN_PRICE_CP:'||p_publication_id||':'||v_req::text,v_actor,v_auth,'ADMIN','ADMIN_AGENT_CP_PREPARE','COMMERCIAL','PRICE_LIST',p_publication_id,jsonb_build_object('publicationId',p_publication_id,'title',v_title,'requestedAction','GENERATE_AGENT_CP','canonicalMasterId','RONA-AGENT-CP-2026-001','operationsIdentity','AI-OPERATIONS-DIRECTOR','ownerPreviewRequired',true,'externalPublicationAllowed',false,'qa_only',false),v_req,'ADMIN_PORTAL','PRICES_OPS_CURRENT_V1','SOURCE_RECEIVED','ACTIVE') returning id into v_event_key;
  for r in select distinct ale.id,ale.agent_legal_entity_id from portal_private.agent_client_assignments aca join portal_private.agent_legal_entities ale on ale.id=aca.agent_legal_entity_key where aca.status::text='ACTIVE' and aca.lifecycle_state::text='ACTIVE' and aca.authority_state::text in ('VERIFIED','CONFIRMED') and aca.valid_from<=now() and (aca.valid_to is null or aca.valid_to>now()) and ale.lifecycle_state::text='ACTIVE' loop
    select coalesce(max(version),0)+1 into v_version from portal_private.owner_agent_commercial_proposals where publication_key=v_publication_key and agent_legal_entity_key=r.id;
    v_cp_id:='RONA-AGENT-CP-'||replace(left(p_publication_id,80),' ','-')||'-'||r.agent_legal_entity_id||'-V'||v_version;
    insert into portal_private.owner_agent_commercial_proposals(cp_id,publication_key,agent_legal_entity_key,version,request_event_key,status,source_refs,authority_state,lifecycle_state) values(v_cp_id,v_publication_key,r.id,v_version,v_event_key,'REQUESTED',jsonb_build_array(p_publication_id,'RONA-AGENT-CP-2026-001'),'SOURCE_RECEIVED','ACTIVE');v_count:=v_count+1;
  end loop;
  if v_count=0 then raise exception 'NO_ACTIVE_AGENTS'; end if;
  insert into portal_private.audit_events(actor_user_id,actor_role,action,entity_type,entity_id,request_id,metadata) values(v_actor,'ADMIN','OWNER_AGENT_CP_PREPARATION_REQUESTED','PRICE_LIST',p_publication_id,v_req,jsonb_build_object('eventId',v_event_id,'agents',v_count,'targetRole','OPERATIONS_DIRECTOR'));
  return jsonb_build_object('publicationId',p_publication_id,'eventId',v_event_id,'requested',v_count,'status','QUEUED_TO_OPERATIONS_DIRECTOR');
end $$;

create or replace function public.owner_prices_cp_mark_reviewed(p_cp_id text) returns jsonb language plpgsql security definer set search_path to 'pg_catalog','public','portal_private','auth' as $$
declare v_actor uuid;v_req uuid:=gen_random_uuid();v_doc text;v_status text;
begin
 v_actor:=portal_private.owner_r1_actor('ADMIN');select d.document_id,cp.status into v_doc,v_status from portal_private.owner_agent_commercial_proposals cp join portal_private.documents d on d.id=cp.document_key join portal_private.document_versions dv on dv.id=d.current_version_id and dv.is_current and dv.is_effective where cp.cp_id=p_cp_id and cp.lifecycle_state::text='ACTIVE' limit 1;if v_doc is null then raise exception 'AGENT_CP_DOCUMENT_NOT_READY';end if;if v_status='SENT' then return jsonb_build_object('cpId',p_cp_id,'status','SENT');end if;update portal_private.owner_agent_commercial_proposals set status='OWNER_REVIEWED',owner_reviewed_at=now(),owner_reviewed_by=v_actor,authority_state='CONFIRMED',updated_at=now() where cp_id=p_cp_id and status in ('GENERATED','OWNER_REVIEWED');if not found then raise exception 'AGENT_CP_NOT_REVIEWABLE';end if;insert into portal_private.audit_events(actor_user_id,actor_role,action,entity_type,entity_id,request_id,metadata) values(v_actor,'ADMIN','OWNER_AGENT_CP_REVIEWED','AGENT_CP',p_cp_id,v_req,jsonb_build_object('documentId',v_doc));return jsonb_build_object('cpId',p_cp_id,'status','OWNER_REVIEWED','documentId',v_doc);
end $$;

create or replace function public.owner_prices_publication_action(p_publication_id text,p_audience text) returns jsonb language plpgsql security definer set search_path to 'pg_catalog','public','portal_private','auth' as $$
declare v_actor uuid;v_req uuid:=gen_random_uuid();v_pub uuid;v_client bool;v_agent bool;v_missing int;v_agents int;
begin
 v_actor:=portal_private.owner_r1_actor('ADMIN');if upper(coalesce(p_audience,'')) not in ('CLIENTS','AGENTS','BOTH','NONE') then raise exception 'INVALID_PRICE_AUDIENCE';end if;v_client:=upper(p_audience) in ('CLIENTS','BOTH');v_agent:=upper(p_audience) in ('AGENTS','BOTH');select p.id into v_pub from portal_private.publications p join portal_private.owner_price_list_controls c on c.publication_key=p.id and c.lifecycle_state::text='ACTIVE' where p.publication_id=p_publication_id and p.publication_type::text='PRICE' and p.lifecycle_state::text='ACTIVE' and p.authority_state::text in ('VERIFIED','CONFIRMED') limit 1;if v_pub is null then raise exception 'PRICE_LIST_NOT_FOUND';end if;if not exists(select 1 from portal_private.publication_items where publication_key=v_pub and item_type::text='PRICE' and lifecycle_state::text='ACTIVE' and authority_state::text in ('VERIFIED','CONFIRMED') and distribution_allowed=true) then raise exception 'PRICE_LIST_DISTRIBUTION_NOT_ALLOWED';end if;
 if v_agent then select count(distinct ale.id) into v_agents from portal_private.agent_client_assignments aca join portal_private.agent_legal_entities ale on ale.id=aca.agent_legal_entity_key where aca.status::text='ACTIVE' and aca.lifecycle_state::text='ACTIVE' and aca.authority_state::text in ('VERIFIED','CONFIRMED') and aca.valid_from<=now() and (aca.valid_to is null or aca.valid_to>now()) and ale.lifecycle_state::text='ACTIVE';select count(*) into v_missing from (select distinct ale.id from portal_private.agent_client_assignments aca join portal_private.agent_legal_entities ale on ale.id=aca.agent_legal_entity_key where aca.status::text='ACTIVE' and aca.lifecycle_state::text='ACTIVE' and aca.authority_state::text in ('VERIFIED','CONFIRMED') and aca.valid_from<=now() and (aca.valid_to is null or aca.valid_to>now()) and ale.lifecycle_state::text='ACTIVE') a where not exists(select 1 from portal_private.owner_agent_commercial_proposals cp where cp.publication_key=v_pub and cp.agent_legal_entity_key=a.id and cp.lifecycle_state::text='ACTIVE' and cp.status='OWNER_REVIEWED' and cp.document_key is not null);if v_agents=0 then raise exception 'NO_ACTIVE_AGENTS';end if;if v_missing>0 then raise exception 'AGENT_CP_OWNER_REVIEW_REQUIRED';end if;end if;
 update portal_private.owner_price_snapshots ops set publish_client=v_client,publish_agent=v_agent,client_published_at=case when v_client then coalesce(client_published_at,now()) else null end,agent_published_at=case when v_agent then coalesce(agent_published_at,now()) else null end,business_status=case when v_client or v_agent then 'PUBLISHED' else 'AGREED' end,published_at=case when v_client or v_agent then coalesce(published_at,now()) else null end,published_by=v_actor,updated_at=now() where ops.source_publication_item_key in(select id from portal_private.publication_items where publication_key=v_pub) and ops.business_status<>'SUPERSEDED';update portal_private.owner_price_list_controls set client_enabled=v_client,agent_enabled=v_agent,client_published_at=case when v_client then coalesce(client_published_at,now()) else null end,agent_published_at=case when v_agent then coalesce(agent_published_at,now()) else null end,published_by=v_actor,internal_state='READY_FOR_REVIEW',updated_at=now() where publication_key=v_pub;if v_agent then update portal_private.owner_agent_commercial_proposals set status='SENT',sent_at=coalesce(sent_at,now()),sent_by=v_actor,updated_at=now() where publication_key=v_pub and lifecycle_state::text='ACTIVE' and status='OWNER_REVIEWED';end if;insert into portal_private.audit_events(actor_user_id,actor_role,action,entity_type,entity_id,request_id,metadata) values(v_actor,'ADMIN','OWNER_PRICE_LIST_PUBLICATION_UPDATED','PRICE_LIST',p_publication_id,v_req,jsonb_build_object('audience',upper(p_audience),'client',v_client,'agent',v_agent,'agentCpGate',v_agent));return jsonb_build_object('publicationId',p_publication_id,'audience',upper(p_audience),'client',v_client,'agent',v_agent,'status',case when v_client or v_agent then 'PUBLISHED' else 'INTERNAL_ONLY' end);
end $$;
revoke all on function public.owner_prices_admin_workspace() from public;revoke all on function public.owner_prices_agent_cp_request(text) from public;revoke all on function public.owner_prices_cp_mark_reviewed(text) from public;revoke all on function public.owner_prices_publication_action(text,text) from public;grant execute on function public.owner_prices_admin_workspace() to authenticated;grant execute on function public.owner_prices_agent_cp_request(text) to authenticated;grant execute on function public.owner_prices_cp_mark_reviewed(text) to authenticated;grant execute on function public.owner_prices_publication_action(text,text) to authenticated;
