-- Payments V8 final runtime core. Current signed document -> Finance schedule -> immutable Finance authority.

create or replace function portal_private.supersede_payment_plan_before_v8_insert()
returns trigger language plpgsql security definer set search_path to 'pg_catalog','portal_private' as $function$
begin
  if new.source_system='FINANCE_SIGNED_DOCUMENT_PAYMENT_SCHEDULE_V8' and new.schedule_group_id is not null then
    update portal_private.owner_payment_plan p set status='CANCELLED',schedule_authority_state=case when p.schedule_authority_state='TO_VERIFY' then 'TO_VERIFY' else 'SUPERSEDED' end,updated_at=clock_timestamp()
    where p.deal_key=new.deal_key and p.status<>'CANCELLED' and p.schedule_group_id is distinct from new.schedule_group_id;
  end if; return new;
end;$function$;
drop trigger if exists owner_payment_plan_v8_supersede_before_insert on portal_private.owner_payment_plan;
create trigger owner_payment_plan_v8_supersede_before_insert before insert on portal_private.owner_payment_plan for each row execute function portal_private.supersede_payment_plan_before_v8_insert();

create or replace function portal_private.ensure_signed_document_schedule_job_v8(p_document_key uuid,p_version_key uuid default null)
returns uuid language plpgsql security definer set search_path to 'pg_catalog','portal_private' as $function$
declare v_doc portal_private.documents%rowtype; v_ver portal_private.document_versions%rowtype; v_link portal_private.owner_deal_documents%rowtype; v_deal portal_private.deals%rowtype; v_job_id uuid; v_task_id text; v_desc text;
begin
  select * into v_doc from portal_private.documents where id=p_document_key;
  if not found or upper(coalesce(v_doc.document_type,'')) not in ('SIGNED_ADDENDUM','SIGNED_SPECIFICATION','SIGNED_CONTRACT') or upper(coalesce(v_doc.authority_state::text,''))<>'CONFIRMED' or upper(coalesce(v_doc.lifecycle_state::text,''))<>'ACTIVE' then return null; end if;
  select * into v_link from portal_private.owner_deal_documents where document_key=v_doc.id and upper(coalesce(document_kind,'')) in ('SIGNED_ADDENDUM','SIGNED_SPECIFICATION','SIGNED_CONTRACT') order by updated_at desc limit 1; if not found then return null; end if;
  select * into v_deal from portal_private.deals where id=v_link.deal_key and upper(lifecycle_state::text)='ACTIVE'; if not found then return null; end if;
  if p_version_key is not null then select * into v_ver from portal_private.document_versions where id=p_version_key and document_key=v_doc.id; else select * into v_ver from portal_private.document_versions where id=v_doc.current_version_id and document_key=v_doc.id; end if;
  if not found or v_doc.current_version_id is distinct from v_ver.id or v_ver.is_current<>true or v_ver.is_effective<>true or upper(coalesce(v_ver.authority_state::text,''))<>'CONFIRMED' or upper(coalesce(v_ver.lifecycle_state::text,''))<>'ACTIVE' then return null; end if;
  insert into portal_private.finance_signed_schedule_jobs_v8(deal_key,source_document_key,source_document_version_key,source_document_id,status) values(v_deal.id,v_doc.id,v_ver.id,v_doc.document_id,'PENDING_FINANCE')
  on conflict(source_document_version_key) do update set status=case when portal_private.finance_signed_schedule_jobs_v8.status in ('MATERIALIZED','FINANCE_IN_PROGRESS','PENDING_OPERATIONS') then portal_private.finance_signed_schedule_jobs_v8.status else 'PENDING_FINANCE' end,updated_at=clock_timestamp() returning job_id into v_job_id;
  v_task_id:='TASK-FIN-SCHEDULE-V8-'||regexp_replace(upper(v_deal.deal_id),'[^A-Z0-9]+','','g')||'-'||upper(substr(replace(v_ver.id::text,'-',''),1,8));
  v_desc:=format('Canonical Finance V8 payment schedule. Source of truth: current confirmed bilateral signed document %s, Deal ID %s. Read the exact signed document and extract only contractual client receivable terms. Signed terms supersede application/offer/legacy plan. Submit BUSINESS_CHANGE_PROPOSAL with target TASK %s, proposed_action=MATERIALIZE_SIGNED_DOCUMENT_PAYMENT_SCHEDULE_V8, proposed_field=signed_document_payment_schedule, schema=FINANCE_SIGNED_DOCUMENT_PAYMENT_SCHEDULE_V8, deal_id=%s, source_document_id=%s, currency, total_to_receive, schedule_version, tranches[{tranche_no,amount,due_state,trigger_type,trigger_state,next_tranche_condition}]. Documentary/physical conditions not authoritatively fulfilled remain DEFERRED_NOT_DUE / NOT_CONFIRMED. Ambiguity => HOLD/TO_VERIFY; never guess. EXECUTOR BINDING: entity_type=TASK and entity_id exactly %s.',v_doc.document_id,v_deal.deal_id,v_task_id,v_deal.deal_id,v_doc.document_id,v_task_id);
  insert into portal_private.staff_tasks(task_id,title,description,status,priority,authority_domain,assigned_functional_role,client_key,contract_key,deal_key,source_type,source_object_id,source_version,source_hash,qa_only)
  values(v_task_id,'Finance V8 — canonical payment schedule '||v_deal.deal_id,v_desc,'NEW'::portal_private.staff_task_status_enum,'HIGH'::portal_private.staff_priority_enum,'FINANCE','FINANCE'::portal_private.staff_functional_role_enum,v_deal.client_key,v_deal.contract_key,v_deal.id,'SIGNED_DOCUMENT',v_doc.document_id,'FINANCE_SIGNED_DOCUMENT_PAYMENT_SCHEDULE_V8',v_ver.sha256,false)
  on conflict(task_id) do update set description=excluded.description,source_hash=excluded.source_hash,updated_at=clock_timestamp();
  update portal_private.finance_signed_schedule_jobs_v8 set staff_task_id=v_task_id,updated_at=clock_timestamp() where job_id=v_job_id; return v_job_id;
end;$function$;

create or replace function portal_private.enqueue_signed_document_finance_schedule_v8() returns trigger language plpgsql security definer set search_path to 'pg_catalog','portal_private' as $function$
begin if upper(coalesce(new.document_kind,'')) in ('SIGNED_ADDENDUM','SIGNED_SPECIFICATION','SIGNED_CONTRACT') then perform portal_private.ensure_signed_document_schedule_job_v8(new.document_key,null); end if; return new; end;$function$;
drop trigger if exists trg_signed_document_finance_schedule_v8 on portal_private.owner_deal_documents;
create trigger trg_signed_document_finance_schedule_v8 after insert on portal_private.owner_deal_documents for each row execute function portal_private.enqueue_signed_document_finance_schedule_v8();

create or replace function portal_private.trg_signed_document_current_pointer_schedule_v8() returns trigger language plpgsql security definer set search_path to 'pg_catalog','portal_private' as $function$
begin if upper(coalesce(new.document_type,'')) in ('SIGNED_ADDENDUM','SIGNED_SPECIFICATION','SIGNED_CONTRACT') and new.current_version_id is not null and upper(coalesce(new.authority_state::text,''))='CONFIRMED' and upper(coalesce(new.lifecycle_state::text,''))='ACTIVE' and (tg_op='INSERT' or old.current_version_id is distinct from new.current_version_id or old.authority_state is distinct from new.authority_state or old.lifecycle_state is distinct from new.lifecycle_state) then perform portal_private.ensure_signed_document_schedule_job_v8(new.id,new.current_version_id); end if; return new; end;$function$;
drop trigger if exists signed_document_current_pointer_schedule_v8 on portal_private.documents;
create trigger signed_document_current_pointer_schedule_v8 after insert or update of current_version_id,authority_state,lifecycle_state on portal_private.documents for each row execute function portal_private.trg_signed_document_current_pointer_schedule_v8();

create or replace function portal_private.trg_signed_document_version_schedule_v8() returns trigger language plpgsql security definer set search_path to 'pg_catalog','portal_private' as $function$
declare v_doc portal_private.documents%rowtype; begin if new.is_current=true and new.is_effective=true and upper(coalesce(new.authority_state::text,''))='CONFIRMED' and upper(coalesce(new.lifecycle_state::text,''))='ACTIVE' then select * into v_doc from portal_private.documents where id=new.document_key; if found and v_doc.current_version_id=new.id and upper(coalesce(v_doc.document_type,'')) in ('SIGNED_ADDENDUM','SIGNED_SPECIFICATION','SIGNED_CONTRACT') then perform portal_private.ensure_signed_document_schedule_job_v8(v_doc.id,new.id); end if; end if; return new; end;$function$;
drop trigger if exists signed_document_version_schedule_v8 on portal_private.document_versions;
create trigger signed_document_version_schedule_v8 after insert or update of is_current,is_effective,authority_state,lifecycle_state on portal_private.document_versions for each row execute function portal_private.trg_signed_document_version_schedule_v8();

create or replace function portal_private.trg_signed_document_review_schedule_v8() returns trigger language plpgsql security definer set search_path to 'pg_catalog','portal_private' as $function$
begin if upper(coalesce(new.document_kind,'')) in ('SIGNED_ADDENDUM','SIGNED_SPECIFICATION','SIGNED_CONTRACT') and new.checked_by_admin=true and (tg_op='INSERT' or old.checked_by_admin is distinct from true or old.document_key is distinct from new.document_key) then perform portal_private.ensure_signed_document_schedule_job_v8(new.document_key,null); end if; return new; end;$function$;
drop trigger if exists signed_document_review_schedule_v8 on portal_private.owner_deal_documents;
create trigger signed_document_review_schedule_v8 after insert or update of checked_by_admin,document_key on portal_private.owner_deal_documents for each row execute function portal_private.trg_signed_document_review_schedule_v8();

create or replace function portal_private.materialize_signed_document_payment_schedule_v8(p_approval_record_id uuid)
returns jsonb language plpgsql security definer set search_path to 'pg_catalog','portal_private' as $function$
declare ap portal_private.ai_coordination_records%rowtype; pr portal_private.ai_coordination_records%rowtype; v_proposal_id uuid; s jsonb; d portal_private.deals%rowtype; doc portal_private.documents%rowtype; dv portal_private.document_versions%rowtype; j portal_private.finance_signed_schedule_jobs_v8%rowtype; cur portal_private.deal_finance_authority_v7%rowtype; v_current_count int:=0; v_group uuid:=gen_random_uuid(); v_total numeric; v_currency text; v_version text; v_tranches jsonb; t jsonb; v_no int; v_amount numeric; v_sum numeric:=0; v_seen int[]:='{}'; v_due_state text; v_trigger_type text; v_trigger_state text; v_condition text; v_received numeric:=0; v_received_left numeric:=0; v_rem numeric; v_due numeric:=0; v_expected numeric:=0; v_cond numeric:=0; v_status text; v_doc_status text; v_id uuid:=gen_random_uuid(); v_supersedes uuid; v_refs jsonb; v_idem text; v_spend numeric; v_spend_status text; v_remaining_exec numeric; v_remaining_exec_status text; v_exec_currency char(3); v_exec_status text; v_mixed char(3); v_contract_currency char(3); v_result jsonb; v_error text;
begin
  select * into ap from portal_private.ai_coordination_records where record_id=p_approval_record_id;
  if not found or ap.record_type<>'OPERATIONS_INTERNAL_DECISION' or ap.functional_role::text<>'OPERATIONS_DIRECTOR' or coalesce(ap.identity_id,'')<>'AI-OPERATIONS-DIRECTOR' or coalesce(ap.qa_only,false)=true or ap.status<>'APPROVE_FOR_NEXT_STAGE' then return jsonb_build_object('accepted',false,'materialized',false,'reason_code','OPERATIONS_APPROVAL_INVALID'); end if;
  begin v_proposal_id:=coalesce(nullif(ap.payload->>'record_id','')::uuid,ap.parent_record_id); exception when others then return jsonb_build_object('accepted',false,'materialized',false,'reason_code','FINANCE_PROPOSAL_ID_INVALID'); end;
  select * into pr from portal_private.ai_coordination_records where record_id=v_proposal_id;
  if not found or pr.record_type<>'BUSINESS_CHANGE_PROPOSAL' or pr.functional_role::text<>'FINANCE' or coalesce(pr.identity_id,'')<>'AI-FINANCE' or coalesce(pr.tool_name,'')<>'business_change_proposal_submit' or coalesce(pr.qa_only,false)=true or pr.status<>'PROPOSED' or ap.parent_record_id is distinct from pr.record_id then return jsonb_build_object('accepted',false,'materialized',false,'reason_code','FINANCE_PROPOSAL_INVALID'); end if;
  if upper(coalesce(pr.payload->>'proposed_action',''))<>'MATERIALIZE_SIGNED_DOCUMENT_PAYMENT_SCHEDULE_V8' or lower(coalesce(pr.payload->>'proposed_field',''))<>'signed_document_payment_schedule' then return jsonb_build_object('accepted',false,'materialized',false,'reason_code','SIGNED_SCHEDULE_CONTRACT_INVALID'); end if;
  s:=coalesce(pr.payload->'proposed_state',pr.payload->'proposed_value'); if jsonb_typeof(s)='string' then begin s:=(s#>>'{}')::jsonb; exception when others then return jsonb_build_object('accepted',false,'materialized',false,'reason_code','SIGNED_SCHEDULE_STATE_JSON_INVALID'); end; end if;
  if jsonb_typeof(s)<>'object' or upper(coalesce(s->>'schema',''))<>'FINANCE_SIGNED_DOCUMENT_PAYMENT_SCHEDULE_V8' then return jsonb_build_object('accepted',false,'materialized',false,'reason_code','SIGNED_SCHEDULE_STATE_INVALID'); end if;
  select * into d from portal_private.deals where deal_id=s->>'deal_id' and upper(lifecycle_state::text)='ACTIVE' order by updated_at desc limit 1; if not found then return jsonb_build_object('accepted',false,'materialized',false,'reason_code','DEAL_NOT_FOUND'); end if;
  select * into doc from portal_private.documents where document_id=s->>'source_document_id' and deal_key=d.id and upper(document_type) in ('SIGNED_ADDENDUM','SIGNED_SPECIFICATION','SIGNED_CONTRACT') and upper(authority_state::text)='CONFIRMED' and upper(lifecycle_state::text)='ACTIVE' order by updated_at desc limit 1; if not found or doc.current_version_id is null then return jsonb_build_object('accepted',false,'materialized',false,'reason_code','CURRENT_SIGNED_DOCUMENT_NOT_FOUND'); end if;
  select * into dv from portal_private.document_versions where id=doc.current_version_id and document_key=doc.id; if not found or dv.is_current<>true or dv.is_effective<>true or upper(dv.authority_state::text)<>'CONFIRMED' or upper(dv.lifecycle_state::text)<>'ACTIVE' then return jsonb_build_object('accepted',false,'materialized',false,'reason_code','SIGNED_DOCUMENT_VERSION_NOT_EFFECTIVE'); end if;
  perform pg_advisory_xact_lock(hashtext('signed-payment-schedule-v8:'||dv.id::text)); select * into j from portal_private.finance_signed_schedule_jobs_v8 where source_document_version_key=dv.id for update;
  if not found then insert into portal_private.finance_signed_schedule_jobs_v8(deal_key,source_document_key,source_document_version_key,source_document_id,status,proposal_record_id,approval_record_id,attempt_count) values(d.id,doc.id,dv.id,doc.document_id,'FINANCE_IN_PROGRESS',pr.record_id,ap.record_id,1) returning * into j; elsif j.status='MATERIALIZED' and j.proposal_record_id=pr.record_id then return coalesce(j.result_snapshot,'{}'::jsonb)||jsonb_build_object('idempotent_replay',true,'job_id',j.job_id); else update portal_private.finance_signed_schedule_jobs_v8 set proposal_record_id=pr.record_id,approval_record_id=ap.record_id,status='FINANCE_IN_PROGRESS',attempt_count=attempt_count+1,last_error=null,updated_at=clock_timestamp() where job_id=j.job_id returning * into j; end if;
  begin
    v_currency:=upper(btrim(coalesce(s->>'currency',''))); if v_currency!~'^[A-Z]{3}$' then raise exception 'SIGNED_SCHEDULE_CURRENCY_INVALID'; end if; if jsonb_typeof(s->'total_to_receive')<>'number' then raise exception 'SIGNED_SCHEDULE_TOTAL_REQUIRED'; end if; v_total:=(s->>'total_to_receive')::numeric; if v_total<=0 then raise exception 'SIGNED_SCHEDULE_TOTAL_INVALID'; end if;
    v_version:=coalesce(nullif(btrim(s->>'schedule_version'),''),'SIGNED_DOC:'||doc.document_id||':V'||dv.version_number::text); v_tranches:=s->'tranches'; if jsonb_typeof(v_tranches)<>'array' or jsonb_array_length(v_tranches)=0 then raise exception 'SIGNED_SCHEDULE_TRANCHES_REQUIRED'; end if;
    for t in select value from jsonb_array_elements(v_tranches) x(value) loop if jsonb_typeof(t->'tranche_no')<>'number' or jsonb_typeof(t->'amount')<>'number' then raise exception 'SIGNED_SCHEDULE_TRANCHE_FIELDS_REQUIRED'; end if; v_no:=(t->>'tranche_no')::int; v_amount:=(t->>'amount')::numeric; v_due_state:=upper(coalesce(t->>'due_state','')); v_trigger_type:=nullif(btrim(coalesce(t->>'trigger_type','')),''); v_trigger_state:=upper(coalesce(t->>'trigger_state','NOT_APPLICABLE')); if v_no<=0 or v_no=any(v_seen) or v_amount<0 then raise exception 'SIGNED_SCHEDULE_TRANCHE_INVALID'; end if; v_seen:=array_append(v_seen,v_no); if v_due_state not in ('CURRENT_DUE','DEFERRED_NOT_DUE','NOT_APPLICABLE') or v_trigger_state not in ('CONFIRMED','NOT_CONFIRMED','NOT_APPLICABLE') then raise exception 'SIGNED_SCHEDULE_TRANCHE_STATE_INVALID'; end if; if v_trigger_type is not null and v_trigger_state='NOT_CONFIRMED' and v_due_state<>'DEFERRED_NOT_DUE' then raise exception 'UNCONFIRMED_TRIGGER_CANNOT_BE_DUE'; end if; if v_trigger_state='CONFIRMED' and v_due_state<>'CURRENT_DUE' then raise exception 'CONFIRMED_TRIGGER_MUST_BE_DUE'; end if; v_sum:=v_sum+v_amount; end loop; if abs(v_sum-v_total)>0.01 then raise exception 'SIGNED_SCHEDULE_TRANCHES_TOTAL_MISMATCH'; end if;
    select count(*) into v_current_count from portal_private.deal_finance_authority_v7 a where a.deal_key=d.id and a.source_locked=true and upper(a.authority_state) not in ('SUPERSEDED','REJECTED','REVERSED','INVALID','INACTIVE') and upper(a.lifecycle_state) not in ('SUPERSEDED','REJECTED','REVERSED','ARCHIVED','INACTIVE') and not exists(select 1 from portal_private.deal_finance_authority_v7 n where n.supersedes_id=a.id and n.source_locked=true and upper(n.authority_state) not in ('SUPERSEDED','REJECTED','REVERSED','INVALID','INACTIVE') and upper(n.lifecycle_state) not in ('SUPERSEDED','REJECTED','REVERSED','ARCHIVED','INACTIVE')); if v_current_count>1 then raise exception 'MULTIPLE_CURRENT_FINANCE_AUTHORITIES'; end if;
    if v_current_count=1 then select * into cur from portal_private.deal_finance_authority_v7 a where a.deal_key=d.id and a.source_locked=true and upper(a.authority_state) not in ('SUPERSEDED','REJECTED','REVERSED','INVALID','INACTIVE') and upper(a.lifecycle_state) not in ('SUPERSEDED','REJECTED','REVERSED','ARCHIVED','INACTIVE') and not exists(select 1 from portal_private.deal_finance_authority_v7 n where n.supersedes_id=a.id and n.source_locked=true and upper(n.authority_state) not in ('SUPERSEDED','REJECTED','REVERSED','INVALID','INACTIVE') and upper(n.lifecycle_state) not in ('SUPERSEDED','REJECTED','REVERSED','ARCHIVED','INACTIVE')) limit 1; v_received:=greatest(0,cur.total_to_receive-(cur.due_now+cur.expected_not_due+cur.future_conditional)); if v_received>v_total+0.01 then raise exception 'RECOGNIZED_RECEIPT_EXCEEDS_SIGNED_OBLIGATION'; end if; v_spend:=cur.actual_spend; v_spend_status:=cur.actual_spend_status; v_remaining_exec:=cur.remaining_execution; v_remaining_exec_status:=cur.remaining_execution_status; v_exec_currency:=cur.execution_currency; v_exec_status:=cur.execution_status; v_supersedes:=cur.id; v_mixed:=cur.mixed_inbound_accounting_currency; v_contract_currency:=coalesce(cur.contractual_payment_currency,v_currency::char(3)); v_doc_status:=cur.documentary_status; else v_received:=0; v_spend:=0; v_spend_status:='AUTHORITATIVE'; v_remaining_exec:=0; v_remaining_exec_status:='AUTHORITATIVE'; v_exec_currency:=v_currency::char(3); v_exec_status:='CONFIRMED_ZERO_RECEIPT_PENDING'; v_supersedes:=null; v_mixed:=null; v_contract_currency:=v_currency::char(3); v_doc_status:='TO_VERIFY'; end if;
    update portal_private.owner_payment_plan set schedule_authority_state='SUPERSEDED',status='CANCELLED',updated_at=clock_timestamp() where deal_key=d.id and status<>'CANCELLED'; v_received_left:=v_received;
    for t in select value from jsonb_array_elements(v_tranches) x(value) order by (value->>'tranche_no')::int loop v_no:=(t->>'tranche_no')::int; v_amount:=(t->>'amount')::numeric; v_due_state:=upper(t->>'due_state'); v_trigger_type:=nullif(btrim(coalesce(t->>'trigger_type','')),''); v_trigger_state:=upper(coalesce(t->>'trigger_state','NOT_APPLICABLE')); v_condition:=nullif(btrim(coalesce(t->>'next_tranche_condition',t->>'condition','')),''); v_rem:=greatest(0,v_amount-least(v_amount,v_received_left)); v_received_left:=greatest(0,v_received_left-v_amount); if v_rem>0 then if v_due_state='CURRENT_DUE' then v_due:=v_due+v_rem; elsif v_due_state='DEFERRED_NOT_DUE' and v_trigger_type is not null and v_trigger_state='NOT_CONFIRMED' then v_cond:=v_cond+v_rem; elsif v_due_state='DEFERRED_NOT_DUE' then v_expected:=v_expected+v_rem; end if; end if; insert into portal_private.owner_payment_plan(deal_key,tranche_no,share_text,planned_amount,currency,due_at,status,source_system,schedule_authority_state,due_state,trigger_type,trigger_state,next_tranche_condition,schedule_version,schedule_group_id,proposal_record_id,operations_decision_id,source_document_key,source_document_version_key,source_refs,source_timestamp,materialized_at,materialized_by) values(d.id,v_no,coalesce(v_condition,'Signed document tranche '||v_no),v_amount,v_currency::char(3),null,'EXPECTED','FINANCE_SIGNED_DOCUMENT_PAYMENT_SCHEDULE_V8','CONFIRMED',v_due_state,v_trigger_type,v_trigger_state,v_condition,v_version,v_group,pr.record_id,ap.record_id,doc.id,dv.id,jsonb_build_array(jsonb_build_object('source_type','DOCUMENT','source_id',doc.document_id),jsonb_build_object('source_type','DOCUMENT_VERSION','source_id',dv.id::text),jsonb_build_object('source_type','BUSINESS_CHANGE_PROPOSAL','source_id',pr.record_id::text),jsonb_build_object('source_type','OPERATIONS_DECISION','source_id',ap.record_id::text)),dv.source_timestamp,clock_timestamp(),'SERVER_V8'); end loop;
    if abs((v_due+v_expected+v_cond)-(v_total-v_received))>0.01 then raise exception 'SIGNED_SCHEDULE_NET_BUCKET_INTEGRITY_ERROR'; end if; v_status:=case when v_total-v_received<=0.01 then 'PAID' when v_received>0 then 'PARTIAL' when v_due>0 then 'DUE' else 'NOT_DUE' end; if v_cond>0 and upper(coalesce(v_doc_status,'')) not like 'BANK_%' then v_doc_status:='TO_VERIFY'; end if;
    v_refs:=jsonb_build_array(jsonb_build_object('source_type','DOCUMENT','source_id',doc.document_id),jsonb_build_object('source_type','DOCUMENT_VERSION','source_id',dv.id::text),jsonb_build_object('source_type','PAYMENT_SCHEDULE','source_id',v_group::text),jsonb_build_object('source_type','BUSINESS_CHANGE_PROPOSAL','source_id',pr.record_id::text),jsonb_build_object('source_type','OPERATIONS_DECISION','source_id',ap.record_id::text),jsonb_build_object('source_type','GLOBAL_ROLE_POLICY','source_id','FINANCE_CANONICAL_PAYMENT_SCHEDULE_POLICY_V1')); v_idem:='signed-schedule-v8:'||pr.record_id::text;
    insert into portal_private.deal_finance_authority_v7(id,deal_key,total_to_receive,due_now,expected_not_due,future_conditional,obligation_currency,contractual_payment_currency,mixed_inbound_accounting_currency,finance_status,documentary_status,authority_state,lifecycle_state,effective_at,supersedes_id,supersedes_authority_refs,source_version,source_timestamp,source_refs,source_locked,actor_id,actor_role,correlation_id,idempotency_key,actual_spend,actual_spend_status,remaining_execution,remaining_execution_status,execution_currency,execution_status) values(v_id,d.id,v_total,v_due,v_expected,v_cond,v_currency::char(3),v_contract_currency,v_mixed,v_status,v_doc_status,'AUTHORITATIVE','CURRENT',ap.created_at,v_supersedes,case when v_supersedes is null then '[]'::jsonb else jsonb_build_array(jsonb_build_object('source_type','FINANCE_AUTHORITY','source_id',v_supersedes::text)) end,'FINANCE_SIGNED_SCHEDULE_V8:'||v_version,dv.source_timestamp,v_refs,true,'AI-FINANCE','FINANCE',coalesce(pr.correlation_id,ap.correlation_id,gen_random_uuid()),v_idem,v_spend,v_spend_status,v_remaining_exec,v_remaining_exec_status,v_exec_currency,v_exec_status);
    v_result:=jsonb_build_object('accepted',true,'materialized',true,'deal_id',d.deal_id,'source_document_id',doc.document_id,'schedule_group_id',v_group,'authority_id',v_id,'recognized_received',v_received,'due_now',v_due,'expected_not_due',v_expected,'future_conditional',v_cond,'remaining_to_receive',v_total-v_received,'proposal_record_id',pr.record_id,'approval_record_id',ap.record_id,'projection_refresh_required',true,'job_id',j.job_id); update portal_private.finance_signed_schedule_jobs_v8 set status='MATERIALIZED',schedule_group_id=v_group,proposal_record_id=pr.record_id,approval_record_id=ap.record_id,result_snapshot=v_result,last_error=null,updated_at=clock_timestamp() where job_id=j.job_id; return v_result;
  exception when others then v_error:=left(sqlerrm,1000); update portal_private.finance_signed_schedule_jobs_v8 set status='RETRY',proposal_record_id=pr.record_id,approval_record_id=ap.record_id,last_error=v_error,result_snapshot=jsonb_build_object('accepted',false,'materialized',false,'reason_code','SIGNED_SCHEDULE_EXECUTION_ERROR','error',v_error),updated_at=clock_timestamp() where job_id=j.job_id; return jsonb_build_object('accepted',false,'materialized',false,'reason_code','SIGNED_SCHEDULE_EXECUTION_ERROR','error',v_error,'job_id',j.job_id); end;
end;$function$;

create or replace function portal_private.auto_materialize_signed_document_payment_schedule_v8() returns trigger language plpgsql security definer set search_path to 'pg_catalog','portal_private' as $function$
begin if new.record_type='OPERATIONS_INTERNAL_DECISION' and new.functional_role::text='OPERATIONS_DIRECTOR' and new.status='APPROVE_FOR_NEXT_STAGE' and upper(coalesce(new.payload->>'action',''))='APPROVE_FOR_NEXT_STAGE' then perform portal_private.materialize_signed_document_payment_schedule_v8(new.record_id); end if; return new; end;$function$;
drop trigger if exists finance_auto_materialize_signed_schedule_v8 on portal_private.ai_coordination_records;
create trigger finance_auto_materialize_signed_schedule_v8 after insert on portal_private.ai_coordination_records for each row execute function portal_private.auto_materialize_signed_document_payment_schedule_v8();

create or replace function portal_private.auto_gate_finance_signed_schedule_v8() returns trigger language plpgsql security definer set search_path to 'pg_catalog','portal_private','extensions' as $function$
declare s jsonb; j portal_private.finance_signed_schedule_jobs_v8%rowtype; st portal_private.staff_tasks%rowtype; doc portal_private.documents%rowtype; dv portal_private.document_versions%rowtype; v_idem text; v_hash text; v_payload jsonb; v_gate uuid; v_shadow uuid;
begin
  if new.record_type<>'BUSINESS_CHANGE_PROPOSAL' or new.functional_role::text<>'FINANCE' or coalesce(new.identity_id,'')<>'AI-FINANCE' or coalesce(new.qa_only,false)=true or new.status<>'PROPOSED' or upper(coalesce(new.payload->>'proposed_action',''))<>'MATERIALIZE_SIGNED_DOCUMENT_PAYMENT_SCHEDULE_V8' or lower(coalesce(new.payload->>'proposed_field',''))<>'signed_document_payment_schedule' then return new; end if;
  if coalesce(new.tool_name,'')='ai_model_executor_business_change_proposal' then v_idem:=encode(extensions.digest(convert_to('V8_CANONICAL_PROPOSAL|'||new.record_id::text,'UTF8'),'sha256'),'hex'); select record_id into v_shadow from portal_private.ai_coordination_records where identity_id='AI-FINANCE' and tool_name='business_change_proposal_submit' and idempotency_key_hash=v_idem limit 1; if v_shadow is null then v_payload:=new.payload||jsonb_build_object('normalized_from_executor_record_id',new.record_id,'normalization_contract','FINANCE_SIGNED_DOCUMENT_PAYMENT_SCHEDULE_V8','owner_policy_id','FINANCE_CANONICAL_PAYMENT_SCHEDULE_POLICY_V1'); v_hash:=encode(extensions.digest(convert_to(v_payload::text,'UTF8'),'sha256'),'hex'); insert into portal_private.ai_coordination_records(record_type,functional_role,identity_id,client_id,server_slug,tool_name,target_type,target_id,target_role,parent_record_id,version,idempotency_key_hash,payload_hash,source_refs,evidence_refs,payload,status,correlation_id,mcp_request_id,qa_only) values('BUSINESS_CHANGE_PROPOSAL','FINANCE'::portal_private.ai_business_role_enum,'AI-FINANCE','SERVER_POLICY_GATE','payments-v8-owner-policy','business_change_proposal_submit',new.target_type,new.target_id,'OPERATIONS_DIRECTOR'::portal_private.ai_business_role_enum,new.record_id,1,v_idem,v_hash,coalesce(new.source_refs,'[]'::jsonb)||jsonb_build_array('AI_COORDINATION:'||new.record_id::text,'OWNER_POLICY:FINANCE_CANONICAL_PAYMENT_SCHEDULE_POLICY_V1'),coalesce(new.evidence_refs,'[]'::jsonb),v_payload,'PROPOSED',new.correlation_id,gen_random_uuid(),false); end if; return new; end if;
  if coalesce(new.tool_name,'')<>'business_change_proposal_submit' or new.target_type<>'TASK' or new.target_id not like 'TASK-FIN-SCHEDULE-V8-%' then return new; end if;
  if not exists(select 1 from portal_private.ai_role_global_policies_v1 p where p.policy_id='FINANCE_CANONICAL_PAYMENT_SCHEDULE_POLICY_V1' and p.authority_kind='OWNER_INSTRUCTION' and not exists(select 1 from portal_private.ai_role_global_policies_v1 x where x.supersedes_policy_id=p.policy_id)) then return new; end if;
  select * into st from portal_private.staff_tasks where task_id=new.target_id; if not found or st.source_type<>'SIGNED_DOCUMENT' then return new; end if; select * into j from portal_private.finance_signed_schedule_jobs_v8 where staff_task_id=st.task_id for update; if not found or j.status='MATERIALIZED' then return new; end if;
  s:=coalesce(new.payload->'proposed_state',new.payload->'proposed_value'); if jsonb_typeof(s)='string' then begin s:=(s#>>'{}')::jsonb; exception when others then update portal_private.finance_signed_schedule_jobs_v8 set status='TO_VERIFY',last_error='V8_STATE_JSON_INVALID',updated_at=clock_timestamp() where job_id=j.job_id; return new; end; end if; if jsonb_typeof(s)<>'object' or upper(coalesce(s->>'schema',''))<>'FINANCE_SIGNED_DOCUMENT_PAYMENT_SCHEDULE_V8' then update portal_private.finance_signed_schedule_jobs_v8 set status='TO_VERIFY',last_error='V8_STATE_INVALID',updated_at=clock_timestamp() where job_id=j.job_id; return new; end if;
  select * into doc from portal_private.documents where id=j.source_document_key and document_id=s->>'source_document_id' and deal_key=j.deal_key and upper(authority_state::text)='CONFIRMED' and upper(lifecycle_state::text)='ACTIVE'; if not found or doc.current_version_id is distinct from j.source_document_version_key then update portal_private.finance_signed_schedule_jobs_v8 set status='TO_VERIFY',last_error='V8_SIGNED_DOCUMENT_BINDING_INVALID',updated_at=clock_timestamp() where job_id=j.job_id; return new; end if; select * into dv from portal_private.document_versions where id=j.source_document_version_key and document_key=doc.id and is_current=true and is_effective=true; if not found then update portal_private.finance_signed_schedule_jobs_v8 set status='TO_VERIFY',last_error='V8_SIGNED_VERSION_INVALID',updated_at=clock_timestamp() where job_id=j.job_id; return new; end if;
  v_idem:=encode(extensions.digest(convert_to('V8_OWNER_POLICY_APPROVAL|'||new.record_id::text,'UTF8'),'sha256'),'hex'); select record_id into v_gate from portal_private.ai_coordination_records where identity_id='AI-OPERATIONS-DIRECTOR' and tool_name='operations_internal_decision' and idempotency_key_hash=v_idem limit 1;
  if v_gate is null then v_payload:=jsonb_build_object('action','APPROVE_FOR_NEXT_STAGE','record_id',new.record_id,'note','Deterministic Owner-policy gate for a Finance V8 signed-document schedule.','owner_policy_id','FINANCE_CANONICAL_PAYMENT_SCHEDULE_POLICY_V1','automated_policy_gate',true,'semantic_owner','FINANCE','payments_role','DISPLAY_ONLY'); v_hash:=encode(extensions.digest(convert_to(v_payload::text,'UTF8'),'sha256'),'hex'); insert into portal_private.ai_coordination_records(record_type,functional_role,identity_id,client_id,server_slug,tool_name,target_type,target_id,target_role,parent_record_id,version,idempotency_key_hash,payload_hash,source_refs,evidence_refs,payload,status,correlation_id,mcp_request_id,qa_only) values('OPERATIONS_INTERNAL_DECISION','OPERATIONS_DIRECTOR'::portal_private.ai_business_role_enum,'AI-OPERATIONS-DIRECTOR','SERVER_POLICY_GATE','payments-v8-owner-policy','operations_internal_decision',new.target_type,new.target_id,'FINANCE'::portal_private.ai_business_role_enum,new.record_id,1,v_idem,v_hash,coalesce(new.source_refs,'[]'::jsonb)||jsonb_build_array('BUSINESS_CHANGE_PROPOSAL:'||new.record_id::text,'OWNER_POLICY:FINANCE_CANONICAL_PAYMENT_SCHEDULE_POLICY_V1'),jsonb_build_array('DOCUMENT:'||doc.document_id,'DOCUMENT_VERSION:'||dv.id::text),v_payload,'APPROVE_FOR_NEXT_STAGE',new.correlation_id,gen_random_uuid(),false) returning record_id into v_gate; end if;
  update portal_private.finance_signed_schedule_jobs_v8 set status=case when status='MATERIALIZED' then status else 'PENDING_OPERATIONS' end,proposal_record_id=new.record_id,approval_record_id=v_gate,updated_at=clock_timestamp() where job_id=j.job_id; return new;
end;$function$;
drop trigger if exists finance_v8_owner_policy_auto_gate on portal_private.ai_coordination_records;
create trigger finance_v8_owner_policy_auto_gate after insert on portal_private.ai_coordination_records for each row execute function portal_private.auto_gate_finance_signed_schedule_v8();

create or replace function portal_private.handle_finance_signed_schedule_hold_v8() returns trigger language plpgsql security definer set search_path to 'pg_catalog','portal_private' as $function$
declare j portal_private.finance_signed_schedule_jobs_v8%rowtype; v_reason text; begin if new.record_type<>'FUNCTIONAL_CONCLUSION' or new.functional_role::text<>'FINANCE' or coalesce(new.identity_id,'')<>'AI-FINANCE' or coalesce(new.qa_only,false)=true or new.target_type<>'TASK' or new.target_id not like 'TASK-FIN-SCHEDULE-V8-%' or upper(coalesce(new.status,'')) not in ('HOLD','REJECTED') then return new; end if; select * into j from portal_private.finance_signed_schedule_jobs_v8 where staff_task_id=new.target_id for update; if not found or j.status='MATERIALIZED' then return new; end if; v_reason:=left(coalesce(nullif(new.payload->>'summary',''),nullif(new.payload->>'recommendation',''),new.status),1000); update portal_private.finance_signed_schedule_jobs_v8 set status='TO_VERIFY',last_error='FINANCE_'||upper(new.status)||': '||v_reason,updated_at=clock_timestamp() where job_id=j.job_id; update portal_private.staff_tasks set status=case when upper(new.status)='REJECTED' then 'REJECTED'::portal_private.staff_task_status_enum else 'WAITING'::portal_private.staff_task_status_enum end,decision='FINANCE_'||upper(new.status)||': '||v_reason,decision_at=clock_timestamp(),updated_at=clock_timestamp() where task_id=new.target_id; insert into portal_private.finance_schedule_integrity_alerts_v8(deal_key,source_document_version_key,reason_code,details,status) values(j.deal_key,j.source_document_version_key,case when upper(new.status)='REJECTED' then 'FINANCE_SIGNED_SCHEDULE_REJECTED' else 'FINANCE_SIGNED_SCHEDULE_HOLD' end,jsonb_build_object('functional_conclusion_id',new.record_id,'task_id',new.target_id,'summary',v_reason),'OPEN') on conflict(deal_key,reason_code) where status='OPEN' do update set details=excluded.details,created_at=clock_timestamp(); return new; end;$function$;
drop trigger if exists finance_v8_hold_handler on portal_private.ai_coordination_records;
create trigger finance_v8_hold_handler after insert on portal_private.ai_coordination_records for each row execute function portal_private.handle_finance_signed_schedule_hold_v8();

create or replace function portal_private.guard_finance_signed_schedule_job_status_v8() returns trigger language plpgsql set search_path to 'pg_catalog','portal_private' as $function$ begin if new.status='PENDING_OPERATIONS' and old.status in ('RETRY','TO_VERIFY','ERROR') then new.status:=old.status; end if; return new; end;$function$;
drop trigger if exists finance_signed_schedule_job_status_guard_v8 on portal_private.finance_signed_schedule_jobs_v8;
create trigger finance_signed_schedule_job_status_guard_v8 before update of status on portal_private.finance_signed_schedule_jobs_v8 for each row execute function portal_private.guard_finance_signed_schedule_job_status_v8();

create or replace function portal_private.settle_finance_signed_schedule_task_v8() returns trigger language plpgsql security definer set search_path to 'pg_catalog','portal_private' as $function$
begin if new.staff_task_id is null then return new; end if; if new.status='MATERIALIZED' then update portal_private.staff_tasks set status='COMPLETED'::portal_private.staff_task_status_enum,decision='FINANCE_SIGNED_DOCUMENT_PAYMENT_SCHEDULE_V8 materialized',decision_at=coalesce(decision_at,clock_timestamp()),updated_at=clock_timestamp() where task_id=new.staff_task_id and status::text not in ('COMPLETED','CLOSED'); update portal_private.ai_runtime_queue set state='PROCESSED',processed_at=coalesce(processed_at,clock_timestamp()),lease_until=null,claimed_by=null,last_error_code=null,last_error_text=null,updated_at=clock_timestamp() where source_type='STAFF_TASK' and source_id=new.staff_task_id and target_role::text='FINANCE' and state<>'PROCESSED'; update portal_private.finance_schedule_integrity_alerts_v8 set status='RESOLVED',resolved_at=clock_timestamp() where deal_key=new.deal_key and status='OPEN'; elsif new.status='TO_VERIFY' then update portal_private.staff_tasks set status='WAITING'::portal_private.staff_task_status_enum,updated_at=clock_timestamp() where task_id=new.staff_task_id and status::text not in ('REJECTED','COMPLETED','CLOSED'); elsif new.status='SUPERSEDED' then update portal_private.staff_tasks set status='CLOSED'::portal_private.staff_task_status_enum,decision=coalesce(decision,'Superseded by a newer signed document version'),decision_at=coalesce(decision_at,clock_timestamp()),updated_at=clock_timestamp() where task_id=new.staff_task_id and status::text not in ('COMPLETED','CLOSED'); end if; return new; end;$function$;
drop trigger if exists finance_signed_schedule_job_task_settlement_v8 on portal_private.finance_signed_schedule_jobs_v8;
create trigger finance_signed_schedule_job_task_settlement_v8 after insert or update of status on portal_private.finance_signed_schedule_jobs_v8 for each row execute function portal_private.settle_finance_signed_schedule_task_v8();
