-- Reconcile only payment-plan rows generated by the corrective handoff fallback.
-- Existing finance-owned/canonical plan rows are never replaced.

create or replace function portal_private.owner_r1_reconcile_generated_payment_plan(p_deal_id text)
returns boolean
language plpgsql
security definer
set search_path to 'pg_catalog','public','portal_private','auth'
as $$
declare
  v_deal uuid;
  v_payment_terms text;
  v_handoff_at timestamptz;
  v_obligation numeric;
  v_received numeric;
  v_currency text;
  v_total_rows integer;
  v_generated_rows integer;
  v_shares text[];
  v_share1 numeric;
  v_share2 numeric;
  v_tranche1 numeric;
  v_tranche2 numeric;
  v_terms1 text;
  v_terms2 text;
  v_status1 text;
  v_status2 text;
begin
  select d.id,ca.payment_terms,w.payment_handoff_at,
         fs.obligation_amount,fs.received_amount,btrim(fs.currency)
    into v_deal,v_payment_terms,v_handoff_at,v_obligation,v_received,v_currency
    from portal_private.deals d
    join portal_private.deal_registrations dr on dr.deal_key=d.id
    join portal_private.client_applications ca on ca.id=dr.application_key
    join portal_private.owner_deal_workflow w on w.deal_key=d.id
    join portal_private.owner_deal_finance_summary fs on fs.deal_id=d.deal_id
   where d.deal_id=p_deal_id
     and fs.authority_state='CONFIRMED'
     and fs.lifecycle_state='ACTIVE'
   order by dr.registered_at desc
   limit 1;

  if v_deal is null or v_obligation is null or v_obligation<0
     or v_received is null or v_received<0
     or coalesce(v_currency,'')!~'^[A-Z]{3}$' then
    return false;
  end if;

  select count(*),
         count(*) filter(where source_system='ADMIN_DEAL_HANDOFF_R1')
    into v_total_rows,v_generated_rows
    from portal_private.owner_payment_plan
   where deal_key=v_deal;

  -- Only our single-row fallback is eligible for reconciliation.
  if v_total_rows<>1 or v_generated_rows<>1 then
    return false;
  end if;

  select array_agg(m[1])
    into v_shares
    from regexp_matches(coalesce(v_payment_terms,''),'([0-9]+([.,][0-9]+)?)\s*%','g') as m;

  if coalesce(cardinality(v_shares),0)<>2 then
    return false;
  end if;

  v_share1:=replace(v_shares[1],',','.')::numeric;
  v_share2:=replace(v_shares[2],',','.')::numeric;
  if v_share1<=0 or v_share2<=0 or abs((v_share1+v_share2)-100)>=0.0001 then
    return false;
  end if;

  v_tranche1:=round(v_obligation*v_share1/100,2);
  v_tranche2:=v_obligation-v_tranche1;
  v_terms1:=btrim(split_part(v_payment_terms,';',1));
  v_terms2:=btrim(regexp_replace(v_payment_terms,'^[^;]*;\s*',''));
  if v_terms2='' then v_terms2:=v_payment_terms; end if;

  v_status1:=case when v_received<=0 then 'EXPECTED' when v_received>=v_tranche1 then 'RECEIVED' else 'PARTIAL' end;
  v_status2:=case when v_received<=v_tranche1 then 'EXPECTED' when v_received>=v_obligation then 'RECEIVED' else 'PARTIAL' end;

  delete from portal_private.owner_payment_plan
   where deal_key=v_deal and source_system='ADMIN_DEAL_HANDOFF_R1';

  insert into portal_private.owner_payment_plan(
    deal_key,tranche_no,share_text,planned_amount,currency,due_at,status,source_system
  ) values
    (v_deal,1,v_terms1,v_tranche1,v_currency,
     case when lower(coalesce(v_payment_terms,''))~'(предвар|deposit|prepay)' then coalesce(v_handoff_at,now()) else null end,
     v_status1,'ADMIN_DEAL_ACCEPTED_TERMS_R1'),
    (v_deal,2,v_terms2,v_tranche2,v_currency,null,v_status2,'ADMIN_DEAL_ACCEPTED_TERMS_R1')
  on conflict(deal_key,tranche_no) do nothing;

  return true;
end
$$;

revoke all on function portal_private.owner_r1_reconcile_generated_payment_plan(text) from public;

create or replace function public.owner_r1_send_to_payments(p_deal_id text)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public','portal_private','auth'
as $$
declare
  v_actor uuid;
  v_deal uuid;
  v_prod timestamptz;
  v_qty timestamptz;
  v_cancel text;
  v_handoff text;
  v_addendum int;
  v_invoice int;
  v_signed int;
  v_finance jsonb;
  v_amount numeric;
  v_currency text;
begin
  v_actor:=portal_private.owner_r1_actor('ADMIN');

  select d.id,w.product_confirmed_at,w.quantity_confirmed_at,
         coalesce(w.cancellation_state,'ACTIVE'),coalesce(w.payment_handoff_state,'NOT_SENT')
    into v_deal,v_prod,v_qty,v_cancel,v_handoff
    from portal_private.deals d
    left join portal_private.owner_deal_workflow w on w.deal_key=d.id
   where d.deal_id=p_deal_id
   limit 1;

  if v_deal is null then raise exception using errcode='P0001',message='DEAL_NOT_FOUND'; end if;
  if v_cancel<>'ACTIVE' then raise exception using errcode='P0001',message='DEAL_NOT_ACTIVE'; end if;
  if v_prod is null then raise exception using errcode='P0001',message='PRODUCT_CONFIRMATION_REQUIRED'; end if;
  if v_qty is null then raise exception using errcode='P0001',message='VOLUME_CONFIRMATION_REQUIRED'; end if;

  select count(*) filter(where odd.document_kind in ('ADDENDUM','SIGNED_ADDENDUM')),
         count(*) filter(where odd.document_kind='INVOICE'),
         count(*) filter(where odd.document_kind='SIGNED_ADDENDUM')
    into v_addendum,v_invoice,v_signed
    from portal_private.owner_deal_documents odd
    join portal_private.documents doc on doc.id=odd.document_key
   where odd.deal_key=v_deal
     and doc.lifecycle_state='ACTIVE'::portal_private.lifecycle_state_enum;

  if v_addendum=0 then raise exception using errcode='P0001',message='ADDENDUM_REQUIRED'; end if;
  if v_invoice=0 then raise exception using errcode='P0001',message='INVOICE_REQUIRED'; end if;
  if v_signed=0 then raise exception using errcode='P0001',message='SIGNED_ADDENDUM_REQUIRED'; end if;

  -- One canonical transaction: authoritative economics and payment expectations first, SENT second.
  v_finance:=portal_private.owner_r1_materialize_payment_finance(p_deal_id);
  if not coalesce((v_finance->>'materialized')::boolean,false) then
    raise exception using errcode='P0001',message='PAYMENT_ECONOMICS_NOT_MATERIALIZED',detail=coalesce(v_finance->>'reason','UNKNOWN');
  end if;

  perform portal_private.owner_r1_reconcile_generated_payment_plan(p_deal_id);

  v_amount:=(v_finance->>'remaining')::numeric;
  v_currency:=v_finance->>'currency';
  if v_amount is null or v_amount<0 or coalesce(v_currency,'')!~'^[A-Z]{3}$' then
    raise exception using errcode='P0001',message='PAYMENT_ECONOMICS_NOT_MATERIALIZED',detail='MATERIALIZED_RESULT_INVALID';
  end if;

  update portal_private.owner_deal_workflow
     set payment_handoff_state='SENT',
         payment_handoff_at=coalesce(payment_handoff_at,now()),
         payment_handoff_by=coalesce(payment_handoff_by,v_actor),
         payment_expectation_state=case when v_amount>0 then 'ACTIVE' else 'NOT_CREATED' end,
         payment_expectation_amount=v_amount,
         payment_expectation_currency=v_currency,
         updated_at=now()
   where deal_key=v_deal;

  return jsonb_build_object(
    'dealId',p_deal_id,
    'state','SENT',
    'amount',v_amount,
    'currency',v_currency,
    'unitPrice',(v_finance->>'unitPrice')::numeric,
    'quantityTonnes',(v_finance->>'quantityTonnes')::numeric,
    'obligation',(v_finance->>'obligation')::numeric,
    'received',(v_finance->>'received')::numeric,
    'financePending',false,
    'financeSource',v_finance->>'source',
    'idempotent',v_handoff='SENT'
  );
end
$$;

comment on function public.owner_r1_send_to_payments(text) is
'Owner R1 canonical atomic payment handoff. No pre-existing finance summary is required; accepted economics are materialized from authoritative lineage in the same transaction, and SENT is recorded only after successful materialization. Repeated send is an idempotent repair/read path.';

-- Generic reconciliation for fallback rows only. Canonical pre-existing payment plans are outside this scope.
do $$
declare r record;
begin
  for r in
    select d.deal_id
      from portal_private.deals d
      join portal_private.owner_payment_plan p on p.deal_key=d.id
     group by d.deal_id
    having count(*)=1
       and count(*) filter(where p.source_system='ADMIN_DEAL_HANDOFF_R1')=1
  loop
    perform portal_private.owner_r1_reconcile_generated_payment_plan(r.deal_id);
  end loop;
end
$$;