import baseRuntime from './chunk18-base.js';
import adminDealsPremiumRuntime from '../main-ui/admin-deals-premium-v1.js';
import adminDealsSemanticButtonsRuntime from '../main-ui/admin-deals-semantic-buttons-v1.js';
import adminDealsSemanticCorrectionsRuntime from '../main-ui/admin-deals-semantic-corrections-v1.js';
import adminDealPassportPremiumRuntime from '../main-ui/admin-deal-passport-premium-v1.js';

export const adminTopbarTickerV2=String.raw`(()=>{'use strict';
if(window.__RONA_ADMIN_TOPBAR_TICKER_V2__||location.pathname!=='/portal/admin')return;
window.__RONA_ADMIN_TOPBAR_TICKER_V2__='20260914-post-ready-v2';
const root=document.documentElement,styleId='ronaAdminTopbarTickerV2Style',tickerId='rona-admin-build-ticker-v2';
let observer=null,tries=0;
function isReady(){return window.__RONA_OWNER_ADMIN_READY__===true&&root.classList.contains('rona-owner-paint-ready')}
function installStyle(){if(document.getElementById(styleId))return;const s=document.createElement('style');s.id=styleId;s.textContent='html[data-rona-admin-topbar-ticker="ready"] .topbar>.search{flex:0 1 760px!important;width:min(44vw,760px)!important;max-width:760px!important;min-width:360px!important}html[data-rona-admin-topbar-ticker="ready"] #'+tickerId+'{flex:1 1 300px;min-width:220px;max-width:460px;height:36px;overflow:hidden;display:flex;align-items:center;border:1px solid rgba(125,211,252,.20);border-radius:11px;background:linear-gradient(90deg,rgba(3,18,27,.82),rgba(9,28,42,.72));box-shadow:inset 0 1px 0 rgba(255,255,255,.035),0 6px 20px rgba(0,0,0,.14)}html[data-rona-admin-topbar-ticker="ready"] #'+tickerId+' .track{display:inline-flex;align-items:center;width:max-content;min-width:max-content;padding-left:100%;white-space:nowrap;will-change:transform;animation:ronaAdminTickerV2 14s linear infinite}html[data-rona-admin-topbar-ticker="ready"] #'+tickerId+' .text{display:inline-flex;align-items:center;width:max-content;padding:0 18px;font:600 10.5px/36px system-ui,sans-serif;letter-spacing:.04em;color:#dce8ff}html[data-rona-admin-topbar-ticker="ready"] #'+tickerId+'[data-state="ok"] .text{color:#d8ffec}html[data-rona-admin-topbar-ticker="ready"] #'+tickerId+'[data-state="error"] .text{color:#ffd8dc}html[data-rona-admin-topbar-ticker="ready"] #'+tickerId+':hover .track{animation-play-state:paused}html[data-rona-admin-topbar-ticker="ready"] body>#rona-owner-build-indicator{opacity:0!important;visibility:hidden!important;pointer-events:none!important}@keyframes ronaAdminTickerV2{from{transform:translateX(0)}to{transform:translateX(-100%)}}@media(max-width:1180px){html[data-rona-admin-topbar-ticker="ready"] #'+tickerId+'{display:none!important}html[data-rona-admin-topbar-ticker="ready"] .topbar>.search{flex:1 1 auto!important;width:auto!important;max-width:none!important;min-width:0!important}html[data-rona-admin-topbar-ticker="ready"] body>#rona-owner-build-indicator{opacity:1!important;visibility:visible!important;pointer-events:auto!important}}@media(prefers-reduced-motion:reduce){html[data-rona-admin-topbar-ticker="ready"] #'+tickerId+' .track{width:100%!important;min-width:0!important;padding-left:0!important;animation:none!important;transform:none!important;justify-content:center}}';document.head.appendChild(s)}
function source(){return document.getElementById('rona-owner-build-indicator')}
function sync(){const h=document.getElementById(tickerId),t=h?.querySelector('.text'),n=source();if(!h||!t)return;t.textContent=n?.textContent?.trim()||('Сборка: '+String(window.__RONA_UI_BUILD__||'owner-main-v2')+' · Данные: загружены');h.dataset.state=String(n?.dataset?.state||'loading')}
function mount(){if(!isReady())return false;const top=document.querySelector('.topbar');if(!top)return false;const anchor=Array.from(top.children).find(x=>/внутренний\s+контур/i.test(String(x.textContent||'')))||top.querySelector('.role-pill');if(!anchor)return false;installStyle();let h=document.getElementById(tickerId);if(!h){h=document.createElement('div');h.id=tickerId;h.setAttribute('aria-label','Статус текущей сборки');const tr=document.createElement('div');tr.className='track';const tx=document.createElement('span');tx.className='text';tr.appendChild(tx);h.appendChild(tr)}if(h.parentNode!==top||h.nextSibling!==anchor)top.insertBefore(h,anchor);root.dataset.ronaAdminTopbarTicker='ready';observer?.disconnect();const n=source();if(n){observer=new MutationObserver(sync);observer.observe(n,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['data-state']})}sync();return true}
function boot(){if(mount())return;if(++tries<240)setTimeout(boot,50)}
window.addEventListener('rona:admin-single-owner-ready',()=>{tries=0;boot()});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();`;

export default baseRuntime + adminDealsPremiumRuntime + adminDealsSemanticButtonsRuntime + adminDealsSemanticCorrectionsRuntime + adminDealPassportPremiumRuntime + adminTopbarTickerV2;
