export default `(()=>{'use strict';
if(window.__RONA_AI_LK_SYNC_OVERLAY__)return;window.__RONA_AI_LK_SYNC_OVERLAY__=true;
const API='/portal/owner-api';let adminSync=null,agentSync=null;
const q=s=>document.querySelector(s);const fmt=(v,d=2)=>v===null||v===undefined||v===''?'—':new Intl.NumberFormat('ru-RU',{maximumFractionDigits:d}).format(Number(v));
function e(tag,attrs={},...children){const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k==='class')n.className=v;else if(k==='text')n.textContent=String(v);else n.setAttribute(k,String(v))}for(const c of children.flat()){if(c===null||c===undefined)continue;n.append(c?.nodeType?c:document.createTextNode(String(c)))}return n}
function table(headers,rows){const t=e('table',{class:'rona-owner-table'}),h=e('thead'),hr=e('tr');headers.forEach(x=>hr.append(e('th',{text:x})));h.append(hr);const b=e('tbody');rows.forEach(row=>{const tr=e('tr');row.forEach(x=>{const td=e('td');td.append(x?.nodeType?x:document.createTextNode(String(x??'—')));tr.append(td)});b.append(tr)});t.append(h,b);return e('div',{class:'rona-owner-table-wrap'},t)}
function card(id,title,...children){const c=e('section',{id,class:'rona-owner-card'});c.append(e('h2',{text:title}));children.flat().forEach(x=>c.append(x?.nodeType?x:document.createTextNode(String(x))));return c}
async function load(path){const r=await fetch(API+'?path='+encodeURIComponent(path),{credentials:'same-origin',cache:'no-store',headers:{accept:'application/json'}});const j=await r.json().catch(()=>({}));if(!r.ok||j?.ok===false)throw new Error(j?.code||('HTTP_'+r.status));return j.data}
const roleRu=v=>({FINANCE:'Финансовый директор',LEGAL:'Юрист',MARKET_ANALYST:'Аналитик рынков',OPERATIONS_DIRECTOR:'Операционный директор',RAIL_LOGISTICS:'ЖД-логистика',SYSTEM_ADMIN:'Системный администратор'}[String(v)]||String(v||'—'));
const tariffStatusRu=v=>({WORKING_CONFIRMED:'Подтверждено',ROUTE_SPECIFIC_CONFIRMED:'Подтверждено для маршрута',HISTORICAL:'Исторический',TO_VERIFY:'Требует проверки',FX_DEPENDENT:'Зависит от курса'}[String(v)]||String(v||'—'));
function renderAdmin(){if(!adminSync)return;const home=q('#page-home .rona-owner-page-content')||q('#page-home');if(home&&!q('#ronaAiEmployeesCard')){const r=adminSync.aiRuntime||{},active=(adminSync.aiEmployees||[]).filter(x=>String(x.status)==='ACTIVE').length,total=(adminSync.aiEmployees||[]).length;home.append(card('ronaAiEmployeesCard','ИИ-сотрудники',e('div',{class:'rona-owner-grid'},e('div',{class:'rona-owner-card'},e('div',{class:'rona-owner-muted',text:'Активные роли'}),e('div',{class:'rona-owner-kpi',text:active+'/'+total})),e('div',{class:'rona-owner-card'},e('div',{class:'rona-owner-muted',text:'Контур обмена'}),e('div',{class:'rona-owner-status',text:r.enabled&&r.scheduler_state==='ENABLED'?'Работает':'Ограничен'})),e('div',{class:'rona-owner-card'},e('div',{class:'rona-owner-muted',text:'Heartbeat'}),e('div',{class:'rona-owner-kpi',text:r.heartbeat_minutes?String(r.heartbeat_minutes)+' мин':'—'}))),table(['Сотрудник','Роль','Статус'],(adminSync.aiEmployees||[]).map(x=>[x.display_name||roleRu(x.business_role),roleRu(x.business_role),x.status||'—'])),e('div',{class:'rona-owner-muted',text:'Автономный server-side model executor: '+String(r.model_execution_state||'—')+'. Интерактивный fixed-role контур работает независимо от этого статуса.'})))}
const mon=q('#page-monitoring .rona-owner-page-content')||q('#page-monitoring');if(mon&&!q('#ronaRailTariffMatrixCard')){const rows=(adminSync.railTariffs||[]).map(x=>[x.product_group==='LPG_SPBT'?'СУГ / СПБТ':'Светлые нефтепродукты',x.territory,x.route_text,fmt(x.tariff_usd_per_t,2),x.source_provider,tariffStatusRu(x.status)]);mon.append(card('ronaRailTariffMatrixCard','Матрица ЖД-тарифов',rows.length?table(['Товарная группа','Территория','Маршрут','USD/т','Источник','Статус'],rows):e('div',{class:'rona-owner-muted',text:'Подтвержденные тарифы отсутствуют.'}),e('div',{class:'rona-owner-muted',text:'Тарифы являются расчетными логистическими данными и не подтверждают факт отгрузки или движения вагонов.'}))}
if(home&&!q('#ronaAiConclusionsCard')){const xs=(adminSync.latestAiConclusions||[]).slice(0,12);home.append(card('ronaAiConclusionsCard','Последние выводы ИИ-сотрудников',xs.length?table(['Сотрудник','Объект','Статус','Вывод'],xs.map(x=>[roleRu(x.role),(x.target_type||'')+' '+(x.target_id||''),x.status||'—',String(x.summary||'—').slice(0,420)])):e('div',{class:'rona-owner-muted',text:'Новых выводов нет.'}),e('div',{class:'rona-owner-muted',text:'Этот блок показывает audited выводы. Изменение договоров, платежей, публикаций, движения и IAM выполняется только профильным authoritative workflow.'}))}}
function renderAgent(){if(!agentSync)return;const root=q('#ronaOwnerAgentSummary');if(!root||q('#ronaAgentSettlementCard'))return;const p=agentSync.displayPolicy;const rows=(agentSync.settlements||[]).map(x=>[x.dealId,x.clientId,x.stage,fmt(x.amount,2)+(x.currency?' '+x.currency:''),x.paymentObligationConfirmed?'Подтверждено':'Не подтверждено',x.paymentFactConfirmed?'Оплачено':'Нет факта оплаты']);root.append(card('ronaAgentSettlementCard','Расчёт агента',p?e('div',{class:'rona-owner-card'},e('strong',{text:'Правило курсового эффекта: '+fmt(Number(p.positiveActualFxVisibleShare||0)*100,0)+'%'}),e('div',{class:'rona-owner-muted',text:p.note||''})):null,rows.length?table(['Сделка','Клиент','Стадия','Сумма','Обязательство','Оплата'],rows):e('div',{class:'rona-owner-muted',text:'Подтвержденный расчет к выплате пока не сформирован.'}),e('div',{class:'rona-owner-muted',text:'Неподтвержденные, прогнозные и внутренние Finance/Accounting значения в ЛК не публикуются.'}))}
async function refreshAdmin(){try{adminSync=await load('/admin/ai-sync');window.__RONA_OWNER_AI_SYNC_SNAPSHOT__=adminSync;renderAdmin()}catch(e){window.__RONA_OWNER_AI_SYNC_ERROR__=String(e.message||e)}}
async function refreshAgent(){try{agentSync=await load('/agent/ai-sync');window.__RONA_OWNER_AGENT_AI_SYNC_SNAPSHOT__=agentSync;renderAgent()}catch(e){window.__RONA_OWNER_AGENT_AI_SYNC_ERROR__=String(e.message||e)}}
const path=location.pathname;if(path==='/portal/admin'){const start=()=>{refreshAdmin();setInterval(refreshAdmin,60000);new MutationObserver(()=>renderAdmin()).observe(document.body,{childList:true,subtree:true})};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start()}else if(path==='/portal/agent'){const start=()=>{refreshAgent();setInterval(refreshAgent,60000);new MutationObserver(()=>renderAgent()).observe(document.body,{childList:true,subtree:true})};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start()}
})();`;
