export default `(()=>{'use strict';
if(window.__RONA_OWNER_PREPAINT_RELEASE__)return;
window.__RONA_OWNER_PREPAINT_RELEASE__=true;
const path=location.pathname;
const role=path==='/portal/admin'?'ADMIN':path==='/portal/client'?'CLIENT':path==='/portal/agent'?'AGENT':'';
if(!role){document.documentElement.classList.add('rona-owner-paint-ready');return}
const ready='__RONA_OWNER_'+role+'_READY__',error='__RONA_OWNER_'+role+'_ERROR__';
let done=false,frames=0,fallbackObserver=null;
function style(){if(document.getElementById('ronaOwnerIncidentStyle'))return;const s=document.createElement('style');s.id='ronaOwnerIncidentStyle';s.textContent='#rona-owner-build-indicator{position:fixed;right:12px;bottom:12px;z-index:2147483647;padding:7px 10px;border-radius:999px;background:rgba(9,16,30,.92);color:#dce8ff;border:1px solid rgba(137,169,220,.35);font:600 11px/1.2 system-ui,sans-serif;box-shadow:0 8px 28px rgba(0,0,0,.28)}#rona-owner-build-indicator[data-state="error"]{border-color:#ff6b7a;color:#ffd8dc}#rona-owner-build-indicator[data-state="ok"]{border-color:#46c98b;color:#d8ffec}html:not(.rona-owner-paint-ready) body>#rona-owner-build-indicator,html:not(.rona-owner-paint-ready) body>#rona-owner-failclosed{opacity:1!important;visibility:visible!important;pointer-events:auto!important}#rona-owner-failclosed{position:fixed;inset:0;z-index:2147483646;display:flex;align-items:center;justify-content:center;padding:28px;background:#0b1020;color:#f4f7ff;font-family:system-ui,sans-serif}#rona-owner-failclosed .rona-owner-incident-card{width:min(680px,100%);padding:28px;border:1px solid rgba(255,107,122,.45);border-radius:18px;background:#121a2c;box-shadow:0 24px 80px rgba(0,0,0,.4)}#rona-owner-failclosed h1{margin:0 0 12px;font-size:24px}#rona-owner-failclosed p{margin:8px 0;color:#c9d4e8;line-height:1.45}#rona-owner-failclosed code{display:block;margin-top:14px;padding:10px 12px;border-radius:10px;background:#0b1020;color:#ffd8dc;overflow-wrap:anywhere}#rona-owner-failclosed button{margin-top:18px;padding:10px 14px;border:1px solid rgba(255,255,255,.2);border-radius:10px;background:#1d2a45;color:#fff;font-weight:700;cursor:pointer}';document.head.appendChild(s)}
function indicator(){style();let n=document.getElementById('rona-owner-build-indicator');if(!n&&document.body){n=document.createElement('div');n.id='rona-owner-build-indicator';document.body.appendChild(n)}return n}
function currentOnlyReady(){if(window[ready]!==true)return false;if(role!=='ADMIN')return true;return window.__RONA_POSTCORE_ENHANCEMENTS_READY__===true&&document.documentElement.dataset.ronaPostcore==='ready'&&!!window.__RONA_ADMIN_CANONICAL_TWEAKS__}
function updateIndicator(){const n=indicator();if(!n)return;const build=String(window.__RONA_UI_BUILD__||'owner-main-v2');const coreErr=window[error];const aiErr=role==='ADMIN'?window.__RONA_OWNER_AI_SYNC_ERROR__:role==='AGENT'?window.__RONA_OWNER_AGENT_AI_SYNC_ERROR__:null;const coreOk=window[ready]===true,canonicalOk=currentOnlyReady();const financeOk=role!=='ADMIN'||!!window.__RONA_OWNER_AI_SYNC_SNAPSHOT__;let state='loading',data='загрузка';if(coreErr||aiErr){state='error';data='ошибка'}else if(canonicalOk){state='ok';data=financeOk?'загружены':'интерфейс загружен / finance синхронизация'}else if(coreOk){state='loading';data=role==='ADMIN'?'канонический интерфейс':'core загружен'}n.dataset.state=state;n.textContent='Сборка: '+build+' · Данные: '+data}
function suppressLegacyFallback(){if(role!=='ADMIN')return false;const root=document.documentElement;if(root.dataset.ronaOwnerPaint!=='fallback')return false;root.classList.remove('rona-owner-paint-ready');root.dataset.ronaOwnerPaint='current-only-loading';root.dataset.ronaAdminBootFailsafe='suppressed-current-only';window.__RONA_OWNER_FIRST_PAINT_READY__=false;window.__RONA_OWNER_SHELL_FALLBACK__=false;const app=document.querySelector('.app');if(app){for(const name of ['opacity','visibility','pointer-events'])app.style.removeProperty(name);app.setAttribute('aria-hidden','true')}updateIndicator();return true}
function failClosed(reason){if(done)return true;done=true;if(fallbackObserver)fallbackObserver.disconnect();style();document.documentElement.classList.remove('rona-owner-paint-ready');document.documentElement.dataset.ronaOwnerPaint='blocked-error';window.__RONA_OWNER_FIRST_PAINT_READY__=false;if(document.body&&!document.getElementById('rona-owner-failclosed')){const root=document.createElement('section');root.id='rona-owner-failclosed';const card=document.createElement('div');card.className='rona-owner-incident-card';const h=document.createElement('h1');h.textContent='Интерфейс временно заблокирован';const p=document.createElement('p');p.textContent='Основной интерфейс не прошёл загрузку. Старая версия кабинета намеренно не показывается.';const c=document.createElement('code');c.textContent='UI_ERROR: '+String(reason||'PRIMARY_UI_NOT_READY');const b=document.createElement('button');b.type='button';b.textContent='Повторить загрузку';b.onclick=()=>location.reload();card.append(h,p,c,b);root.append(card);document.body.append(root)}updateIndicator();return true}
function reveal(mode){if(done)return true;done=true;if(fallbackObserver)fallbackObserver.disconnect();const app=document.querySelector('.app');if(app){for(const name of ['opacity','visibility','pointer-events'])app.style.removeProperty(name);app.removeAttribute('aria-hidden')}document.documentElement.classList.add('rona-owner-paint-ready');document.documentElement.dataset.ronaOwnerPaint=mode||'ready';window.__RONA_OWNER_FIRST_PAINT_READY__=true;updateIndicator();return true}
function tick(){if(done)return;suppressLegacyFallback();if(currentOnlyReady())return reveal('ready');if(window[error])return failClosed(window[error]);if(++frames>3600)return failClosed('PRIMARY_UI_READY_TIMEOUT');requestAnimationFrame(tick)}
style();updateIndicator();setInterval(updateIndicator,1000);if(role==='ADMIN'&&typeof MutationObserver==='function'){fallbackObserver=new MutationObserver(()=>{if(suppressLegacyFallback()&&!done)requestAnimationFrame(tick)});fallbackObserver.observe(document.documentElement,{attributes:true,attributeFilter:['class','data-rona-owner-paint']})}if(currentOnlyReady())reveal('ready');else requestAnimationFrame(tick);
})();`;