import { onRequest as basePortal } from './[[path]].js';
const BUILD='owner-main-v2-20260824-0252';
const PRIMARY_UI_SOURCE_CONTRACT='src="/portal/main-ui"';
const PREPAINT='<meta name="rona-ui-primary" content="main-v2"><meta name="rona-ui-build" content="'+BUILD+'"><style id="rona-owner-prepaint-gate">html:not(.rona-owner-paint-ready) body>*:not(script):not(style){opacity:0!important;visibility:hidden!important;pointer-events:none!important}html:not(.rona-owner-paint-ready) body{cursor:wait}</style>';
const LOADER='<script id="rona-main-ui-loader" src="/portal/main-ui?v=20260824-0252" defer data-rona-ui="primary"></script>';
const DEALSCURRENT='<script id="rona-deals-current-loader" src="/portal/deals-current-state-ui?v=20260824-0252" defer data-rona-ui="deals-current-state-v1.5"></script>';
const R11='<script id="rona-deals-r11-loader" src="/portal/deals-r1-r11-ui" defer data-rona-ui="deals-r1-cancel-hotfix"></script>';
const CASH2D='<script id="rona-cash-r2-loader" src="/portal/cash-r2-ui" async data-rona-ui="cash-2d-isolated"></script>';
const RAILV4='<script id="rona-rail-current-v4-loader" src="/portal/rail-current-v4-ui?v=20260824-0252" defer data-rona-ui="rail-current-v4"></script>';
const CLAIMS2F='<script id="rona-claims-r2-loader" src="/portal/claims-r2-ui" async data-rona-ui="claims-2f-isolated"></script>';
const TITLECLEANUP='<script id="rona-title-visual-rollback-loader" src="/portal/title-visual-rollback-ui" async data-rona-ui="title-visual-rollback"></script>';
const CLAIMSTITLE='<script id="rona-claims-title-loader" src="/portal/claims-title-hotfix" async data-rona-ui="claims-title-hotfix"></script>';
const REMAINING='<script id="rona-remaining-sections-loader" src="/portal/remaining-sections-ui" async data-rona-ui="remaining-sections-r1"></script>';
const APPTOTAL='<script id="rona-applications-total-kpi-loader" src="/portal/applications-total-kpi-ui" async data-rona-ui="applications-total-kpi-r1"></script>';
function injectPrepaint(source){if(source.includes('name="rona-ui-primary"'))return source;const lower=source.toLowerCase(),i=lower.indexOf('</head>');if(i<0)return PREPAINT+source;return source.slice(0,i)+PREPAINT+source.slice(i)}
function injectLoader(source){void PRIMARY_UI_SOURCE_CONTRACT;if(source.includes('id="rona-main-ui-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+LOADER;return source.slice(0,i)+LOADER+source.slice(i)}
function injectDealsCurrent(source){if(source.includes('id="rona-deals-current-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+DEALSCURRENT;return source.slice(0,i)+DEALSCURRENT+source.slice(i)}
function injectR11(source){if(source.includes('id="rona-deals-r11-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+R11;return source.slice(0,i)+R11+source.slice(i)}
function injectCash2D(source){if(source.includes('id="rona-cash-r2-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+CASH2D;return source.slice(0,i)+CASH2D+source.slice(i)}
function injectRailV4(source){if(source.includes('id="rona-rail-current-v4-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+RAILV4;return source.slice(0,i)+RAILV4+source.slice(i)}
function injectClaims2F(source){if(source.includes('id="rona-claims-r2-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+CLAIMS2F;return source.slice(0,i)+CLAIMS2F+source.slice(i)}
function injectTitleCleanup(source){if(source.includes('id="rona-title-visual-rollback-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+TITLECLEANUP;return source.slice(0,i)+TITLECLEANUP+source.slice(i)}
function injectClaimsTitle(source){if(source.includes('id="rona-claims-title-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+CLAIMSTITLE;return source.slice(0,i)+CLAIMSTITLE+source.slice(i)}
function injectRemaining(source){if(source.includes('id="rona-remaining-sections-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+REMAINING;return source.slice(0,i)+REMAINING+source.slice(i)}
function injectAppTotal(source){if(source.includes('id="rona-applications-total-kpi-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+APPTOTAL;return source.slice(0,i)+APPTOTAL+source.slice(i)}
export async function onRequest(context){const response=await basePortal(context);const ct=response.headers.get('content-type')||'';if(response.status!==200||!ct.toLowerCase().includes('text/html'))return response;let source=await response.text();source=injectPrepaint(source);source=injectLoader(source);source=injectDealsCurrent(source);source=injectR11(source);source=injectCash2D(source);source=injectRailV4(source);source=injectClaims2F(source);source=injectTitleCleanup(source);source=injectClaimsTitle(source);source=injectRemaining(source);source=injectAppTotal(source);const h=new Headers(response.headers);h.delete('content-length');h.delete('etag');h.set('cache-control','no-store, no-cache, must-revalidate');h.set('pragma','no-cache');h.set('expires','0');h.set('x-rona-ui','main-v2');h.set('x-rona-ui-build',BUILD);h.set('x-rona-r1-ui','current-state-primary');h.set('x-rona-cash-ui','isolated-r2');h.set('x-rona-rail-ui','current-v4');h.set('x-rona-claims-ui','isolated-2f');h.set('x-rona-claims-title','hotfix-v2');h.set('x-rona-title-visual','rollback-pre-sticky');h.set('x-rona-remaining-sections','r1');h.set('x-rona-applications-total-kpi','r1');h.set('x-rona-deals-current-state','v1.5');h.set('x-rona-payments-ui','finance-current-v2');return new Response(source,{status:response.status,statusText:response.statusText,headers:h})}
