const SCRIPT=String.raw`(()=>{'use strict';
if(window.__RONA_AGENT_CP_UI__)return;
window.__RONA_AGENT_CP_UI__='20260825-current-only-v1';
if(location.pathname!=='/portal/agent')return;
const API='/portal/agent-cp-api';
const q=(s,r=document)=>r.querySelector(s),el=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!==undefined&&x!==null)n.textContent=String(x);return n};
const dt=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})};
let state=null,busy=false,renderKey='';
function root(){return q('#ronaOwnerAgentSummary')}
function style(){if(q('#ronaAgentCpStyle'))return;const s=el('style');s.id='ronaAgentCpStyle';s.textContent=[
'#ronaAgentCpCard .rona-agent-cp-list{display:grid;gap:0;margin-top:10px}.rona-agent-cp-item{display:grid;grid-template-columns:minmax(220px,1.2fr) minmax(180px,.8fr) minmax(180px,.8fr) auto;gap:12px;align-items:center;padding:13px 4px;border-bottom:1px solid rgba(144,184,205,.08);font-size:12px}.rona-agent-cp-item:last-child{border-bottom:0}.rona-agent-cp-name{font-weight:850}.rona-agent-cp-meta{color:var(--rv-muted,#91a2b3)}.rona-agent-cp-open{font:inherit;color:#f6fcff;background:rgba(53,169,219,.16);border:1px solid rgba(89,215,255,.34);border-radius:9px;padding:9px 11px;font-size:11px;font-weight:850;cursor:pointer}.rona-agent-cp-empty{padding:12px 0;color:var(--rv-muted,#91a2b3);font-size:12px;line-height:1.5}',
'@media(max-width:820px){.rona-agent-cp-item{grid-template-columns:1fr 1fr}.rona-agent-cp-open{width:100%}}@media(max-width:580px){.rona-agent-cp-item{grid-template-columns:1fr}}'
].join('');document.head.appendChild(s)}
async function api(){const r=await fetch(API+'/agent/bootstrap',{credentials:'same-origin',cache:'no-store',headers:{accept:'application/json'}}),j=await r.json().catch(()=>({}));if(!r.ok||j?.ok===false)throw new Error(String(j?.code||`HTTP_${r.status}`));return j.data||{}}
function mount(){const host=root();if(!host||!state)return;style();const xs=Array.isArray(state.commercialProposals)?state.commercialProposals:[],key=String(state.currentPublicationId||'')+'|'+xs.map(x=>[x.cpId,x.sentAt,x.sha256].join(':')).join('|');let card=q('#ronaAgentCpCard',host);if(card&&renderKey===key)return;const next=el('section','rona-owner-card');next.id='ronaAgentCpCard';next.append(el('h2','','Коммерческие предложения'));if(!xs.length){next.append(el('div','rona-agent-cp-empty','Опубликованных коммерческих предложений по текущему прайсу пока нет.'))}else{const list=el('div','rona-agent-cp-list');for(const x of xs){const row=el('div','rona-agent-cp-item'),open=el('button','rona-agent-cp-open','Открыть PDF');open.type='button';open.onclick=()=>window.open(API+'/agent/commercial-proposals/'+encodeURIComponent(x.cpId)+'/download','_blank','noopener');row.append(el('div','rona-agent-cp-name',x.agentName||'RONA Trade'),el('div','rona-agent-cp-meta','Прайс: '+String(x.publicationId||state.currentPublicationId||'—')),el('div','rona-agent-cp-meta','Опубликовано: '+dt(x.sentAt)),open);list.append(row)}next.append(list)}if(card)card.replaceWith(next);else host.append(next);renderKey=key;window.__RONA_AGENT_CP_CURRENT_STATE__=state}
async function refresh(){if(busy)return;busy=true;try{state=await api();window.__RONA_AGENT_CP_ERROR__=null;renderKey='';mount()}catch(err){window.__RONA_AGENT_CP_ERROR__=String(err?.message||err)}finally{busy=false}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(refresh,600),{once:true});else setTimeout(refresh,600);
setInterval(mount,1500);setInterval(refresh,30000);
})();`;
export async function onRequest(){return new Response(SCRIPT,{status:200,headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache','expires':'0','x-content-type-options':'nosniff','x-rona-agent-cp-ui':'20260825-current-only-v1'}})}
