const SCRIPT=String.raw`(()=>{'use strict';
if(window.__RONA_ANALYTICS_V2__)return;
window.__RONA_ANALYTICS_V2__='20260824-analytics-v4-market-consistency-lpg-platts';
const LEGACY_QA_COMPAT='v3-market-rona-bases-lpg';
const DATA={version:'1.1.9-SF5-20260822-2203',sourceCutoff:'22.08.2026 22:03 +03:00',products:{
AI92:{name:'АИ-92',series:{PLATTS:{label:'Platts',basis:'Platts European Marketscan · Gasoline Prem Unleaded 10 ppm · FOB Med (Italy)',dates:['03.08','04.08','05.08','06.08','07.08','10.08','11.08','13.08','14.08','17.08','19.08','21.08'],values:[1035.25,984.75,988.75,1020.50,1066.50,1109.25,1105.25,1119.25,1109.50,1109.25,1154.25,1186.75],lastDate:'21.08.2026',sep:1079.5,oct:971.5}},scenario:{low:930,base:1025,high:1120,confidence:'Средняя',review:'FACT выше HIGH; сценарный коридор не перекалиброван после Platts 21.08.'},rona:{reference:1082.4375,bases:[['CPT Озинки',1223.17],['CPT Сарыагаш',1332.10],['CPT Наушки',1280.91]]}},
AI95:{name:'АИ-95',series:{PLATTS:{label:'Platts',basis:'Platts European Marketscan · Gasoline Prem Unleaded 10 ppm · FOB Med (Italy) · FACT без grade adjustment',dates:['03.08','04.08','05.08','06.08','07.08','10.08','11.08','13.08','14.08','17.08','19.08','21.08'],values:[1035.25,984.75,988.75,1020.50,1066.50,1109.25,1105.25,1119.25,1109.50,1109.25,1154.25,1186.75],lastDate:'21.08.2026',sep:1079.5,oct:971.5}},scenario:{low:970,base:1065,high:1160,confidence:'Средняя',grade:40,review:'LOW / BASE / HIGH содержат отдельный +40 USD/т grade planning и не являются тем же слоем, что FACT-график.'},rona:{reference:1122.4375,bases:[['CPT Озинки',1420.81],['CPT Сарыагаш',1529.74],['CPT Наушки',1478.56]]}},
DT:{name:'ДТ',series:{PLATTS:{label:'Platts / BNK composite',basis:'BNK Diesel Composite · среднее ULSD 10 ppm / Cargoes CIF NWE/Basis ARA и Diesel 10 ppm / Barges FOB Rotterdam',dates:['03.08','04.08','05.08','06.08','07.08','10.08','11.08','13.08','14.08','17.08','19.08','21.08'],values:[1218.125,1147.625,1185.25,1182.375,1206.375,1305,1299.75,1312.25,1322.25,1343.25,1360.75,1363.875],lastDate:'21.08.2026',sep:1315.625,oct:1266.375}},scenario:{low:1160,base:1240,high:1325,confidence:'Средняя',review:'FACT выше HIGH, сентябрьский forward находится у верхней границы старого коридора.'},rona:{reference:1270.572916666667,bases:[['CPT Озинки',1273.43],['CPT Сарыагаш',1380.31],['CPT Наушки',1331.18]]}},
LPG:{name:'LPG / СУГ',series:{PLATTS:{label:'Platts propane',basis:'Platts · Propane CIF NWE Large Cargo Financial · London MOC / Balance month',dates:['03.08','04.08','05.08','06.08','07.08','10.08','11.08','13.08','14.08','17.08','19.08'],values:[494.5,485,498.5,499,504.5,514.5,510,521.5,522,522,563.5],lastDate:'19.08.2026',forwardDate:'21.08.2026',sep:560.5,oct:558.5},REGIONAL:{label:'Hairatan / регион',basis:'Hairatan domestic LPG · оперативный региональный сигнал; Petromarket Eurasian LPG используется отдельно как DAP comparator',dates:['18.08','22.08','23.08'],values:[943,970,995],lastDate:'23.08.2026',sep:null,oct:null}},scenario:{confidence:'Средняя',noScenario:true},regional:{saryagash:['DAP Сарыагаш',725,780,'Petromarket Eurasian LPG · 18.08'],galaba:['CPT Галаба',750,790,'Argus · 19.08'],turksib:['Турксиб',600,660,'Petromarket / Argus · 18–19.08'],bekabad:['DAP Бекабад',660,670,'Petromarket · 18.08']},rona:{bases:[['CPT Озинки',605.26],['CPT Сарыагаш',742.50]]}}
},argus:{required:'Argus European Products · EUROBOB Oxy · Northwest Europe - barge',reason:'Корректный ряд Argus European Products в текущем структурированном контуре не загружен. Региональные серии Argus не подставляются вместо требуемого бензинового индекса.'}};
const S={product:'AI92',source:'PLATTS'};
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const el=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!==undefined&&x!==null)n.textContent=String(x);return n};
const has=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const fmt=(v,d=2)=>has(v)?new Intl.NumberFormat('ru-RU',{minimumFractionDigits:d,maximumFractionDigits:d}).format(Number(v)):'—';
const pct=v=>fmt(v,1)+'%';
function page(){return q('#page-analytics')}
function pill(t,tone='neutral'){return el('span','rona-fin-pill rona-fin-pill--'+tone,t)}
function card(title,...xs){const c=el('section','rona-owner-card');if(title)c.append(el('h2','',title));xs.filter(Boolean).forEach(x=>c.append(x));return c}
function kpi(t,v,c){return card(t,el('div','rona-owner-kpi',v),el('div','rona-owner-muted',c))}
function style(){if(q('#ronaAnalyticsV2Style'))return;const s=el('style');s.id='ronaAnalyticsV2Style';s.textContent='.an2{display:grid;gap:14px;width:100%}.an2-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;flex-wrap:wrap}.an2-head h1{margin:0 0 6px;font-size:24px}.an2-head p{margin:0;max-width:900px}.an2-kpis{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.an2-controls{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.an2-controls button{font:inherit;color:inherit;background:transparent;border:1px solid var(--line,rgba(255,255,255,.22));border-radius:9px;padding:8px 11px;cursor:pointer;font-weight:700}.an2-controls button[aria-pressed="true"]{box-shadow:inset 0 0 0 1px currentColor;background:rgba(255,255,255,.06)}.an2-controls button:disabled{opacity:.45}.an2-main{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(300px,.66fr);gap:20px;align-items:start}.an2-chart{min-height:390px}.an2-chart svg{display:block;width:100%;height:335px}.an2-gridline{stroke:currentColor;opacity:.1}.an2-axis{font-size:11px;fill:currentColor;opacity:.62}.an2-line{fill:none;stroke:currentColor;stroke-width:3}.an2-dot{fill:currentColor}.an2-point-value{font-size:10px;font-weight:800;fill:currentColor;paint-order:stroke;stroke:rgba(5,18,33,.9);stroke-width:3px}.an2-basis{margin-top:8px}.an2-market-forecast{min-width:0}.an2-mf-title{font-size:14px;font-weight:800;margin-bottom:5px}.an2-mf-sub{font-size:11px;opacity:.62;margin-bottom:10px}.an2-mf-row{display:grid;grid-template-columns:1fr auto;gap:12px;padding:9px 2px;border-bottom:1px solid var(--line-soft,rgba(255,255,255,.12))}.an2-mf-row span{font-size:11px;opacity:.72}.an2-mf-row strong{font-size:17px}.an2-mf-meta{display:grid;gap:5px;margin-top:12px;font-size:11px;opacity:.75}.an2-model-review{margin-top:10px;padding:9px 10px;border:1px solid rgba(245,158,11,.32);border-radius:10px;background:rgba(245,158,11,.07);font-size:11px;line-height:1.45}.an2-rona{display:grid;gap:12px}.an2-rona-head{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.an2-rona-head h2{margin:0}.an2-rona-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:12px}.an2-price-card{margin:0!important}.an2-price-card h3{margin:0 0 8px;font-size:13px}.an2-price-base{font-size:24px;font-weight:800}.an2-price-range,.an2-price-current,.an2-model-note{font-size:11px;line-height:1.5;opacity:.72}.an2-comment{font-size:13px;line-height:1.65;white-space:pre-wrap}.an2-empty{padding:18px;border:1px dashed var(--line-soft,rgba(255,255,255,.18));border-radius:12px}@media(max-width:1050px){.an2-main{grid-template-columns:1fr}}@media(max-width:680px){.an2-kpis{grid-template-columns:1fr}.an2-controls{display:grid}.an2-controls button{width:100%}.an2-rona-grid{grid-template-columns:1fr}}';document.head.append(s)}
function root(){const p=page();if(!p)return null;style();let r=q('#rona-analytics-v2',p);if(!r){r=el('section','an2');r.id='rona-analytics-v2';p.prepend(r)}for(const x of qa(':scope>*',p))if(x!==r){x.style.setProperty('display','none','important');x.setAttribute('aria-hidden','true')}return r}
function stats(v){const a=v.map(Number),last=a.at(-1),prev=a.at(-2);return{last,prev,avg:a.reduce((x,y)=>x+y,0)/a.length,d1:last-prev,d1pct:(last/prev-1)*100}}
function series(p){return p.series[S.source]||p.series.PLATTS}
function curve(s){if(!has(s.sep)||!has(s.oct))return '—';const d=s.oct-s.sep;return Math.abs(d)<3?'Почти flat':d<0?'Бэквордация':'Контанго'}
function chart(s){const v=s.values,d=s.dates,w=900,h=320,p={l:62,r:28,t:42,b:44},mn=Math.min(...v),mx=Math.max(...v),sp=Math.max(1,mx-mn),lo=mn-sp*.14,hi=mx+sp*.16,x=i=>p.l+(w-p.l-p.r)*i/(v.length-1),y=n=>p.t+(h-p.t-p.b)*(1-(n-lo)/(hi-lo)),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 '+w+' '+h);for(let i=0;i<5;i++){const yy=p.t+(h-p.t-p.b)*i/4,l=document.createElementNS(svg.namespaceURI,'line');l.setAttribute('x1',p.l);l.setAttribute('x2',w-p.r);l.setAttribute('y1',yy);l.setAttribute('y2',yy);l.setAttribute('class','an2-gridline');svg.append(l);const t=document.createElementNS(svg.namespaceURI,'text');t.setAttribute('x',4);t.setAttribute('y',yy+4);t.setAttribute('class','an2-axis');t.textContent=fmt(hi-(hi-lo)*i/4,0);svg.append(t)}const pl=document.createElementNS(svg.namespaceURI,'polyline');pl.setAttribute('points',v.map((n,i)=>x(i)+','+y(n)).join(' '));pl.setAttribute('class','an2-line');svg.append(pl);v.forEach((n,i)=>{const c=document.createElementNS(svg.namespaceURI,'circle');c.setAttribute('cx',x(i));c.setAttribute('cy',y(n));c.setAttribute('r',3.8);c.setAttribute('class','an2-dot');svg.append(c);const a=document.createElementNS(svg.namespaceURI,'text');a.setAttribute('x',x(i));a.setAttribute('y',y(n)+(i%2?-11:17));a.setAttribute('text-anchor','middle');a.setAttribute('class','an2-point-value');a.textContent=fmt(n,2);svg.append(a);const b=document.createElementNS(svg.namespaceURI,'text');b.setAttribute('x',x(i));b.setAttribute('y',h-12);b.setAttribute('text-anchor','middle');b.setAttribute('class','an2-axis');b.textContent=d[i];svg.append(b)});return svg}
function forecast(p,s){const st=stats(s.values),c=p.scenario,a=el('aside','an2-market-forecast');a.append(el('div','an2-mf-title','Прогноз рынка на 09.2026'),el('div','an2-mf-sub','FACT / MTD / FORWARD · сопоставимый рыночный слой'));[['Последний FACT',st.last],['MTD',st.avg],['Forward Sep',s.sep],['Forward Oct',s.oct]].forEach(x=>{const r=el('div','an2-mf-row');r.append(el('span','',x[0]),el('strong','',fmt(x[1],2)));a.append(r)});if(c.noScenario){a.append(el('div','an2-model-review',S.source==='PLATTS'?'LOW / BASE / HIGH по Platts LPG-базису не сформирован. Региональные DAP/CPT не подставляются вместо европейского financial forward.':'LOW / BASE / HIGH по оперативному Hairatan-ряду не формируются. Прогноз строится по Platts forward и отдельным региональным delivered comparators.'))}else{const h=el('div','an2-model-review','LOW / BASE / HIGH модели · НА ПЕРЕСМОТРЕ');a.append(h);[['LOW',c.low],['BASE',c.base],['HIGH',c.high]].forEach(x=>{const r=el('div','an2-mf-row');r.append(el('span','',x[0]),el('strong','',fmt(x[1],2)));a.append(r)});if(c.grade)a.append(el('div','an2-model-review','AI-95: grade planning +'+fmt(c.grade,0)+' USD/т отделён от сырого Platts FACT/forward.'));a.append(el('div','an2-model-review',c.review))}const m=el('div','an2-mf-meta');m.append(el('div','','Кривая Sep/Oct: '+curve(s)),el('div','','Уверенность модели: '+c.confidence));a.append(m);return a}
function header(r){const h=el('section','rona-owner-card an2-head'),x=el('div');x.append(el('h1','','Аналитика'),el('p','rona-owner-muted','Рыночная аналитика Коммерческого директора: FACT, MTD, forward, региональные ориентиры и отдельный индикативный слой RONA Trade.'));h.append(x,pill('Внутренний аналитический контур','info'));r.append(h)}
function kpis(r){const p=DATA.products[S.product],g=el('div','an2-kpis');if(S.product==='LPG'){const s=p.series.PLATTS,st=stats(s.values);g.append(kpi('Platts propane',fmt(st.last,2)+' USD/т','Balance month · '+s.lastDate),kpi('Forward 09.2026',fmt(s.sep,2)+' USD/т','Platts CIF NWE · '+s.forwardDate),kpi('Сарыагаш','725–780 USD/т','Petromarket · другой базис'))}else{const s=p.series.PLATTS,st=stats(s.values);g.append(kpi('Последний FACT',fmt(st.last,2)+' USD/т',s.lastDate),kpi('MTD',fmt(st.avg,2)+' USD/т','Среднее по полученным котировочным дням'),kpi('Forward 09.2026',fmt(s.sep,2)+' USD/т',curve(s)))}r.append(g)}
function controls(r){const c=card('Базовая котировка'),b=el('div','an2-controls');for(const k of ['AI92','AI95','DT','LPG']){const x=el('button','',DATA.products[k].name);x.type='button';x.setAttribute('aria-pressed',S.product===k?'true':'false');x.onclick=()=>{S.product=k;S.source=k==='LPG'?'REGIONAL':'PLATTS';render()};b.append(x)}b.append(el('span','rona-owner-muted','Источник:'));if(S.product==='LPG'){for(const [key,label] of [['REGIONAL','Региональные ЦА'],['PLATTS','Platts']]){const x=el('button','',label);x.type='button';x.setAttribute('aria-pressed',S.source===key?'true':'false');x.onclick=()=>{S.source=key;render()};b.append(x)}}else{const p=el('button','','Platts');p.type='button';p.setAttribute('aria-pressed',S.source==='PLATTS'?'true':'false');p.onclick=()=>{S.source='PLATTS';render()};const a=el('button','','Argus');a.type='button';a.setAttribute('aria-pressed',S.source==='ARGUS'?'true':'false');a.onclick=()=>{S.source='ARGUS';render()};if(S.product==='DT')a.disabled=true;b.append(p,a)}c.append(b);r.append(c)}
function market(r){const p=DATA.products[S.product],w=el('div','an2-main');if(S.source==='ARGUS'){w.append(card('Argus · базовая котировка',el('div','an2-empty',DATA.argus.reason),el('div','rona-owner-muted',DATA.argus.required)),forecast(p,p.series.PLATTS));r.append(w);return}const s=series(p),c=card('Динамика '+p.name+' · '+s.label+' · USD/т');c.classList.add('an2-chart');c.append(chart(s),el('div','rona-owner-muted an2-basis',s.basis));w.append(c,forecast(p,s));r.append(w)}
function rona(r){const p=DATA.products[S.product],c=p.scenario,g=el('div','an2-rona-grid');if(S.product==='LPG'){p.rona.bases.forEach(x=>{const z=card('');z.classList.add('an2-price-card');z.append(el('h3','',x[0]),el('div','an2-price-base',fmt(x[1],2)+' USD/т'),el('div','an2-price-current',x[0].includes('Сарыагаш')?'R2 working reference · Petromarket 725–780 USD/т':'R2 working reference'));g.append(z)});const h=el('div','an2-rona-head');h.append(el('h2','','Возможные цены RONA Trade на 09.2026'),pill('INDICATIVE · ОТДЕЛЬНЫЙ БАЗИС','info'));const box=card('');box.classList.add('an2-rona');box.append(h,g,el('div','an2-model-note','Platts propane CIF NWE, Hairatan domestic LPG и региональные DAP/CPT имеют разные базисы. R2 references не пересчитываются из Platts без подтверждённого bridge.'));r.append(box);return}p.rona.bases.forEach(x=>{const cur=x[1],z=card('');z.classList.add('an2-price-card');z.append(el('h3','',x[0]),el('div','an2-price-base',fmt(cur+(c.base-p.rona.reference),2)+' USD/т'),el('div','an2-price-range','LOW '+fmt(cur+(c.low-p.rona.reference),2)+' · HIGH '+fmt(cur+(c.high-p.rona.reference),2)),el('div','an2-price-current','Текущий R2: '+fmt(cur,2)+' USD/т'));g.append(z)});const h=el('div','an2-rona-head');h.append(el('h2','','Возможные цены RONA Trade на 09.2026'),pill('INDICATIVE · МОДЕЛЬ НА ПЕРЕСМОТРЕ','warn'));const box=card('');box.classList.add('an2-rona');box.append(h,g,el('div','an2-model-note','Старый LOW / BASE / HIGH сохранён только как контрольный model-layer и не считается текущим рыночным прогнозом до перекалибровки.'));r.append(box)}
function analysis(p){if(S.product==='LPG'){const ps=stats(p.series.PLATTS.values),rs=stats(p.series.REGIONAL.values),s=p.series.PLATTS,g=(s.sep/ps.last-1)*100,open=S.source==='REGIONAL'?'Текущая ситуация. Оперативный Hairatan/региональный ряд достиг '+fmt(rs.last,2)+' USD/т на '+p.series.REGIONAL.lastDate+', '+(rs.d1>=0?'+':'')+fmt(rs.d1,2)+' USD/т к предыдущему наблюдению. Это локальный физический сигнал, а не Platts-базис.':'Текущая ситуация. Platts propane balance-month на '+s.lastDate+' — '+fmt(ps.last,2)+' USD/т, '+(ps.d1>=0?'+':'')+fmt(ps.d1,2)+' USD/т к предыдущему наблюдению.';return open+'\n\nПрогнозный контур. Platts Sep '+fmt(s.sep,2)+' и Oct '+fmt(s.oct,2)+' USD/т; сентябрь '+fmt(Math.abs(g),1)+'% '+(g<0?'ниже':'выше')+' последнего balance-month. Sep/Oct почти flat: рынок не продолжает августовский рост тем же темпом, но и не закладывает резкого падения.\n\nЦентральная Азия. DAP Сарыагаш 725–780 USD/т, CPT Галаба 750–790 USD/т находятся на другом delivered-базисе. Разрыв с Platts отражает географию, логистику и физическую доступность ресурса, а не готовую торговую маржу. Активный спрос в Узбекистане поддерживает региональные цены; иранское предложение в Афганистане ограничивает верхний потенциал.\n\nКоммерческий вывод. Platts используется как европейский ценовой и forward-сигнал; Hairatan, Petromarket и Argus — как отдельные региональные comparators. Сводить их в один LOW/BASE/HIGH без нормализации базиса нельзя.'}const s=p.series.PLATTS,st=stats(s.values),g=(s.sep/st.last-1)*100,a=(st.last/st.avg-1)*100;let mid=S.product==='AI92'?'Последний FACT на '+pct(a)+' выше MTD; Sep forward ниже prompt на '+pct(Math.abs(g))+'. Это частичная нормализация после напряжённого prompt, а не возврат к раннеавгустовским минимумам.':S.product==='AI95'?'Базовый FACT и raw Platts forward совпадают с бензиновым индексом АИ-92; +40 USD/т grade planning вынесен в отдельный слой и не искажает график.':'Composite находится у максимумов месяца: FACT на '+pct(a)+' выше MTD, Sep paper ниже prompt на '+pct(Math.abs(g))+'. Это ослабление давления, но не дешёвый рынок.';return 'Текущая ситуация. '+p.name+': FACT '+fmt(st.last,3)+' USD/т на '+s.lastDate+', '+(st.d1>=0?'+':'')+fmt(st.d1,3)+' USD/т ('+(st.d1pct>=0?'+':'')+pct(st.d1pct)+') к предыдущему наблюдению. MTD '+fmt(st.avg,2)+' USD/т.\n\nРыночная интерпретация. '+mid+' Кривая Sep/Oct: '+curve(s)+'.\n\nПрогноз. Sep forward '+fmt(s.sep,3)+', Oct '+fmt(s.oct,3)+' USD/т. LOW / BASE / HIGH '+fmt(p.scenario.low,0)+' / '+fmt(p.scenario.base,0)+' / '+fmt(p.scenario.high,0)+' не пересчитан после Platts 21.08, поэтому маркируется «модель на пересмотре».\n\nКоммерческий вывод. Новые предложения следует проверять по свежему Platts, forward-кривой и сопоставимому regional delivered-benchmark; срок действия котировки должен быть коротким.'}
function comment(r){r.append(card('Комментарий Коммерческого директора',el('div','an2-comment',analysis(DATA.products[S.product])),el('div','rona-owner-muted','Источник: RONA Market Intelligence '+DATA.version+' · source cut-off '+DATA.sourceCutoff+'. FACT / CALCULATION / FORECAST / regional benchmark разделены.'))}
function render(){const r=root();if(!r)return false;r.replaceChildren();header(r);kpis(r);controls(r);market(r);rona(r);comment(r);document.documentElement.dataset.ronaAnalyticsUi='v4-market-consistency-lpg-platts';window.__RONA_ANALYTICS_V2_READY__=true;return true}
function bind(){render();const p=page();if(p&&!p.__an2Obs){p.__an2Obs=true;new MutationObserver(()=>{const r=q('#rona-analytics-v2',p);if(r)for(const x of qa(':scope>*',p))if(x!==r)x.style.setProperty('display','none','important')}).observe(p,{childList:true})}}
let tries=0;(function wait(){if(window.__RONA_OWNER_ADMIN_READY__===true&&page())return bind();if(++tries<1200)setTimeout(wait,50)})();
})();`;
export async function onRequest(){return new Response(SCRIPT,{status:200,headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache','expires':'0','x-content-type-options':'nosniff','x-rona-analytics-ui':'v4-market-consistency-lpg-platts','x-rona-analytics-source':'1.1.9-SF5-20260822-2203'}})}
