const SCRIPT=String.raw`(()=>{'use strict';
if(window.__RONA_ANALYTICS_V2__)return;
window.__RONA_ANALYTICS_V2__='20260824-analytics-bnk-v2-values-table';
const DATA={version:'1.1.9-SF5-20260822-2203',cutoff:'22.08.2026 22:03 +03:00',latestTradeDate:'21.08.2026',products:{
'AI92':{name:'АИ-92',basis:'Platts European Marketscan · Gasoline Prem Unleaded 10 ppm · FOB Med (Italy)',dates:['03.08','04.08','05.08','06.08','07.08','10.08','11.08','13.08','14.08','17.08','19.08','21.08'],values:[1035.25,984.75,988.75,1020.50,1066.50,1109.25,1105.25,1119.25,1109.50,1109.25,1154.25,1186.75],forecast:{month:'09.2026',forward:1079.50,mtd:1082.4375,low:930,base:1025,high:1120,direction:'Снижение',confidence:'Средняя',curve:'Бэквордация',comment:'Физический FOB Med на 21.08 достиг 1 186,75 USD/т, тогда как сентябрьский forward составляет 1 079,50 USD/т. Prompt-рынок остается выше forward; действующий коридор 930–1 120 USD/т сохраняется до отдельного пересмотра. Для коммерческого решения требуется короткий срок действия котировки и свежий региональный сопоставимый ориентир.'}},
'AI95':{name:'АИ-95',basis:'Platts European Marketscan · Gasoline Prem Unleaded 10 ppm · FOB Med (Italy) · FACT без grade adjustment',dates:['03.08','04.08','05.08','06.08','07.08','10.08','11.08','13.08','14.08','17.08','19.08','21.08'],values:[1035.25,984.75,988.75,1020.50,1066.50,1109.25,1105.25,1119.25,1109.50,1109.25,1154.25,1186.75],forecast:{month:'09.2026',forward:1119.50,mtd:1122.4375,low:970,base:1065,high:1160,direction:'Снижение',confidence:'Средняя',curve:'Бэквордация',comment:'В FACT АИ-95 использует тот же базовый бензиновый индекс без надбавки за сорт. В прогнозном planning-layer сохраняется отдельный +40 USD/т grade differential: сентябрьский ориентир 1 119,50 USD/т остается внутри коридора, но заметно выше BASE. Надбавка является индикативной и не должна превращаться в DAP-цену без регионального bridge.'}},
'DT':{name:'ДТ',basis:'BNK Diesel Composite · среднее ULSD 10 ppm / Cargoes CIF NWE/Basis ARA и Diesel 10 ppm / Barges FOB Rotterdam',dates:['03.08','04.08','05.08','06.08','07.08','10.08','11.08','13.08','14.08','17.08','19.08','21.08'],values:[1218.125,1147.625,1185.25,1182.375,1206.375,1305.00,1299.75,1312.25,1322.25,1343.25,1360.75,1363.875],forecast:{month:'09.2026',forward:1315.625,mtd:1270.572916666667,low:1160,base:1240,high:1325,direction:'Снижение',confidence:'Средняя',curve:'Бэквордация',comment:'Расчетный BNK composite на 21.08 достиг 1 363,875 USD/т. Сентябрьский paper composite 1 315,625 USD/т находится всего на 9,375 USD/т ниже текущего HIGH 1 325. Прогноз приблизился к верхней границе; новый коммерческий ориентир следует сверять с актуальными региональными delivered-benchmarks до выпуска.'}}
},argus:{available:false,required:'Argus European Products · EUROBOB Oxy · Northwest Europe - barge',reason:'Корректный ряд Argus European Products, требуемый процедурой БНК для бензинов, в текущем структурированном контуре не загружен. Региональные серии Argus не подставляются вместо требуемого индекса.'}};
const S={product:'AI92',source:'PLATTS'};
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const el=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!==undefined&&x!==null)n.textContent=String(x);return n};
const fmt=(v,d=2)=>Number.isFinite(Number(v))?new Intl.NumberFormat('ru-RU',{minimumFractionDigits:d,maximumFractionDigits:d}).format(Number(v)):'—';
function page(){return q('#page-analytics')}
function pill(t,tone='neutral'){return el('span','rona-fin-pill rona-fin-pill--'+tone,t)}
function card(title){const c=el('section','rona-owner-card');if(title)c.append(el('h2','',title));for(let i=1;i<arguments.length;i++)if(arguments[i])c.append(arguments[i]);return c}
function kpi(title,value,caption){const c=card(title,el('div','rona-owner-kpi',value),el('div','rona-owner-muted',caption));return c}
function style(){if(q('#ronaAnalyticsV2Style'))return;const s=el('style');s.id='ronaAnalyticsV2Style';s.textContent=[
'#page-analytics>#rona-analytics-v2{display:grid!important;visibility:visible!important;opacity:1!important}',
'#page-analytics>*:not(#rona-analytics-v2){display:none!important;visibility:hidden!important}',
'.an2{width:100%;max-width:none;margin:0;gap:14px;box-sizing:border-box}',
'.an2-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;flex-wrap:wrap}.an2-head h1{margin:0 0 6px;font-size:24px;line-height:1.2;font-weight:800}.an2-head p{margin:0;max-width:880px}',
'.an2-kpis{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}',
'.an2-controls{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.an2-controls button{font:inherit;color:inherit;background:transparent;border:1px solid var(--line,rgba(255,255,255,.22));border-radius:9px;padding:8px 11px;cursor:pointer;font-weight:700}.an2-controls button[aria-pressed="true"]{box-shadow:inset 0 0 0 1px currentColor;background:rgba(255,255,255,.06)}.an2-controls button:disabled{opacity:.45;cursor:not-allowed}',
'.an2-main{display:grid;grid-template-columns:minmax(0,1.72fr) minmax(270px,.58fr);gap:20px;align-items:start}.an2-chart{min-height:390px}.an2-chart svg{display:block;width:100%;height:335px;overflow:visible}.an2-gridline{stroke:currentColor;opacity:.1;stroke-width:1}.an2-axis{font-size:11px;fill:currentColor;opacity:.62}.an2-line{fill:none;stroke:currentColor;stroke-width:3;stroke-linecap:round;stroke-linejoin:round}.an2-dot{fill:currentColor}.an2-point-value{font-size:10px;font-weight:800;fill:currentColor;opacity:.94;paint-order:stroke;stroke:rgba(5,18,33,.9);stroke-width:3px;stroke-linejoin:round}.an2-basis{margin-top:8px}',
'.an2-data-panel{background:transparent!important;border:0!important;box-shadow:none!important;padding:2px 0 0!important;margin:0!important;min-width:0}.an2-data-title{font-size:13px;font-weight:800;margin:0 0 8px}.an2-data-table{width:100%;border-collapse:collapse;background:transparent!important;font-size:12px}.an2-data-table th,.an2-data-table td{background:transparent!important;padding:5px 4px;border:0;border-bottom:1px solid var(--line-soft,rgba(255,255,255,.11));white-space:nowrap}.an2-data-table th{text-align:left;font-size:10px;text-transform:uppercase;letter-spacing:.05em;opacity:.62;font-weight:700}.an2-data-table th:last-child,.an2-data-table td:last-child{text-align:right}.an2-data-table td:last-child{font-weight:800;font-variant-numeric:tabular-nums}.an2-data-table tbody tr:last-child td{border-bottom:1px solid var(--line,rgba(255,255,255,.24))}.an2-data-table tfoot td{border-bottom:0;padding-top:6px;opacity:.9}.an2-data-table tfoot td:first-child{font-weight:700;opacity:.68}.an2-data-table tfoot tr:first-child td{padding-top:10px}',
'.an2-forecast{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.an2-forecast .rona-owner-card{margin-bottom:0}.an2-value{font-size:24px;font-weight:800;margin:8px 0 4px}.an2-comment{line-height:1.6;font-size:13px;white-space:pre-wrap}.an2-empty{padding:20px;border:1px dashed var(--line-soft,rgba(255,255,255,.18));border-radius:12px;line-height:1.55}.an2-note{padding:10px 12px;border-left:3px solid currentColor;background:rgba(255,255,255,.025);font-size:12px;line-height:1.5;opacity:.8}',
'@media(max-width:1050px){.an2-main{grid-template-columns:1fr}.an2-data-panel{padding:0!important}.an2-forecast{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:680px){.an2-kpis,.an2-forecast{grid-template-columns:1fr}.an2-controls{display:grid}.an2-controls button{width:100%}.an2-chart svg{height:285px}.an2-point-value{font-size:9px}}'
].join('');document.head.append(s)}
function ensureRoot(){const p=page();if(!p)return null;style();let r=q('#rona-analytics-v2',p);if(!r){r=el('section','an2');r.id='rona-analytics-v2';p.insertBefore(r,p.firstChild)}for(const x of qa(':scope>*',p))if(x!==r){x.style.setProperty('display','none','important');x.setAttribute('aria-hidden','true')}return r}
function stats(values){const a=values.map(Number).filter(Number.isFinite),last=a[a.length-1],prev=a[a.length-2],first=a[0];return{last,avg:a.reduce((x,y)=>x+y,0)/a.length,min:Math.min(...a),max:Math.max(...a),d1:last-prev,d1pct:(last/prev-1)*100,mtd:last-first,mtdpct:(last/first-1)*100,count:a.length}}
function chart(product){const v=product.values,d=product.dates,w=900,h=320,pad={l:62,r:28,t:42,b:44},min=Math.min(...v),max=Math.max(...v),span=Math.max(1,max-min),lo=min-span*.14,hi=max+span*.16,x=i=>pad.l+(w-pad.l-pad.r)*(i/(v.length-1)),y=n=>pad.t+(h-pad.t-pad.b)*(1-(n-lo)/(hi-lo));const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 '+w+' '+h);for(let i=0;i<5;i++){const yy=pad.t+(h-pad.t-pad.b)*i/4,line=document.createElementNS(svg.namespaceURI,'line');line.setAttribute('x1',pad.l);line.setAttribute('x2',w-pad.r);line.setAttribute('y1',yy);line.setAttribute('y2',yy);line.setAttribute('class','an2-gridline');svg.append(line);const tx=document.createElementNS(svg.namespaceURI,'text');tx.setAttribute('x',4);tx.setAttribute('y',yy+4);tx.setAttribute('class','an2-axis');tx.textContent=fmt(hi-(hi-lo)*i/4,0);svg.append(tx)}const pts=v.map((n,i)=>x(i)+','+y(n)).join(' '),pl=document.createElementNS(svg.namespaceURI,'polyline');pl.setAttribute('points',pts);pl.setAttribute('class','an2-line');svg.append(pl);v.forEach((n,i)=>{const c=document.createElementNS(svg.namespaceURI,'circle');c.setAttribute('cx',x(i));c.setAttribute('cy',y(n));c.setAttribute('r','3.8');c.setAttribute('class','an2-dot');const tt=document.createElementNS(svg.namespaceURI,'title');tt.textContent=d[i]+' · '+fmt(n,2)+' USD/т';c.append(tt);svg.append(c);const val=document.createElementNS(svg.namespaceURI,'text');val.setAttribute('x',x(i));val.setAttribute('y',y(n)+(i%2===0?-11:17));val.setAttribute('text-anchor','middle');val.setAttribute('class','an2-point-value');val.textContent=fmt(n,2);svg.append(val);if(i===0||i===v.length-1||i%2===1){const tx=document.createElementNS(svg.namespaceURI,'text');tx.setAttribute('x',x(i));tx.setAttribute('y',h-12);tx.setAttribute('text-anchor','middle');tx.setAttribute('class','an2-axis');tx.textContent=d[i];svg.append(tx)}});return svg}
function valuesTable(product,st){const panel=el('div','an2-data-panel'),title=el('div','an2-data-title','Значения котировок'),table=el('table','an2-data-table'),thead=document.createElement('thead'),hr=document.createElement('tr'),h1=document.createElement('th'),h2=document.createElement('th');h1.textContent='Дата';h2.textContent='USD/т';hr.append(h1,h2);thead.append(hr);const tbody=document.createElement('tbody');product.dates.forEach((date,i)=>{const tr=document.createElement('tr'),td1=document.createElement('td'),td2=document.createElement('td');td1.textContent=date;td2.textContent=fmt(product.values[i],2);tr.append(td1,td2);tbody.append(tr)});const tfoot=document.createElement('tfoot');[['Последняя',st.last],['MTD среднее',st.avg],['Min',st.min],['Max',st.max]].forEach(a=>{const tr=document.createElement('tr'),td1=document.createElement('td'),td2=document.createElement('td');td1.textContent=a[0];td2.textContent=fmt(a[1],2);tr.append(td1,td2);tfoot.append(tr)});table.append(thead,tbody,tfoot);panel.append(title,table);return panel}
function header(r){const h=el('section','rona-owner-card an2-head'),copy=el('div');copy.append(el('h1','','Аналитика'),el('p','rona-owner-muted','Рыночная аналитика Коммерческого директора: динамика базовых котировок по процедуре БНК, прогноз следующего месяца и краткое аналитическое обоснование.'));h.append(copy,pill('Внутренний аналитический контур','info'));r.append(h)}
function topKpis(r){const f=DATA.products[S.product].forecast,g=el('div','an2-kpis');g.append(kpi('Platts',DATA.latestTradeDate,'Последний подтверждённый торговый день'),kpi('Argus',DATA.argus.available?'Доступен':'Нет ряда','Только Argus European Products / EUROBOB Oxy'),kpi('Прогноз',f.month,'LOW / BASE / HIGH · индикативно'));r.append(g)}
function controls(r){const c=card('Базовая котировка'),bar=el('div','an2-controls');['AI92','AI95','DT'].forEach(k=>{const b=el('button','',DATA.products[k].name);b.type='button';b.setAttribute('aria-pressed',S.product===k?'true':'false');b.onclick=()=>{S.product=k;if(k==='DT')S.source='PLATTS';render()};bar.append(b)});const sep=el('span','rona-owner-muted','Источник:');bar.append(sep);const bp=el('button','','Platts');bp.type='button';bp.setAttribute('aria-pressed',S.source==='PLATTS'?'true':'false');bp.onclick=()=>{S.source='PLATTS';render()};const ba=el('button','','Argus');ba.type='button';ba.setAttribute('aria-pressed',S.source==='ARGUS'?'true':'false');ba.onclick=()=>{S.source='ARGUS';render()};if(S.product==='DT'){ba.disabled=true;ba.title='В текущей процедуре БНК для этого дизельного контура используется Platts.'}bar.append(bp,ba);c.append(bar);r.append(c)}
function marketBlock(r){const p=DATA.products[S.product];if(S.source==='ARGUS'){r.append(card('Argus · базовая котировка',el('div','an2-empty',DATA.argus.reason),el('div','an2-note','Требуемый базис: '+DATA.argus.required+'. Региональные издания Argus и иные серии не подменяют этот индекс.')));return}const st=stats(p.values),wrap=el('div','an2-main'),cc=card('Динамика '+p.name+' · USD/т');cc.classList.add('an2-chart');cc.append(chart(p),el('div','rona-owner-muted an2-basis',p.basis));wrap.append(cc,valuesTable(p,st));r.append(wrap)}
function forecast(r){const f=DATA.products[S.product].forecast,g=el('div','an2-forecast');[['LOW',f.low,'Нижний сценарий'],['BASE',f.base,'Базовый сценарий'],['HIGH',f.high,'Верхний сценарий'],['Forward',f.forward,'Сентябрьский рыночный ориентир']].forEach(a=>{const c=card(a[0]);c.append(el('div','an2-value',fmt(a[1],2)+' USD/т'),el('div','rona-owner-muted',a[2]));g.append(c)});r.append(card('Прогноз на '+f.month,g,el('div','an2-note','Направление: '+f.direction+' · Уверенность: '+f.confidence+' · Кривая: '+f.curve+'. Прогноз является индикативным и не является офертой или подтверждённой DAP-ценой.')))}
function commentary(r){const f=DATA.products[S.product].forecast;r.append(card('Комментарий Коммерческого директора',el('div','an2-comment',f.comment),el('div','rona-owner-muted','Источник аналитического среза: RONA Market Intelligence '+DATA.version+' · cutoff '+DATA.cutoff+'. FACT / CALCULATION / FORECAST разделены.')))}
function render(){const r=ensureRoot();if(!r)return false;r.replaceChildren();header(r);topKpis(r);controls(r);marketBlock(r);forecast(r);commentary(r);document.documentElement.classList.add('rona-analytics-v2-ready');document.documentElement.dataset.ronaAnalyticsUi='v2-bnk-values-table';window.__RONA_ANALYTICS_V2_READY__=true;return true}
function bind(){render();const p=page();if(p&&!p.__ronaAnalyticsV2Observer){p.__ronaAnalyticsV2Observer=true;new MutationObserver(()=>{const r=q('#rona-analytics-v2',p);if(!r)return;for(const x of qa(':scope>*',p))if(x!==r){x.style.setProperty('display','none','important');x.setAttribute('aria-hidden','true')}}).observe(p,{childList:true})}}
let tries=0;(function wait(){if(window.__RONA_OWNER_ADMIN_READY__===true&&page()){bind();return}tries++;if(tries<1200)setTimeout(wait,50)})();
})();`;
export async function onRequest(){return new Response(SCRIPT,{status:200,headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache','expires':'0','x-content-type-options':'nosniff','x-rona-analytics-ui':'v2-bnk-values-table','x-rona-analytics-source':'1.1.9-SF5-20260822-2203'}})}
