const SCRIPT=String.raw`(function(){
'use strict';
if(window.__RONA_CASH_R2_UI__)return;
window.__RONA_CASH_R2_UI__='20260823-2145';
var cashFilter='ALL',lastStamp='';
function q(s,r){return(r||document).querySelector(s)}
function qa(s,r){return Array.from((r||document).querySelectorAll(s))}
function el(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined&&text!==null)n.textContent=String(text);return n}
function money(v,c){if(v===null||v===undefined||v==='')return'—';var n=Number(v);return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n)+(c?' '+c:'')}
function d(v){if(!v)return'—';var x=new Date(v);return Number.isNaN(x.getTime())?String(v):x.toLocaleDateString('ru-RU')}
function snapshot(){return window.__RONA_OWNER_AI_SYNC_SNAPSHOT__&&window.__RONA_OWNER_AI_SYNC_SNAPSHOT__.financeFragment||null}
function ensureStyle(){if(q('#ronaCashR2Style'))return;var s=el('style');s.id='ronaCashR2Style';s.textContent='#page-accounting .rona-cash-r2{width:100%}#page-accounting .rona-cash-kpis{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-bottom:14px}#page-accounting .rona-cash-kpi{min-height:132px;padding:16px;border:1px solid var(--line,rgba(255,255,255,.18));border-radius:14px;box-sizing:border-box}#page-accounting .rona-cash-kpi h2{margin:0 0 12px;font-size:16px}#page-accounting .rona-cash-kpi--balance{border-color:rgba(34,197,94,.42);background:rgba(34,197,94,.08)}#page-accounting .rona-cash-kpi--received{border-color:rgba(59,130,246,.44);background:rgba(59,130,246,.08)}#page-accounting .rona-cash-kpi--paid{border-color:rgba(148,163,184,.34);background:rgba(148,163,184,.07)}#page-accounting .rona-cash-kpi-line{display:flex;justify-content:space-between;gap:12px;align-items:baseline;margin:5px 0}#page-accounting .rona-cash-kpi-value{font-size:24px;font-weight:800}#page-accounting .rona-cash-kpi-cur{font-size:12px;font-weight:800;opacity:.72}#page-accounting .rona-cash-filter{display:flex;gap:8px;flex-wrap:wrap;margin:2px 0 14px}#page-accounting .rona-cash-filter button{font:inherit;color:inherit;background:transparent;border:1px solid var(--line,rgba(255,255,255,.22));border-radius:999px;padding:8px 13px;cursor:pointer;font-weight:800}#page-accounting .rona-cash-filter button[aria-pressed="true"]{box-shadow:inset 0 0 0 1px currentColor;background:rgba(59,130,246,.10);border-color:rgba(59,130,246,.45)}#page-accounting .rona-cash-card{padding:16px;border:1px solid var(--line,rgba(255,255,255,.18));border-radius:14px;margin:0 0 14px;box-sizing:border-box}#page-accounting .rona-cash-card h2{margin:0 0 10px}#page-accounting .rona-cash-note{opacity:.72;font-size:12px;line-height:1.45;margin-bottom:12px}#page-accounting .rona-cash-table-wrap{overflow-x:auto;width:100%}#page-accounting .rona-cash-table{width:100%;border-collapse:collapse;font-size:13px;min-width:760px}#page-accounting .rona-cash-table th,#page-accounting .rona-cash-table td{text-align:center;vertical-align:middle;padding:12px 10px;border-bottom:1px solid var(--line-soft,rgba(255,255,255,.12));line-height:1.35}#page-accounting .rona-cash-table th{white-space:nowrap}#page-accounting .rona-cash-confirmed{display:inline-flex;align-items:center;justify-content:center;padding:3px 8px;border-radius:999px;font-size:11px;font-weight:800;color:#16a34a;background:rgba(34,197,94,.11);border:1px solid rgba(34,197,94,.35)}@media(max-width:900px){#page-accounting .rona-cash-kpis{grid-template-columns:1fr}}';document.head.append(s)}
function kpi(title,cls,rows,key){var c=el('section','rona-cash-kpi '+cls),h=el('h2','',title),body=el('div');c.append(h,body);rows.forEach(function(x){var line=el('div','rona-cash-kpi-line');line.append(el('span','rona-cash-kpi-value',money(x[key],x.currency)),el('span','rona-cash-kpi-cur',x.currency));body.append(line)});return c}
function table(rows){var wrap=el('div','rona-cash-table-wrap'),t=el('table','rona-cash-table'),head=el('thead'),hr=el('tr'),body=el('tbody');['Дата','Валюта','Остаток на начало','Поступило','Списано','Остаток на конец','Статус'].forEach(function(x){hr.append(el('th','',x))});head.append(hr);rows.forEach(function(x){var tr=el('tr');[d(x.snapshot_date),x.currency,money(x.opening_balance,x.currency),money(x.received_amount,x.currency),money(x.paid_amount,x.currency),money(x.closing_balance,x.currency)].forEach(function(v){tr.append(el('td','',v))});var st=el('td');st.append(el('span','rona-cash-confirmed','Подтверждено'));tr.append(st);body.append(tr)});t.append(head,body);wrap.append(t);return wrap}
function host(){var page=q('#page-accounting');if(!page)return null;return q(':scope > .rona-owner-page-content',page)||q('.rona-owner-page-content[data-owner-page="accounting"]',page)||page}
function render(){ensureStyle();var f=snapshot(),h=host();if(!h||!f)return;var rows=Array.isArray(f.cash)?f.cash.slice():[];if(!rows.length)return;rows.sort(function(a,b){var o={USD:1,RUB:2,KZT:3},ca=String(a.currency||''),cb=String(b.currency||'');return(o[ca]||99)-(o[cb]||99)||ca.localeCompare(cb)});var stamp=JSON.stringify([cashFilter,f.sourceAsOf,rows.map(function(x){return[x.snapshot_date,x.currency,x.opening_balance,x.received_amount,x.paid_amount,x.closing_balance]})]);if(lastStamp===stamp&&q('#ronaCashR2Root',h))return;lastStamp=stamp;var visible=cashFilter==='ALL'?rows:rows.filter(function(x){return String(x.currency||'')===cashFilter}),root=el('div','rona-cash-r2');root.id='ronaCashR2Root';var grid=el('div','rona-cash-kpis');grid.append(kpi('Остаток на конец','rona-cash-kpi--balance',rows,'closing_balance'),kpi('Поступило','rona-cash-kpi--received',rows,'received_amount'),kpi('Списано','rona-cash-kpi--paid',rows,'paid_amount'));var filter=el('div','rona-cash-filter'),currencies=['ALL'].concat(rows.map(function(x){return String(x.currency||'')}).filter(Boolean).filter(function(v,i,a){return a.indexOf(v)===i}));currencies.forEach(function(v){var b=el('button','',v==='ALL'?'Все':v);b.type='button';b.setAttribute('aria-pressed',String(cashFilter===v));b.onclick=function(){cashFilter=v;lastStamp='';render()};filter.append(b)});var card=el('section','rona-cash-card'),title=el('h2','','Движение денежных средств'),note=el('div','rona-cash-note','Банковская сверка на '+d(f.sourceAsOf)+'. Поступления и списания — накопительно с начала III квартала; остаток — на конец даты снимка.');card.append(title,note,table(visible));root.append(grid,filter,card);h.replaceChildren(root)}
function start(){render();window.addEventListener('rona:finance-sync',function(){lastStamp='';render()});document.addEventListener('click',function(ev){var b=ev.target&&ev.target.closest?ev.target.closest('#nav button[data-page="accounting"]'):null;if(b)setTimeout(function(){lastStamp='';render()},0)},true)}
if(location.pathname==='/portal/admin'){var tries=0;(function wait(){if(window.__RONA_OWNER_ADMIN_READY__===true){start();return}if(++tries<1200)setTimeout(wait,100)})()}
})();`;
export async function onRequest(){return new Response(SCRIPT,{status:200,headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache','expires':'0','x-content-type-options':'nosniff','x-rona-cash-ui':'r2'}})}
