import { onRequest as basePortal } from './[[path]].js';
const PREPAINT='<meta name="rona-ui-primary" content="main-v2"><style id="rona-owner-prepaint-gate">html:not(.rona-owner-paint-ready) body>*:not(script):not(style){opacity:0!important;visibility:hidden!important;pointer-events:none!important}html:not(.rona-owner-paint-ready) body{cursor:wait}</style>';
const LOADER='<script id="rona-main-ui-loader" src="/portal/main-ui" defer data-rona-ui="primary"></script>';
const R1='<script id="rona-deals-r1-loader" src="/portal/deals-r1-ui" async data-rona-ui="deals-r1-isolated"></script>';
const CLAIMS='<script id="rona-client-claims-loader" src="/portal/client-claims-ui" defer data-rona-ui="client-claims-bidirectional-v1"></script>';
const NEWS='<script id="rona-market-news-global-loader" src="/assets/portal-market-news-global-v1.js?v=20260827-auto-all-lk-v1" defer data-rona-ui="market-news-auto-all-lk-v1"></script>';
function injectPrepaint(source){if(source.includes('name="rona-ui-primary"'))return source;const lower=source.toLowerCase(),i=lower.indexOf('</head>');if(i<0)return PREPAINT+source;return source.slice(0,i)+PREPAINT+source.slice(i)}
function injectLoader(source){if(source.includes('id="rona-main-ui-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+LOADER;return source.slice(0,i)+LOADER+source.slice(i)}
function injectR1(source){if(source.includes('id="rona-deals-r1-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+R1;return source.slice(0,i)+R1+source.slice(i)}
function injectClaims(source){if(source.includes('id="rona-client-claims-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+CLAIMS;return source.slice(0,i)+CLAIMS+source.slice(i)}
function injectNews(source){if(source.includes('id="rona-market-news-global-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+NEWS;return source.slice(0,i)+NEWS+source.slice(i)}
export async function onRequest(context){const response=await basePortal(context);const ct=response.headers.get('content-type')||'';if(response.status!==200||!ct.toLowerCase().includes('text/html'))return response;let source=await response.text();source=injectPrepaint(source);source=injectLoader(source);source=injectR1(source);source=injectClaims(source);source=injectNews(source);const h=new Headers(response.headers);h.delete('content-length');h.delete('etag');h.set('x-rona-ui','main-v2');h.set('x-rona-r1-ui','isolated-v1');h.set('x-rona-client-claims-ui','bidirectional-v1');h.set('x-rona-market-news','auto-all-lk-v1');return new Response(source,{status:response.status,statusText:response.statusText,headers:h})}
