// RONA_CLIENT_SESSION_SCOPE_GATE_V2_20260828
const SUPABASE_URL='https://sxawrwzeobaqwwmlkzws.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_W2MxTx00ILiugSyZKp8uyQ_zBzcyorL';
const PORTAL_API=`${SUPABASE_URL}/functions/v1/rona-portal-api`;
const ACCESS_COOKIE='rona_portal_at';
const REFRESH_COOKIE='rona_portal_rt';
const CSP="default-src 'self' data: blob:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; font-src 'self' data:; frame-ancestors 'none'; base-uri 'none'; object-src 'none'; form-action 'self'";
const SECURITY_HEADERS=Object.freeze({'cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache','referrer-policy':'no-referrer','x-content-type-options':'nosniff','x-frame-options':'DENY','permissions-policy':'camera=(), microphone=(), geolocation=(), payment=()','cross-origin-opener-policy':'same-origin','cross-origin-resource-policy':'same-origin','content-security-policy':CSP});
const PREPAINT='<meta name="rona-ui-primary" content="main-v2"><style id="rona-owner-prepaint-gate">html:not(.rona-owner-paint-ready) body>*:not(script):not(style){opacity:0!important;visibility:hidden!important;pointer-events:none!important}html:not(.rona-owner-paint-ready) body{cursor:wait}</style>';
const LOADER='<script id="rona-main-ui-loader" src="/portal/main-ui" defer data-rona-ui="primary"></script>';
const R1='<script id="rona-deals-r1-loader" src="/portal/deals-r1-ui" async data-rona-ui="deals-r1-isolated"></script>';
const CLAIMS='<script id="rona-client-claims-loader" src="/portal/client-claims-ui" defer data-rona-ui="client-claims-bidirectional-v1"></script>';
const NEWS='<script id="rona-market-news-global-loader" src="/assets/portal-market-news-global-v1.js?v=20260827-auto-all-lk-v1" defer data-rona-ui="market-news-auto-all-lk-v1"></script>';
const SESSION_RETRY_DELAYS_MS=Object.freeze([0,250,500,1000,2000,2500]);
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function parseCookies(header){const out={};for(const item of String(header||'').split(';')){const i=item.indexOf('=');if(i<1)continue;const k=item.slice(0,i).trim(),v=item.slice(i+1).trim();if(k)out[k]=v}return out}
function accessCookie(token,maxAge=3600){return `${ACCESS_COOKIE}=${token}; Max-Age=${Math.max(0,Number(maxAge)||0)}; Path=/portal; Secure; HttpOnly; SameSite=Lax`}
function refreshCookie(token,maxAge=604800){return `${REFRESH_COOKIE}=${token}; Max-Age=${Math.max(0,Number(maxAge)||0)}; Path=/portal; Secure; HttpOnly; SameSite=Lax`}
function tokenCookies(tokens){const expires=Math.min(Math.max(Number(tokens?.expires_in||3600),60),7200);return[accessCookie(tokens.access_token,expires),refreshCookie(tokens.refresh_token,604800)]}
function clearCookies(){return[`${ACCESS_COOKIE}=; Max-Age=0; Path=/portal; Secure; HttpOnly; SameSite=Lax`,`${REFRESH_COOKIE}=; Max-Age=0; Path=/portal; Secure; HttpOnly; SameSite=Lax`]}
function secureHeaders(base=new Headers(),html=true){const h=new Headers(base);for(const[k,v]of Object.entries(SECURITY_HEADERS))h.set(k,v);if(!html)h.delete('content-security-policy');h.delete('access-control-allow-origin');h.delete('access-control-allow-credentials');h.delete('content-length');h.delete('etag');return h}
function appendCookies(headers,cookies=[]){for(const cookie of cookies)headers.append('set-cookie',cookie);return headers}
function redirect(location,status=303,cookies=[]){const h=appendCookies(secureHeaders(new Headers({location}),false),cookies);return new Response(null,{status,headers:h})}
function denied(cookies=[]){const h=appendCookies(secureHeaders(new Headers({'content-type':'text/html; charset=utf-8'}),true),cookies);const body='<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RONA Trade — Доступ запрещён</title><style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#05090d;color:#eef4f7;font:16px Inter,Arial,sans-serif}.box{width:min(520px,calc(100vw - 32px));padding:28px;border:1px solid #29404e;border-radius:16px;background:#0b151d}.muted{color:#93a8b3}.code{font:12px ui-monospace,SFMono-Regular,Consolas,monospace;color:#a8bdc8}</style></head><body><main class="box"><h1>Доступ запрещён</h1><p class="muted">Сервер не подтвердил разрешённый клиентский контекст для этой учётной записи.</p><p class="code">CLIENT_SCOPE_NOT_AUTHORIZED</p></main></body></html>';return new Response(body,{status:403,headers:h})}
function unavailable(cookies=[]){const h=appendCookies(secureHeaders(new Headers({'content-type':'text/html; charset=utf-8','refresh':'2;url=/portal/client'}),true),cookies);h.set('x-rona-client-session-gate','scope-unavailable-v2');const body='<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="2;url=/portal/client"><title>RONA Trade — Восстановление соединения</title><style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#05090d;color:#eef4f7;font:16px Inter,Arial,sans-serif}.box{width:min(520px,calc(100vw - 32px));padding:28px;border:1px solid #29404e;border-radius:16px;background:#0b151d}.muted{color:#93a8b3}.btn{display:inline-block;margin-top:12px;padding:11px 14px;border:1px solid #365464;border-radius:10px;color:#eef4f7;text-decoration:none;background:#101f29}</style></head><body><main class="box"><h1>Восстанавливаю соединение</h1><p class="muted">Сессия сохранена. Серверная проверка клиентского контура временно недоступна; повтор выполняется автоматически.</p><a class="btn" href="/portal/client">Повторить сейчас</a></main></body></html>';return new Response(body,{status:503,headers:h})}
async function authRefresh(refreshToken){try{const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,'content-type':'application/json'},body:JSON.stringify({refresh_token:refreshToken})});const data=await r.json().catch(()=>({}));return{ok:r.ok,status:r.status,data}}catch(_){return{ok:false,status:503,data:null,network:true}}}
async function sessionProbe(accessToken){if(!accessToken)return{state:'INVALID',status:401,data:null};let lastStatus=503;for(const delay of SESSION_RETRY_DELAYS_MS){if(delay)await sleep(delay);try{const r=await fetch(`${PORTAL_API}/session/me`,{method:'GET',headers:{authorization:`Bearer ${accessToken}`,accept:'application/json'},cache:'no-store'});lastStatus=r.status;if(r.ok){const data=await r.json().catch(()=>null);if(data?.ok===true&&data?.user)return{state:'VALID',status:r.status,data};continue}if(r.status===401||r.status===403)return{state:'INVALID',status:r.status,data:null};if(r.status===429||r.status>=500)continue;return{state:'INVALID',status:r.status,data:null}}catch(_){lastStatus=503}}return{state:'UNAVAILABLE',status:lastStatus,data:null}}
function scopeAuthorized(data){const roles=Array.isArray(data?.user?.roles)?data.user.roles.map(String):[],scope=data?.scope&&typeof data.scope==='object'?data.scope:{},clients=Array.isArray(scope.client_ids)?scope.client_ids.filter(Boolean):[],contracts=Array.isArray(scope.contract_ids)?scope.contract_ids.filter(Boolean):[];return roles.includes('CLIENT')&&clients.length>0&&contracts.length>0}
async function ensureClientSession(request){const cookies=parseCookies(request.headers.get('cookie')),refresh=cookies[REFRESH_COOKIE]||'';let access=cookies[ACCESS_COOKIE]||'',setCookies=[];if(access){const probe=await sessionProbe(access);if(probe.state==='VALID')return{state:scopeAuthorized(probe.data)?'AUTHORIZED':'DENIED',setCookies,session:probe.data};if(probe.state==='UNAVAILABLE')return{state:'UNAVAILABLE',setCookies,session:null}}
if(!refresh)return{state:'SIGN_IN',setCookies:clearCookies(),session:null};const next=await authRefresh(refresh);if(!next.ok||!next.data?.access_token||!next.data?.refresh_token){if(next.network||next.status===429||next.status>=500)return{state:'UNAVAILABLE',setCookies,session:null};return{state:'SIGN_IN',setCookies:clearCookies(),session:null}}access=next.data.access_token;setCookies=tokenCookies(next.data);const probe=await sessionProbe(access);if(probe.state==='UNAVAILABLE')return{state:'UNAVAILABLE',setCookies,session:null};if(probe.state!=='VALID')return{state:'SIGN_IN',setCookies:clearCookies(),session:null};return{state:scopeAuthorized(probe.data)?'AUTHORIZED':'DENIED',setCookies,session:probe.data}}
function injectPrepaint(source){if(source.includes('name="rona-ui-primary"'))return source;const lower=source.toLowerCase(),i=lower.indexOf('</head>');if(i<0)return PREPAINT+source;return source.slice(0,i)+PREPAINT+source.slice(i)}
function injectLoader(source){if(source.includes('id="rona-main-ui-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+LOADER;return source.slice(0,i)+LOADER+source.slice(i)}
function injectR1(source){if(source.includes('id="rona-deals-r1-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+R1;return source.slice(0,i)+R1+source.slice(i)}
function injectClaims(source){if(source.includes('id="rona-client-claims-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+CLAIMS;return source.slice(0,i)+CLAIMS+source.slice(i)}
function injectNews(source){if(source.includes('id="rona-market-news-global-loader"'))return source;const lower=source.toLowerCase(),i=lower.lastIndexOf('</body>');if(i<0)return source+NEWS;return source.slice(0,i)+NEWS+source.slice(i)}
export async function onRequest(context){const gate=await ensureClientSession(context.request);if(gate.state==='SIGN_IN')return redirect('/portal/login?next=%2Fportal%2Fclient',303,gate.setCookies);if(gate.state==='UNAVAILABLE')return unavailable(gate.setCookies);if(gate.state==='DENIED')return denied(gate.setCookies);const raw=await context.next();const ct=String(raw.headers.get('content-type')||'').toLowerCase();if(raw.status!==200||!ct.includes('text/html')){const h=appendCookies(secureHeaders(raw.headers,false),gate.setCookies);h.set('x-rona-client-session-gate','session-scope-authorized-v2');return new Response(raw.body,{status:raw.status,statusText:raw.statusText,headers:h})}let source=await raw.text();source=injectPrepaint(source);source=injectLoader(source);source=injectR1(source);source=injectClaims(source);source=injectNews(source);const h=appendCookies(secureHeaders(raw.headers,true),gate.setCookies);h.set('x-rona-ui','main-v2');h.set('x-rona-r1-ui','isolated-v1');h.set('x-rona-client-claims-ui','bidirectional-v1');h.set('x-rona-market-news','auto-all-lk-v1');h.set('x-rona-client-session-gate','session-scope-authorized-v2');return new Response(source,{status:200,statusText:raw.statusText,headers:h})}
