const SUPABASE_URL='https://sxawrwzeobaqwwmlkzws.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_W2MxTx00ILiugSyZKp8uyQ_zBzcyorL';
const PORTAL_API=`${SUPABASE_URL}/functions/v1/rona-portal-api`;
const CONTROL=`${SUPABASE_URL}/functions/v1/rona-owner-bootstrap-control-20260816`;
const ACCESS_COOKIE='rona_portal_at';
const SECURITY={'cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache','referrer-policy':'no-referrer','x-content-type-options':'nosniff','x-frame-options':'DENY','content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'"};
function parseCookies(header){const out={};for(const p of String(header||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=p.slice(i+1).trim();}return out;}
function redirect(location){return new Response(null,{status:303,headers:{...SECURITY,location}})}
async function session(token){if(!token)return null;try{const r=await fetch(`${PORTAL_API}/session/me`,{headers:{authorization:`Bearer ${token}`,accept:'application/json'}});if(!r.ok)return null;const j=await r.json();return j?.ok&&j?.user?j:null}catch{return null}}
async function gate(token){if(!token)return null;try{const r=await fetch(CONTROL,{headers:{authorization:`Bearer ${token}`,accept:'application/json'}});if(!r.ok)return null;const j=await r.json();return j?.ok?j:null}catch{return null}}
function target(roles){const r=Array.isArray(roles)?roles.map(String):[];const out=[];if(r.includes('ADMIN'))out.push('/portal/admin');if(r.includes('RONA_OPERATOR'))out.push('/portal/staff');if(r.includes('AGENT'))out.push('/portal/agent');if(r.includes('CLIENT'))out.push('/portal/client');return out.length>1?'/portal/select':out[0]||null;}
function page(){return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RONA Trade — Вход</title><style>:root{font-family:Inter,Arial,sans-serif;color:#eef4f7;background:#05090d}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:#05090d}.box{width:min(430px,calc(100vw - 32px));padding:28px;border:1px solid #29404e;border-radius:18px;background:#0b151d}h1{margin:0 0 8px}.sub{color:#9db1bc}.field{display:grid;gap:7px;margin:14px 0}.field input{padding:12px;border-radius:10px;border:1px solid #365464;background:#09121a;color:#fff;font:inherit}.btn{width:100%;padding:12px;border-radius:10px;border:1px solid #88414a;background:#3d1c22;color:#fff;font-weight:800}</style></head><body><main class="box"><h1>RONA Trade</h1><p class="sub">Единый вход в защищённые кабинеты</p><form method="post" action="/portal/auth/login" autocomplete="on"><input type="hidden" name="next" id="next"><div class="field"><label for="identifier">Логин</label><input id="identifier" name="identifier" type="text" autocomplete="username" required></div><div class="field"><label for="password">Пароль</label><input id="password" name="password" type="password" autocomplete="current-password" required></div><button class="btn" type="submit">Войти</button></form></main><script>const q=new URLSearchParams(location.search);const n=q.get('next')||'';document.getElementById('next').value=n.startsWith('/portal/')?n:'';</script></body></html>`;}
export async function onRequestGet({request}){const token=parseCookies(request.headers.get('cookie'))[ACCESS_COOKIE]||'';if(token){const s=await session(token);if(s){const g=await gate(token);if(g?.must_change_password)return redirect('/portal/password-reset');const t=target(s.user.roles);if(t)return redirect(t);}}return new Response(page(),{status:200,headers:{...SECURITY,'content-type':'text/html; charset=utf-8'}});}
export function onRequestPost(){return new Response(null,{status:405,headers:SECURITY});}
