const SUPABASE_URL='https://sxawrwzeobaqwwmlkzws.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_W2MxTx00ILiugSyZKp8uyQ_zBzcyorL';
const RPC=`${SUPABASE_URL}/rest/v1/rpc`;
const ACCESS_COOKIE='rona_portal_at';
const REFRESH_COOKIE='rona_portal_rt';
const SECURITY=Object.freeze({'cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache','referrer-policy':'no-referrer','x-content-type-options':'nosniff','x-frame-options':'DENY','permissions-policy':'camera=(), microphone=(), geolocation=(), payment=()'});
function cookies(header){const out={};for(const part of String(header||'').split(';')){const i=part.indexOf('=');if(i<1)continue;out[part.slice(0,i).trim()]=part.slice(i+1).trim()}return out}
function accessCookie(token,maxAge=3600){return `${ACCESS_COOKIE}=${token}; Max-Age=${Math.max(0,Number(maxAge)||0)}; Path=/portal; Secure; HttpOnly; SameSite=Lax`}
function refreshCookie(token,maxAge=604800){return `${REFRESH_COOKIE}=${token}; Max-Age=${Math.max(0,Number(maxAge)||0)}; Path=/portal; Secure; HttpOnly; SameSite=Lax`}
function clearCookies(){return[`${ACCESS_COOKIE}=; Max-Age=0; Path=/portal; Secure; HttpOnly; SameSite=Lax`,`${REFRESH_COOKIE}=; Max-Age=0; Path=/portal; Secure; HttpOnly; SameSite=Lax`]}
function tokenCookies(t){return[accessCookie(t.access_token,Math.min(Math.max(Number(t?.expires_in||3600),60),7200)),refreshCookie(t.refresh_token,604800)]}
function baseHeaders(){const h=new Headers({'content-type':'application/json; charset=utf-8'});for(const[k,v]of Object.entries(SECURITY))h.set(k,v);return h}
function json(body,status=200,set=[]){const h=baseHeaders();for(const c of set)h.append('set-cookie',c);return new Response(JSON.stringify(body),{status,headers:h})}
function sameOrigin(request){const u=new URL(request.url),origin=request.headers.get('origin');if(origin)return origin===u.origin;const ref=request.headers.get('referer');if(!ref)return false;try{return new URL(ref).origin===u.origin}catch{return false}}
async function refresh(token){const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,'content-type':'application/json'},body:JSON.stringify({refresh_token:token})});return{ok:r.ok,data:await r.json().catch(()=>({}))}}
async function rpc(token,name,args={}){return fetch(`${RPC}/${encodeURIComponent(name)}`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,authorization:`Bearer ${token}`,'content-type':'application/json',accept:'application/json'},body:JSON.stringify(args)})}
function spec(op,method,body){if(method==='GET'&&op==='workspace')return['owner_prices_admin_workspace',{}];if(method==='POST'&&op==='request-agent-cp')return['owner_prices_agent_cp_request',{p_publication_id:String(body.publicationId||'')}];if(method==='POST'&&op==='review-agent-cp')return['owner_prices_cp_mark_reviewed',{p_cp_id:String(body.cpId||'')}];if(method==='POST'&&op==='publish')return['owner_prices_publication_action',{p_publication_id:String(body.publicationId||''),p_audience:String(body.audience||'')}];return null}
export async function onRequest(context){const request=context.request;if(!['GET','POST'].includes(request.method))return json({ok:false,code:'METHOD_NOT_ALLOWED'},405);if(request.method==='POST'&&!sameOrigin(request))return json({ok:false,code:'ORIGIN_DENIED'},403);const u=new URL(request.url),op=String(u.searchParams.get('op')||'');let body={};if(request.method==='POST'){try{body=await request.json()}catch{return json({ok:false,code:'INVALID_JSON'},400)}}const call=spec(op,request.method,body);if(!call)return json({ok:false,code:'ROUTE_NOT_ALLOWED'},404);const c=cookies(request.headers.get('cookie'));let access=c[ACCESS_COOKIE]||'',rt=c[REFRESH_COOKIE]||'',set=[];if(!access&&rt){const n=await refresh(rt);if(n.ok&&n.data?.access_token&&n.data?.refresh_token){access=n.data.access_token;rt=n.data.refresh_token;set=tokenCookies(n.data)}}if(!access)return json({ok:false,code:'PORTAL_ACCESS_DENIED'},401,clearCookies());let r=await rpc(access,call[0],call[1]);if(r.status===401&&rt){const n=await refresh(rt);if(n.ok&&n.data?.access_token&&n.data?.refresh_token){access=n.data.access_token;set=tokenCookies(n.data);r=await rpc(access,call[0],call[1])}}const data=await r.json().catch(()=>null);if(r.status===401&&!set.length)return json({ok:false,code:String(data?.message||data?.code||'PORTAL_ACCESS_DENIED')},401,clearCookies());if(!r.ok)return json({ok:false,code:String(data?.message||data?.code||`HTTP_${r.status}`)},r.status,set);return json({ok:true,data},200,set)}
