const SCRIPT=String.raw`(function(){
'use strict';
if(window.__RONA_RAIL_CURRENT_FIRST__)return;
window.__RONA_RAIL_CURRENT_FIRST__='20260824-0231-v3';
window.__RONA_RAIL_2E_ISOLATED__='20260824-0231-v3';
var API='/portal/owner-api',selected='ALL',lastStamp='',timer=null,busy=false,snapshot=null,observer=null,repairQueued=false,tariffNode=null;
function q(s,r){return(r||document).querySelector(s)}
function qa(s,r){return Array.from((r||document).querySelectorAll(s))}
function el(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined&&text!==null)n.textContent=String(text);return n}
function btn(text,pressed,fn){var b=el('button','rona-rail-filter-btn',text);b.type='button';b.setAttribute('aria-pressed',pressed?'true':'false');b.onclick=fn;return b}
function fmtDate(v,withTime){if(!v)return '—';var d=new Date(v);if(Number.isNaN(d.getTime()))return '—';return withTime?d.toLocaleString('ru-RU'):d.toLocaleDateString('ru-RU')}
function pill(text,tone){return el('span','rona-rail-pill rona-rail-pill--'+(tone||'neutral'),text)}
function api(path){return fetch(API+'?path='+encodeURIComponent(path),{credentials:'same-origin',cache:'no-store',headers:{accept:'application/json'}}).then(function(r){return r.json().catch(function(){return{}}).then(function(j){if(!r.ok||j&&j.ok===false)throw new Error(String(j&&j.code||'HTTP_'+r.status));return j&&j.data||{}})})}
function ensureStyle(){if(q('#ronaRailCurrentStyle'))return;var s=el('style');s.id='ronaRailCurrentStyle';s.textContent=[
'#page-monitoring{width:100%!important;max-width:none!important}',
'#page-monitoring>.rona-owner-page-content{width:100%!important;max-width:none!important}',
'#page-monitoring>.rona-owner-page-content:not(:has([data-rail-current-root])){visibility:hidden!important}',
'.rona-rail-root{display:grid;gap:16px;width:100%;max-width:none}',
'.rona-rail-hero{margin:0!important}',
'.rona-rail-workspace{display:grid;grid-template-columns:minmax(300px,.72fr) minmax(620px,1.75fr);gap:16px;align-items:start}',
'.rona-rail-left{display:grid;gap:16px;min-width:0}',
'.rona-rail-card{box-sizing:border-box;margin:0!important}',
'.rona-rail-card h2,.rona-rail-card h3{margin:0 0 12px}',
'.rona-rail-card-header{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:12px}',
'.rona-rail-card-header h2{margin:0}',
'.rona-rail-mini-kpis{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-bottom:14px}',
'.rona-rail-mini-kpi{min-height:88px;padding:13px 14px;border:1px solid rgba(145,185,209,.14);border-radius:14px;background:rgba(6,11,17,.34)}',
'.rona-rail-mini-kpi-label{font-size:11px;line-height:1.35;opacity:.72}',
'.rona-rail-mini-kpi-value{margin-top:7px;font-size:25px;font-weight:900;line-height:1}',
'.rona-rail-filters{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 12px}',
'.rona-rail-filter-btn{font:inherit;color:inherit;background:rgba(6,11,17,.36);border:1px solid var(--line,rgba(255,255,255,.22));border-radius:999px;padding:8px 12px;cursor:pointer;font-weight:800}',
'.rona-rail-filter-btn[aria-pressed=true]{background:rgba(59,130,246,.15);border-color:rgba(89,215,255,.42);box-shadow:inset 0 0 0 1px rgba(89,215,255,.18)}',
'.rona-rail-banner{padding:11px 12px;border-radius:12px;border:1px solid rgba(245,158,11,.32);background:rgba(245,158,11,.07);font-size:12px;line-height:1.45}',
'.rona-rail-table-wrap{width:100%;overflow:auto;border:1px solid rgba(145,185,209,.10);border-radius:14px;background:rgba(6,11,17,.28)}',
'.rona-rail-table{width:100%;min-width:760px;border-collapse:collapse;font-size:12px}',
'.rona-rail-table th,.rona-rail-table td{padding:11px 9px;border-bottom:1px solid var(--line-soft,rgba(255,255,255,.10));text-align:center;vertical-align:middle;line-height:1.4}',
'.rona-rail-table th{white-space:nowrap;font-size:10px;letter-spacing:.07em;text-transform:uppercase;opacity:.75}',
'.rona-rail-ops .rona-rail-table{min-width:0}',
'.rona-rail-ops .rona-rail-table th:nth-child(3),.rona-rail-ops .rona-rail-table td:nth-child(3),.rona-rail-ops .rona-rail-table th:nth-child(4),.rona-rail-ops .rona-rail-table td:nth-child(4){display:none}',
'.rona-rail-pill{display:inline-flex;align-items:center;justify-content:center;text-align:center;padding:4px 9px;border-radius:999px;font-size:11px;font-weight:850;border:1px solid transparent}',
'.rona-rail-pill--success{color:#4ce1b8;background:rgba(34,197,94,.09);border-color:rgba(34,197,94,.28)}',
'.rona-rail-pill--warn{color:#ffc76b;background:rgba(245,158,11,.09);border-color:rgba(245,158,11,.30)}',
'.rona-rail-pill--danger{color:#ff8793;background:rgba(239,68,68,.09);border-color:rgba(239,68,68,.28)}',
'.rona-rail-pill--info{color:#8ee8ff;background:rgba(59,130,246,.09);border-color:rgba(59,130,246,.28)}',
'.rona-rail-pill--neutral{color:inherit;background:rgba(148,163,184,.08);border-color:rgba(148,163,184,.22)}',
'.rona-rail-fields{display:grid;grid-template-columns:108px 1fr;gap:8px 10px;align-items:start}',
'.rona-rail-label{opacity:.66;font-size:11px}',
'.rona-rail-value{font-weight:760;overflow-wrap:anywhere;font-size:12px}',
'.rona-rail-position-card{min-width:0}',
'.rona-rail-map{position:relative;overflow:hidden;min-height:340px;margin:0 0 14px;border:1px solid rgba(89,215,255,.14);border-radius:18px;background:radial-gradient(520px 260px at 58% 45%,rgba(41,100,145,.16),transparent 70%),linear-gradient(180deg,rgba(5,12,20,.86),rgba(6,13,20,.60))}',
'.rona-rail-map::after{content:"";position:absolute;inset:0;pointer-events:none;background-image:linear-gradient(rgba(255,255,255,.025) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.025) 1px,transparent 1px);background-size:32px 32px}',
'.rona-rail-map-title{position:absolute;z-index:2;left:16px;top:14px;font-size:12px;font-weight:900;letter-spacing:.06em;text-transform:uppercase}',
'.rona-rail-map-badge{position:absolute;z-index:2;right:14px;top:12px}',
'.rona-rail-map-canvas{position:absolute;inset:42px 10px 46px;display:grid;place-items:center}',
'.rona-rail-map-canvas svg{display:block;width:100%;height:100%;max-height:265px}',
'.rona-rail-map-note{position:absolute;z-index:2;left:16px;right:16px;bottom:13px;font-size:11px;line-height:1.4;opacity:.72}',
'.rona-rail-map [data-country]{fill:rgba(81,139,174,.11);stroke:rgba(121,202,237,.38);stroke-width:1.3;vector-effect:non-scaling-stroke}',
'.rona-rail-map [data-country=KZ],.rona-rail-map [data-country=UZ],.rona-rail-map [data-country=KG]{fill:rgba(76,225,184,.08);stroke:rgba(76,225,184,.42)}',
'.rona-rail-map text{fill:rgba(221,238,247,.66);font:700 14px Inter,Arial,sans-serif;letter-spacing:.02em}',
'.rona-rail-map .rona-map-route{fill:none;stroke:rgba(89,215,255,.34);stroke-width:2;stroke-dasharray:7 7;vector-effect:non-scaling-stroke}',
'.rona-rail-map .rona-map-node{fill:#59d7ff;stroke:rgba(255,255,255,.65);stroke-width:1.2;vector-effect:non-scaling-stroke}',
'.rona-rail-positions-table .rona-rail-table{min-width:900px}',
'.rona-rail-empty{padding:18px;border:1px dashed rgba(145,185,209,.18);border-radius:14px;font-size:12px;opacity:.72}',
'.rona-rail-loading{min-height:220px;display:grid;place-items:center;text-align:center}',
'@media(max-width:1250px){.rona-rail-workspace{grid-template-columns:minmax(280px,.8fr) minmax(520px,1.45fr)}.rona-rail-map{min-height:310px}}',
'@media(max-width:1040px){.rona-rail-workspace{grid-template-columns:1fr}.rona-rail-map{min-height:300px}.rona-rail-ops .rona-rail-table{min-width:720px}.rona-rail-ops .rona-rail-table th:nth-child(3),.rona-rail-ops .rona-rail-table td:nth-child(3),.rona-rail-ops .rona-rail-table th:nth-child(4),.rona-rail-ops .rona-rail-table td:nth-child(4){display:table-cell}}',
'@media(max-width:680px){.rona-rail-mini-kpis{grid-template-columns:1fr 1fr}.rona-rail-map{min-height:270px}.rona-rail-card{padding:14px!important}.rona-rail-fields{grid-template-columns:1fr;gap:3px}.rona-rail-map-title{left:12px}.rona-rail-map-note{left:12px;right:12px}}'
].join('');document.head.appendChild(s)}
function table(headers,rows,cls){var wrap=el('div','rona-rail-table-wrap'+(cls?' '+cls:'')),t=el('table','rona-rail-table'),thead=el('thead'),hr=el('tr'),tb=el('tbody');headers.forEach(function(h){hr.append(el('th','',h))});thead.append(hr);rows.forEach(function(row){var tr=el('tr');row.forEach(function(v){var td=el('td');if(v instanceof Node)td.append(v);else td.textContent=v===null||v===undefined||v===''?'—':String(v);tr.append(td)});tb.append(tr)});t.append(thead,tb);wrap.append(t);return wrap}
function miniKpi(title,value){var c=el('div','rona-rail-mini-kpi');c.append(el('div','rona-rail-mini-kpi-label',title),el('div','rona-rail-mini-kpi-value',String(value)));return c}
function card(title,extra){var c=el('section','rona-owner-card rona-rail-card'+(extra?' '+extra:''));if(title)c.append(el('h2','',title));return c}
function docKey(x){return String(x&&x.gu12_number||x&&x.document_number||x&&x.rail_document_id||'')}
function docStatus(x,exchange){var ws=Array.isArray(x&&x.wagons)?x.wagons:[];if(Number(exchange&&exchange.active_targets||0)===0)return pill('Мониторинг не запущен','warn');if(!ws.length)return pill('Вагоны не зарегистрированы','warn');if(ws.some(function(w){return !w.lastPositionAt}))return pill('Ожидаются позиции','warn');return pill('Позиции получены','success')}
function mapSvg(){return '<svg viewBox="0 0 920 340" role="img" aria-label="Карта стран СНГ для будущего мониторинга железнодорожных вагонов"><path data-country="RU" d="M180 56 L254 30 L365 41 L452 24 L560 43 L663 28 L784 62 L846 99 L824 135 L747 151 L676 139 L610 166 L518 145 L435 168 L349 139 L276 151 L207 122 Z"></path><path data-country="BY" d="M118 123 L172 111 L202 139 L179 168 L126 163 L101 143 Z"></path><path data-country="KZ" d="M317 178 L399 157 L487 176 L562 161 L650 186 L677 226 L630 252 L548 246 L489 267 L409 247 L344 255 L298 222 Z"></path><path data-country="UZ" d="M423 258 L484 249 L525 270 L505 300 L449 306 L405 286 Z"></path><path data-country="KG" d="M526 269 L575 262 L602 284 L575 305 L527 297 Z"></path><path data-country="TJ" d="M577 307 L620 296 L648 316 L617 332 L578 328 Z"></path><path data-country="TM" d="M356 280 L405 278 L432 306 L401 329 L348 321 L329 302 Z"></path><path data-country="AZ" d="M237 237 L275 229 L296 250 L276 273 L239 266 Z"></path><path data-country="AM" d="M213 250 L237 246 L248 270 L226 284 L207 269 Z"></path><path class="rona-map-route" d="M161 147 C250 169 300 202 383 222 S515 254 558 283"></path><circle class="rona-map-node" cx="161" cy="147" r="4"></circle><circle class="rona-map-node" cx="383" cy="222" r="4"></circle><circle class="rona-map-node" cx="558" cy="283" r="4"></circle><text x="450" y="92">Россия</text><text x="433" y="218">Казахстан</text><text x="441" y="287">Узбекистан</text><text x="530" y="290">Кыргызстан</text><text x="112" y="146">Беларусь</text></svg>'}
function mapPanel(exchange,wagons){var box=el('div','rona-rail-map');box.setAttribute('data-rail-map','cis');box.setAttribute('data-monitoring-active',Number(exchange&&exchange.active_targets||0)>0?'true':'false');box.append(el('div','rona-rail-map-title','Карта СНГ'));var badge=el('div','rona-rail-map-badge');badge.append(Number(exchange&&exchange.active_targets||0)>0?pill('Контур активен','success'):pill('Ожидает мониторинг','neutral'));box.append(badge);var canvas=el('div','rona-rail-map-canvas');canvas.innerHTML=mapSvg();box.append(canvas);var live=wagons.filter(function(w){return w&&w.lastPositionAt}).length,note=Number(exchange&&exchange.active_targets||0)>0?(live?'Подтверждённые позиции: '+live+'. Географические маркеры появятся после поступления координат из доверенного источника.':'Мониторинг активирован, но подтверждённые координаты вагонов пока не поступили.'):'Карта подготовлена под интерактивное движение вагонов. До подключения доверенного источника позиции на карту не наносятся.';box.append(el('div','rona-rail-map-note',note));return box}
function findTariffMatrix(page){if(tariffNode&&document.documentElement.contains(tariffNode))return tariffNode;var hs=qa('h1,h2,h3,h4,h5,.section-title,.card-title',page);for(var i=0;i<hs.length;i++){var t=String(hs[i].textContent||'').replace(/\s+/g,' ').trim().toLowerCase();if(t.indexOf('матриц')>=0&&t.indexOf('тариф')>=0){var n=hs[i].closest('section,.rona-owner-card,.card,.panel,[data-section]')||hs[i].parentElement;if(n&&n!==page){tariffNode=n;tariffNode.setAttribute('data-rona-rail-tariff-preserved','1');return tariffNode}}}return null}
function getHost(page){var host=q(':scope > .rona-owner-page-content',page);if(!host){host=el('div','rona-owner-page-content');host.setAttribute('data-owner-page','monitoring');page.append(host)}host.setAttribute('data-rona-rail-owner','current-first-v3');return host}
function isolateLegacy(page,host){var matrix=findTariffMatrix(page);if(matrix&&host.contains(matrix)&&!matrix.closest('[data-rail-current-root]'))matrix.remove();Array.from(page.children).forEach(function(n){if(n===host)return;n.classList.add('rona-owner-original-hidden');n.setAttribute('aria-hidden','true')});if(matrix&&!host.contains(matrix)){matrix.classList.remove('rona-owner-original-hidden');matrix.removeAttribute('aria-hidden');host.append(matrix)}return matrix}
function loadingShell(){var root=el('div','rona-rail-root');root.setAttribute('data-rail-current-root','loading');var hero=el('div','rona-visual-hero rona-rail-hero');var copy=el('div');copy.append(el('div','rona-visual-kicker','Железнодорожный контур'),el('div','rona-visual-title','Онлайн ЖД'),el('div','rona-visual-sub','Загрузка актуального состояния железнодорожного контура…'));hero.append(copy);root.append(hero);var c=card('', 'rona-rail-loading');c.append(el('div','rona-rail-muted','Получаем актуальные ГУ-12 и позиции вагонов.'));root.append(c);return root}
function renderShell(){ensureStyle();var page=q('#page-monitoring');if(!page)return false;var host=getHost(page),matrix=findTariffMatrix(page);if(matrix&&host.contains(matrix))matrix.remove();host.replaceChildren(loadingShell());if(matrix)host.append(matrix);isolateLegacy(page,host);page.classList.remove('rona-owner-hide');document.documentElement.classList.add('rona-rail-runtime-ready');return true}
function render(data,force){ensureStyle();var page=q('#page-monitoring');if(!page)return false;var rail=Array.isArray(data&&data.rail)?data.rail:[],exchange=data&&data.exchange||{},stamp=JSON.stringify({rail:rail,exchange:exchange,selected:selected});var host=getHost(page),marker=q('[data-rail-current-root]',host);if(!force&&stamp===lastStamp&&marker&&marker.getAttribute('data-rail-current-root')==='ready'){isolateLegacy(page,host);return true}lastStamp=stamp;var matrix=findTariffMatrix(page);if(matrix&&host.contains(matrix)&&!matrix.closest('[data-rail-current-root]'))matrix.remove();var root=el('div','rona-rail-root');root.setAttribute('data-rail-current-root','ready');root.setAttribute('data-rail-ui-version','v3');var hero=el('div','rona-visual-hero rona-rail-hero'),copy=el('div');copy.append(el('div','rona-visual-kicker','Железнодорожный контур'),el('div','rona-visual-title','Онлайн ЖД'),el('div','rona-visual-sub','ГУ-12, подтверждённые вагоны и рабочее пространство мониторинга. Матрица ЖД-тарифов ниже сохраняется без изменений.'));hero.append(copy);root.append(hero);
var wagons=[];rail.forEach(function(x){(Array.isArray(x.wagons)?x.wagons:[]).forEach(function(w){wagons.push(w)})});var attention=Number(exchange.conflicts||0)+wagons.filter(function(w){var st=String(w&&w.status||'').toUpperCase();return !w.lastPositionAt||st.indexOf('WAIT')>=0||st.indexOf('ERROR')>=0||st.indexOf('HOLD')>=0||st.indexOf('CONFLICT')>=0}).length,active=Number(exchange.active_targets||0),last=exchange.last_success?fmtDate(exchange.last_success,true):'—';var visible=selected==='ALL'?rail:rail.filter(function(x){return docKey(x)===selected}),chosen=visible[0]||rail[0]||null;
var workspace=el('div','rona-rail-workspace'),left=el('div','rona-rail-left'),control=card('ЖД-контур','rona-rail-control');var mini=el('div','rona-rail-mini-kpis');mini.append(miniKpi('ГУ-12',rail.length),miniKpi('Вагоны',wagons.length),miniKpi('Активный мониторинг',active),miniKpi('Требуют внимания',attention));control.append(mini);var filters=el('div','rona-rail-filters');filters.append(btn('Все ГУ-12',selected==='ALL',function(){selected='ALL';lastStamp='';render(data,true)}));rail.forEach(function(x){var key=docKey(x);filters.append(btn('ГУ-12 '+(key||'—'),selected===key,function(){selected=key;lastStamp='';render(data,true)}))});control.append(filters);if(active===0)control.append(el('div','rona-rail-banner','Онлайн-мониторинг пока не запущен. Показываются только подтверждённые ЖД-документы и фактически зарегистрированные позиции.'));left.append(control);
var rows=visible.map(function(x){var ws=Array.isArray(x.wagons)?x.wagons:[];return[x.gu12_number||x.document_number||x.rail_document_id||'—',x.deal_id||'—',fmtDate(x.document_date,false),x.route_text||'—',String(ws.length),docStatus(x,exchange)]}),ops=card('Операционная картина ЖД','rona-rail-ops');ops.append(rows.length?table(['ГУ-12','Сделка','Дата','Маршрут','Вагоны','Статус'],rows):el('div','rona-rail-empty','Подтверждённые ГУ-12 отсутствуют.'));left.append(ops);
var info=card('Карточка ГУ-12');if(chosen){var fields=el('div','rona-rail-fields'),ws=Array.isArray(chosen.wagons)?chosen.wagons:[];[['Номер',chosen.gu12_number||chosen.document_number||chosen.rail_document_id||'—'],['Сделка',chosen.deal_id||'—'],['Дата',fmtDate(chosen.document_date,false)],['Маршрут',chosen.route_text||'—'],['Вагонов',String(ws.length)],['Последний обмен',last]].forEach(function(p){fields.append(el('div','rona-rail-label',p[0]),el('div','rona-rail-value',p[1]))});info.append(fields)}else info.append(el('div','rona-rail-empty','Выбранная ГУ-12 отсутствует.'));left.append(info);
var pos=card('', 'rona-rail-position-card'),head=el('div','rona-rail-card-header'),headCopy=el('div');headCopy.append(el('h2','','Позиции вагонов'),el('div','rona-rail-muted',chosen?'Выбранная ГУ-12: '+(docKey(chosen)||'—'):'Выберите ГУ-12 для просмотра позиций.'));head.append(headCopy,pill(active?'Мониторинг':'Подготовлено','info'));pos.append(head,mapPanel(exchange,chosen&&Array.isArray(chosen.wagons)?chosen.wagons:[]));var chosenWagons=chosen&&Array.isArray(chosen.wagons)?chosen.wagons:[];if(chosenWagons.length)pos.append(table(['Вагон','Текущая станция','Код','Операция','Статус','Последнее обновление'],chosenWagons.map(function(w){return[w.wagonNumber||'—',w.station||'—',w.stationCode||'—',w.operation||'—',pill(w.status||'Нет статуса',w.lastPositionAt?'info':'warn'),fmtDate(w.lastPositionAt,true)]}),'rona-rail-positions-table'));else pos.append(el('div','rona-rail-empty','По выбранной ГУ-12 подтверждённые вагоны пока не зарегистрированы. Карта остаётся готовой к будущему онлайн-мониторингу.'));
workspace.append(left,pos);root.append(workspace);host.replaceChildren(root);if(matrix){matrix.classList.remove('rona-owner-original-hidden');matrix.removeAttribute('aria-hidden');host.append(matrix)}isolateLegacy(page,host);page.classList.remove('rona-owner-hide');document.documentElement.classList.add('rona-rail-runtime-ready','rona-rail-current-ready');window.__RONA_RAIL_CURRENT_STATE__={version:'v3',generatedAt:new Date().toISOString(),railCount:rail.length,wagonCount:wagons.length,monitoringTargets:active,tariffMatrixPreserved:!!matrix};return true}
function renderError(message){var page=q('#page-monitoring');if(!page)return;var host=getHost(page),matrix=findTariffMatrix(page);if(matrix&&host.contains(matrix))matrix.remove();var root=loadingShell();root.setAttribute('data-rail-current-root','error');var c=q('.rona-rail-loading',root);if(c)c.replaceChildren(el('div','rona-rail-muted','Не удалось получить актуальное состояние ЖД. '+String(message||'')));host.replaceChildren(root);if(matrix)host.append(matrix);isolateLegacy(page,host)}
async function sync(force){if(busy)return;busy=true;try{var data=await api('/admin/bootstrap');snapshot=data;window.__RONA_RAIL_2E_SNAPSHOT__=data;window.__RONA_RAIL_CURRENT_SNAPSHOT__=data;render(data,!!force);window.__RONA_RAIL_2E_ERROR__=null;window.__RONA_RAIL_CURRENT_ERROR__=null}catch(e){var m=String(e&&e.message||e);window.__RONA_RAIL_2E_ERROR__=m;window.__RONA_RAIL_CURRENT_ERROR__=m;if(!snapshot)renderError(m)}finally{busy=false}}
function bindNav(){var nav=q('#nav button[data-page="monitoring"]');if(nav&&!nav.__ronaRailCurrentBound){nav.__ronaRailCurrentBound=true;nav.addEventListener('click',function(){if(snapshot)render(snapshot,true);else renderShell();setTimeout(function(){sync(true)},0)})}}
function repair(){repairQueued=false;var page=q('#page-monitoring');if(!page)return;var host=getHost(page);findTariffMatrix(page);if(!q('[data-rail-current-root]',host)){if(snapshot)render(snapshot,true);else renderShell()}else isolateLegacy(page,host)}
function queueRepair(){if(repairQueued)return;repairQueued=true;Promise.resolve().then(repair)}
function watch(){var page=q('#page-monitoring');if(!page||observer)return;observer=new MutationObserver(queueRepair);observer.observe(page,{childList:true,subtree:true});window.__RONA_RAIL_CURRENT_OBSERVER__=observer}
function start(){ensureStyle();snapshot=window.__RONA_OWNER_ADMIN_SNAPSHOT__||null;if(snapshot)render(snapshot,true);else renderShell();bindNav();watch();sync(true);if(!timer)timer=setInterval(function(){sync(false)},30000)}
if(location.pathname==='/portal/admin'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start()}
})();`;
export async function onRequest(){return new Response(SCRIPT,{status:200,headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache','expires':'0','x-content-type-options':'nosniff','x-rona-rail-ui':'current-first-map-v3'}})}
